[2025-07-14T04:00:12.554+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_analise_desempenho_revendas.executar_query_dataset scheduled__2025-07-13T04:00:00+00:00 [queued]>
[2025-07-14T04:00:12.572+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_analise_desempenho_revendas.executar_query_dataset scheduled__2025-07-13T04:00:00+00:00 [queued]>
[2025-07-14T04:00:12.572+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-07-14T04:00:12.673+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): executar_query_dataset> on 2025-07-13 04:00:00+00:00
[2025-07-14T04:00:12.682+0000] {standard_task_runner.py:60} INFO - Started process 1207195 to run task
[2025-07-14T04:00:12.690+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'DAG_analise_desempenho_revendas', 'executar_query_dataset', 'scheduled__2025-07-13T04:00:00+00:00', '--job-id', '511', '--raw', '--subdir', 'DAGS_FOLDER/DagAnaliseDesempenhoRevendas.py', '--cfg-path', '/tmp/tmpkrt8bzhs']
[2025-07-14T04:00:12.695+0000] {standard_task_runner.py:88} INFO - Job 511: Subtask executar_query_dataset
[2025-07-14T04:00:13.159+0000] {task_command.py:423} INFO - Running <TaskInstance: DAG_analise_desempenho_revendas.executar_query_dataset scheduled__2025-07-13T04:00:00+00:00 [running]> on host 99f5714845f7
[2025-07-14T04:00:13.468+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_analise_desempenho_revendas' AIRFLOW_CTX_TASK_ID='executar_query_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-07-13T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-13T04:00:00+00:00'
[2025-07-14T04:00:13.491+0000] {base.py:83} INFO - Using connection ID 'dataset_comercial_database' for task execution.
[2025-07-14T04:00:14.365+0000] {warnings.py:109} WARNING - /opt/***/dags/DAG_atualizacao_desempenho_revendas/AnaliseDesempenhoRevendas.py:56: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql, connection_database)

[2025-07-14T04:00:15.572+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-14T04:00:15.590+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=DAG_analise_desempenho_revendas, task_id=executar_query_dataset, execution_date=20250713T040000, start_date=20250714T040012, end_date=20250714T040015
[2025-07-14T04:00:15.751+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-14T04:00:16.037+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
