[2025-06-24T04:30:05.001+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_atualizacao_cadastral_revendas.organized_response_database scheduled__2025-06-23T04:30:00+00:00 [queued]>
[2025-06-24T04:30:05.016+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_atualizacao_cadastral_revendas.organized_response_database scheduled__2025-06-23T04:30:00+00:00 [queued]>
[2025-06-24T04:30:05.017+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-24T04:30:05.062+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): organized_response_database> on 2025-06-23 04:30:00+00:00
[2025-06-24T04:30:05.069+0000] {standard_task_runner.py:60} INFO - Started process 178269 to run task
[2025-06-24T04:30:05.075+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'DAG_atualizacao_cadastral_revendas', 'organized_response_database', 'scheduled__2025-06-23T04:30:00+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/DagDatasetComercial.py', '--cfg-path', '/tmp/tmph0srn7v4']
[2025-06-24T04:30:05.077+0000] {standard_task_runner.py:88} INFO - Job 199: Subtask organized_response_database
[2025-06-24T04:30:05.200+0000] {task_command.py:423} INFO - Running <TaskInstance: DAG_atualizacao_cadastral_revendas.organized_response_database scheduled__2025-06-23T04:30:00+00:00 [running]> on host 99f5714845f7
[2025-06-24T04:30:05.482+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_atualizacao_cadastral_revendas' AIRFLOW_CTX_TASK_ID='organized_response_database' AIRFLOW_CTX_EXECUTION_DATE='2025-06-23T04:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-23T04:30:00+00:00'
[2025-06-24T04:30:05.668+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/75620-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:05.669+0000] {logging_mixin.py:188} INFO - Revenda A7 Soluções organizada com sucesso !
[2025-06-24T04:30:05.797+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/80540-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862df0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:05.798+0000] {logging_mixin.py:188} INFO - Revenda AB Soluções em TI organizada com sucesso !
[2025-06-24T04:30:05.924+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21070-032/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82e6d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:05.925+0000] {logging_mixin.py:188} INFO - Revenda Adonai Automação Comercial organizada com sucesso !
[2025-06-24T04:30:06.053+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/39801-240/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82ef70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:06.054+0000] {logging_mixin.py:188} INFO - Revenda ADV SIG organizada com sucesso !
[2025-06-24T04:30:06.183+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88400-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82ed30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:06.183+0000] {logging_mixin.py:188} INFO - Revenda A e A Dist. de Informática - Softart organizada com sucesso !
[2025-06-24T04:30:06.317+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21235-604/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82e5b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:06.318+0000] {logging_mixin.py:188} INFO - Revenda Af Suporte organizada com sucesso !
[2025-06-24T04:30:07.449+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/60115-222/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84bd90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:07.450+0000] {logging_mixin.py:188} INFO - Revenda Agedata Sistemas organizada com sucesso !
[2025-06-24T04:30:08.605+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78130-435/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8626a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:08.605+0000] {logging_mixin.py:188} INFO - Revenda AIO Solucoes organizada com sucesso !
[2025-06-24T04:30:08.734+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37701-706/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d837850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:08.734+0000] {logging_mixin.py:188} INFO - Revenda AllTecInfo organizada com sucesso !
[2025-06-24T04:30:09.881+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78460-606/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c0130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:09.882+0000] {logging_mixin.py:188} INFO - Revenda Alpha Systemas e informática organizada com sucesso !
[2025-06-24T04:30:11.033+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85857-270/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8625e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:11.034+0000] {logging_mixin.py:188} INFO - Revenda Alternativa Automação Comercial organizada com sucesso !
[2025-06-24T04:30:12.185+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78575-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:12.186+0000] {logging_mixin.py:188} INFO - Revenda Amigo do Micro organizada com sucesso !
[2025-06-24T04:30:13.337+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85856-530/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d837f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:13.338+0000] {logging_mixin.py:188} INFO - Revenda AND Consultores Associados organizada com sucesso !
[2025-06-24T04:30:14.489+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/82600-130/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d837430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:14.489+0000] {logging_mixin.py:188} INFO - Revenda APRN Soluções organizada com sucesso !
[2025-06-24T04:30:15.641+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55540-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c0850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:15.641+0000] {logging_mixin.py:188} INFO - Revenda Ary Sistemas de Gestão e Informatica (RNS) organizada com sucesso !
[2025-06-24T04:30:15.769+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/66113-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82e130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:15.770+0000] {logging_mixin.py:188} INFO - Revenda Asteqesystem organizada com sucesso !
[2025-06-24T04:30:16.921+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/76908-430/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82e9d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:16.922+0000] {logging_mixin.py:188} INFO - Revenda Atrium Sistemas organizada com sucesso !
[2025-06-24T04:30:18.073+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/27265-435/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c0d60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:18.074+0000] {logging_mixin.py:188} INFO - Revenda Automac Digitron organizada com sucesso !
[2025-06-24T04:30:19.225+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29900-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c0430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:19.226+0000] {logging_mixin.py:188} INFO - Revenda Automaquinas - Automação Comercial organizada com sucesso !
[2025-06-24T04:30:20.379+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/44003-198/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:20.380+0000] {logging_mixin.py:188} INFO - Revenda Autosyste Tecnologia e Inovação organizada com sucesso !
[2025-06-24T04:30:21.529+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/25515-520/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8624c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:21.530+0000] {logging_mixin.py:188} INFO - Revenda Autotech Informática organizada com sucesso !
[2025-06-24T04:30:22.681+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/22710-112/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82f130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:22.682+0000] {logging_mixin.py:188} INFO - Revenda Bellabyte organizada com sucesso !
[2025-06-24T04:30:22.809+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/68900-075/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82f9d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:22.810+0000] {logging_mixin.py:188} INFO - Revenda Bitech organizada com sucesso !
[2025-06-24T04:30:23.961+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29645-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8628e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:23.962+0000] {logging_mixin.py:188} INFO - Revenda Boldtsoft Sistemas organizada com sucesso !
[2025-06-24T04:30:25.112+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/66623-268/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:25.113+0000] {logging_mixin.py:188} INFO - Revenda BRAZ TI organizada com sucesso !
[2025-06-24T04:30:26.265+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88352-001/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82f880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:26.266+0000] {logging_mixin.py:188} INFO - Revenda Brusoft Informatica organizada com sucesso !
[2025-06-24T04:30:27.417+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88312-260/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82ff70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:27.418+0000] {logging_mixin.py:188} INFO - Revenda Brvatech organizada com sucesso !
[2025-06-24T04:30:28.569+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/70714-020/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:28.569+0000] {logging_mixin.py:188} INFO - Revenda Canal Tecnico (Lumi) organizada com sucesso !
[2025-06-24T04:30:28.697+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/57020-260/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:28.698+0000] {logging_mixin.py:188} INFO - Revenda Casa das Impressoras organizada com sucesso !
[2025-06-24T04:30:29.850+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85852-130/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c29d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:29.851+0000] {logging_mixin.py:188} INFO - Revenda CASTERS organizada com sucesso !
[2025-06-24T04:30:31.001+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55016-080/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8340a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:31.002+0000] {logging_mixin.py:188} INFO - Revenda Centec Equipamentos organizada com sucesso !
[2025-06-24T04:30:32.152+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/57442-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b7e20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:32.153+0000] {logging_mixin.py:188} INFO - Revenda CK Tech Consultoria organizada com sucesso !
[2025-06-24T04:30:33.305+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85065-420/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:33.306+0000] {logging_mixin.py:188} INFO - Revenda Compass Tecnologia da Informação organizada com sucesso !
[2025-06-24T04:30:34.455+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/38400-694/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:34.456+0000] {logging_mixin.py:188} INFO - Revenda Compucenter Software organizada com sucesso !
[2025-06-24T04:30:35.609+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/28735-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82f160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:35.610+0000] {logging_mixin.py:188} INFO - Revenda Conexão Informática Ltda organizada com sucesso !
[2025-06-24T04:30:35.738+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/57120-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82fa00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:35.739+0000] {logging_mixin.py:188} INFO - Revenda Connect System Soluções em Tecnologia organizada com sucesso !
[2025-06-24T04:30:36.890+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/69047-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2af0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:36.891+0000] {logging_mixin.py:188} INFO - Revenda Conte Certo Serviços organizada com sucesso !
[2025-06-24T04:30:38.041+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/15085-310/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:38.041+0000] {logging_mixin.py:188} INFO - Revenda Control Biz organizada com sucesso !
[2025-06-24T04:30:39.192+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55004-270/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b3a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:39.192+0000] {logging_mixin.py:188} INFO - Revenda CTi - Centro Técnico de Informática organizada com sucesso !
[2025-06-24T04:30:40.345+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21380-008/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:40.346+0000] {logging_mixin.py:188} INFO - Revenda D&A Automação Comercial organizada com sucesso !
[2025-06-24T04:30:41.498+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89228-080/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:41.499+0000] {logging_mixin.py:188} INFO - Revenda DALTEC Automacao Comercial organizada com sucesso !
[2025-06-24T04:30:42.649+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/38740-082/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82f340>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:42.649+0000] {logging_mixin.py:188} INFO - Revenda DataConta Gestão de Negócios organizada com sucesso !
[2025-06-24T04:30:42.778+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89801-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:42.778+0000] {logging_mixin.py:188} INFO - Revenda Dataproxy organizada com sucesso !
[2025-06-24T04:30:43.930+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/91220-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834c70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:43.930+0000] {logging_mixin.py:188} INFO - Revenda DCODER organizada com sucesso !
[2025-06-24T04:30:45.080+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/77405-130/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:45.080+0000] {logging_mixin.py:188} INFO - Revenda D Data Soluções organizada com sucesso !
[2025-06-24T04:30:46.233+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/53421-321/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:46.233+0000] {logging_mixin.py:188} INFO - Revenda DGTEC organizada com sucesso !
[2025-06-24T04:30:47.385+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46400-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82f400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:47.386+0000] {logging_mixin.py:188} INFO - Revenda Digito Informatica organizada com sucesso !
[2025-06-24T04:30:48.537+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85060-080/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82fa90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:48.538+0000] {logging_mixin.py:188} INFO - Revenda Dikoc Soluções em Software organizada com sucesso !
[2025-06-24T04:30:49.689+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/81200-150/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cb310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:49.690+0000] {logging_mixin.py:188} INFO - Revenda DMK Sistemas e Soluções - HSI organizada com sucesso !
[2025-06-24T04:30:49.822+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78635-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:49.822+0000] {logging_mixin.py:188} INFO - Revenda DMZ Informatica organizada com sucesso !
[2025-06-24T04:30:50.970+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/13843-201/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862a00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:50.971+0000] {logging_mixin.py:188} INFO - Revenda Dolphin Consultoria organizada com sucesso !
[2025-06-24T04:30:52.121+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/28913-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:52.121+0000] {logging_mixin.py:188} INFO - Revenda DSM Consultoria em T.I. organizada com sucesso !
[2025-06-24T04:30:53.273+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/79004-440/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:53.274+0000] {logging_mixin.py:188} INFO - Revenda Duall Tech organizada com sucesso !
[2025-06-24T04:30:54.428+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/41820-020/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834a00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:54.430+0000] {logging_mixin.py:188} INFO - Revenda DWH Comercio de Alimentos organizada com sucesso !
[2025-06-24T04:30:55.577+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88702-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cba30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:55.578+0000] {logging_mixin.py:188} INFO - Revenda Edcom Automação Comercial organizada com sucesso !
[2025-06-24T04:30:55.710+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/75901-630/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834d00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:55.711+0000] {logging_mixin.py:188} INFO - Revenda Eleve Tecnologia organizada com sucesso !
[2025-06-24T04:30:56.857+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88106-500/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:56.857+0000] {logging_mixin.py:188} INFO - Revenda Emlink Solucoes Empresariais organizada com sucesso !
[2025-06-24T04:30:58.009+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/64200-250/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:58.010+0000] {logging_mixin.py:188} INFO - Revenda Exatop Certificação Digital e Sistemas organizada com sucesso !
[2025-06-24T04:30:59.161+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89258-730/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8629a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:30:59.162+0000] {logging_mixin.py:188} INFO - Revenda Exodus Informática organizada com sucesso !
[2025-06-24T04:31:00.315+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89280-328/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cb340>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:00.315+0000] {logging_mixin.py:188} INFO - Revenda Extrema Software de Gestão organizada com sucesso !
[2025-06-24T04:31:01.465+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/63660-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cb550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:01.465+0000] {logging_mixin.py:188} INFO - Revenda F5 Suporte e Automacão Comercial organizada com sucesso !
[2025-06-24T04:31:02.615+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/13273-410/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82f310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:02.617+0000] {logging_mixin.py:188} INFO - Revenda Facilita Sistemas organizada com sucesso !
[2025-06-24T04:31:02.746+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95670-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:02.747+0000] {logging_mixin.py:188} INFO - Revenda Facilsys organizada com sucesso !
[2025-06-24T04:31:03.897+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58808-485/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b7640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:03.897+0000] {logging_mixin.py:188} INFO - Revenda F & F Soluções Empresariais organizada com sucesso !
[2025-06-24T04:31:05.049+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88160-064/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cb6d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:05.050+0000] {logging_mixin.py:188} INFO - Revenda FKSIS - Sistemas de Gestão organizada com sucesso !
[2025-06-24T04:31:06.203+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88354-610/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cbf10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:06.203+0000] {logging_mixin.py:188} INFO - Revenda FlorySoftt organizada com sucesso !
[2025-06-24T04:31:07.353+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/23860-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:07.354+0000] {logging_mixin.py:188} INFO - Revenda Fn Info House organizada com sucesso !
[2025-06-24T04:31:08.505+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/63502-769/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82f070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:08.506+0000] {logging_mixin.py:188} INFO - Revenda FS Informatica organizada com sucesso !
[2025-06-24T04:31:09.657+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/84320-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8348e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:09.657+0000] {logging_mixin.py:188} INFO - Revenda Fusion Sistemas e Informatica organizada com sucesso !
[2025-06-24T04:31:09.786+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59900-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8343a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:09.787+0000] {logging_mixin.py:188} INFO - Revenda Gilmaq Automação Comercial organizada com sucesso !
[2025-06-24T04:31:10.937+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55825-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cb9d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:10.938+0000] {logging_mixin.py:188} INFO - Revenda GM Soluções em Informática organizada com sucesso !
[2025-06-24T04:31:12.089+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/01311-927/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cb520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:12.090+0000] {logging_mixin.py:188} INFO - Revenda Grupo GUUW organizada com sucesso !
[2025-06-24T04:31:13.243+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37800-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:13.244+0000] {logging_mixin.py:188} INFO - Revenda Guaxutec organizada com sucesso !
[2025-06-24T04:31:14.391+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88508-190/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:14.392+0000] {logging_mixin.py:188} INFO - Revenda HSI Automação Comercial organizada com sucesso !
[2025-06-24T04:31:15.544+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/20756-100/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862a90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:15.545+0000] {logging_mixin.py:188} INFO - Revenda HWC Soluções organizada com sucesso !
[2025-06-24T04:31:15.674+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59500-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862eb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:15.675+0000] {logging_mixin.py:188} INFO - Revenda I7 Automação Comercial organizada com sucesso !
[2025-06-24T04:31:16.826+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29280-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cb820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:16.827+0000] {logging_mixin.py:188} INFO - Revenda Ideal Soluções Empresariais organizada com sucesso !
[2025-06-24T04:31:17.977+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59570-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cb8b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:17.978+0000] {logging_mixin.py:188} INFO - Revenda ID Tecnologia organizada com sucesso !
[2025-06-24T04:31:19.127+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/06454-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8349d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:19.128+0000] {logging_mixin.py:188} INFO - Revenda IFFI Soluções organizada com sucesso !
[2025-06-24T04:31:20.279+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/69980-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:20.280+0000] {logging_mixin.py:188} INFO - Revenda IG TEC organizada com sucesso !
[2025-06-24T04:31:21.433+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58900-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82fbb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:21.434+0000] {logging_mixin.py:188} INFO - Revenda INFOPRINTER organizada com sucesso !
[2025-06-24T04:31:22.585+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21011-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:22.586+0000] {logging_mixin.py:188} INFO - Revenda INFORMIT organizada com sucesso !
[2025-06-24T04:31:22.715+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/69303-045/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cbb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:22.716+0000] {logging_mixin.py:188} INFO - Revenda Infor Serviços organizada com sucesso !
[2025-06-24T04:31:23.865+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/48601-270/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cb6a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:23.866+0000] {logging_mixin.py:188} INFO - Revenda Infortec Automacao Comercial organizada com sucesso !
[2025-06-24T04:31:25.021+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46430-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:25.021+0000] {logging_mixin.py:188} INFO - Revenda Infotek organizada com sucesso !
[2025-06-24T04:31:26.169+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/26535-190/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862910>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:26.170+0000] {logging_mixin.py:188} INFO - Revenda Innovati Tecnologia (INW Store) organizada com sucesso !
[2025-06-24T04:31:27.321+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50865-090/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82f9a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:27.322+0000] {logging_mixin.py:188} INFO - Revenda Inova Software organizada com sucesso !
[2025-06-24T04:31:28.472+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55130-970/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82f520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:28.473+0000] {logging_mixin.py:188} INFO - Revenda Inspire Consult & Informatica  organizada com sucesso !
[2025-06-24T04:31:29.625+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89801-106/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8628e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:29.626+0000] {logging_mixin.py:188} INFO - Revenda Inteltix Tecnologia (Center) organizada com sucesso !
[2025-06-24T04:31:29.753+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/79823-290/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b7ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:29.754+0000] {logging_mixin.py:188} INFO - Revenda J7 Automação Comercial - System HD organizada com sucesso !
[2025-06-24T04:31:30.905+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78360-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cb040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:30.905+0000] {logging_mixin.py:188} INFO - Revenda Jann Informatica organizada com sucesso !
[2025-06-24T04:31:32.057+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/76997-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cbaf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:32.058+0000] {logging_mixin.py:188} INFO - Revenda JB Tecnologia organizada com sucesso !
[2025-06-24T04:31:33.207+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/68460-245/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8341c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:33.208+0000] {logging_mixin.py:188} INFO - Revenda J & E Soluções organizada com sucesso !
[2025-06-24T04:31:34.361+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46430-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:34.361+0000] {logging_mixin.py:188} INFO - Revenda JExpress organizada com sucesso !
[2025-06-24T04:31:35.512+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58077-062/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cba60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:35.512+0000] {logging_mixin.py:188} INFO - Revenda J F Soluções Informatica organizada com sucesso !
[2025-06-24T04:31:36.665+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/69058-580/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cb5b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:36.666+0000] {logging_mixin.py:188} INFO - Revenda J F Tech Tecnologia & Sistemas organizada com sucesso !
[2025-06-24T04:31:36.795+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/31255-780/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b7ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:36.795+0000] {logging_mixin.py:188} INFO - Revenda JHLS Automação Comercial organizada com sucesso !
[2025-06-24T04:31:37.945+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/12914-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:37.945+0000] {logging_mixin.py:188} INFO - Revenda Jinsei Contabilidade organizada com sucesso !
[2025-06-24T04:31:39.095+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/27197-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82fa90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:39.096+0000] {logging_mixin.py:188} INFO - Revenda JJ Serviços organizada com sucesso !
[2025-06-24T04:31:40.249+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/49055-620/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d74c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:40.250+0000] {logging_mixin.py:188} INFO - Revenda JM Informatica organizada com sucesso !
[2025-06-24T04:31:41.401+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89220-110/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:41.402+0000] {logging_mixin.py:188} INFO - Revenda JP Automação Comercial organizada com sucesso !
[2025-06-24T04:31:42.553+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78250-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84bd90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:42.554+0000] {logging_mixin.py:188} INFO - Revenda JSR Automação Comercial  organizada com sucesso !
[2025-06-24T04:31:42.682+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89700-166/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82f160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:42.682+0000] {logging_mixin.py:188} INFO - Revenda Kernel Sistemas organizada com sucesso !
[2025-06-24T04:31:43.833+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/14010-180/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82f190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:43.834+0000] {logging_mixin.py:188} INFO - Revenda KMCI Tecnologia em Automação organizada com sucesso !
[2025-06-24T04:31:44.986+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/25555-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:44.986+0000] {logging_mixin.py:188} INFO - Revenda Komputronic do Brasil organizada com sucesso !
[2025-06-24T04:31:46.137+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29052-170/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:46.138+0000] {logging_mixin.py:188} INFO - Revenda KSC Sistemas organizada com sucesso !
[2025-06-24T04:31:47.289+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50010-100/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c24f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:47.289+0000] {logging_mixin.py:188} INFO - Revenda L&D Comercio e Tecnologia organizada com sucesso !
[2025-06-24T04:31:48.439+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/25935-530/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:48.440+0000] {logging_mixin.py:188} INFO - Revenda LD Tech organizada com sucesso !
[2025-06-24T04:31:49.593+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29375-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b5b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:49.594+0000] {logging_mixin.py:188} INFO - Revenda LF Sistemas organizada com sucesso !
[2025-06-24T04:31:49.726+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/39400-215/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:49.727+0000] {logging_mixin.py:188} INFO - Revenda LiderTech organizada com sucesso !
[2025-06-24T04:31:50.873+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/93700-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:50.874+0000] {logging_mixin.py:188} INFO - Revenda Life Sistemas  organizada com sucesso !
[2025-06-24T04:31:52.026+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/20250-450/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82f370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:52.026+0000] {logging_mixin.py:188} INFO - Revenda LL Tecnologia organizada com sucesso !
[2025-06-24T04:31:53.178+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/36884-004/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82ff70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:53.178+0000] {logging_mixin.py:188} INFO - Revenda LMD Sistemas organizada com sucesso !
[2025-06-24T04:31:54.330+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/22730-001/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:54.331+0000] {logging_mixin.py:188} INFO - Revenda Logitec 2000 Informatica organizada com sucesso !
[2025-06-24T04:31:55.481+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37470-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7013da4070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:55.482+0000] {logging_mixin.py:188} INFO - Revenda Macmos organizada com sucesso !
[2025-06-24T04:31:56.633+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59300-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:56.634+0000] {logging_mixin.py:188} INFO - Revenda Mape Informatica organizada com sucesso !
[2025-06-24T04:31:56.764+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89900-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:56.765+0000] {logging_mixin.py:188} INFO - Revenda Marcka Informática e Sistemas organizada com sucesso !
[2025-06-24T04:31:57.913+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58041-070/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82fac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:57.914+0000] {logging_mixin.py:188} INFO - Revenda Matechinfo organizada com sucesso !
[2025-06-24T04:31:59.066+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88355-393/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834be0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:31:59.066+0000] {logging_mixin.py:188} INFO - Revenda MB Tecnologia organizada com sucesso !
[2025-06-24T04:32:00.219+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/82015-520/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8349a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:00.219+0000] {logging_mixin.py:188} INFO - Revenda MC2 Tecnologia organizada com sucesso !
[2025-06-24T04:32:01.369+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89562-180/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c29d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:01.369+0000] {logging_mixin.py:188} INFO - Revenda MCR Sistemas (RS-AMX) organizada com sucesso !
[2025-06-24T04:32:02.522+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21660-060/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b72b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:02.523+0000] {logging_mixin.py:188} INFO - Revenda MD Tech Automação organizada com sucesso !
[2025-06-24T04:32:03.673+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46430-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82fbb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:03.673+0000] {logging_mixin.py:188} INFO - Revenda Megasoft Informatica organizada com sucesso !
[2025-06-24T04:32:03.802+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95270-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82fa00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:03.803+0000] {logging_mixin.py:188} INFO - Revenda Mercantec Soluções organizada com sucesso !
[2025-06-24T04:32:04.952+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88310-661/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862790>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:04.953+0000] {logging_mixin.py:188} INFO - Revenda Mikrox "Somadatta" organizada com sucesso !
[2025-06-24T04:32:06.108+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/63010-127/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:06.108+0000] {logging_mixin.py:188} INFO - Revenda M. Nobre (Terabyte) organizada com sucesso !
[2025-06-24T04:32:07.257+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/32310-210/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8625e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:07.258+0000] {logging_mixin.py:188} INFO - Revenda MRsis Automação organizada com sucesso !
[2025-06-24T04:32:08.409+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37062-170/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:08.409+0000] {logging_mixin.py:188} INFO - Revenda M&R Soluções - Grupo ATL organizada com sucesso !
[2025-06-24T04:32:09.561+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/47640-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2d00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:09.562+0000] {logging_mixin.py:188} INFO - Revenda Multi Soft organizada com sucesso !
[2025-06-24T04:32:09.693+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78390-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c26a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:09.694+0000] {logging_mixin.py:188} INFO - Revenda NewCompras.com.br organizada com sucesso !
[2025-06-24T04:32:10.841+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/67030-080/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834e80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:10.842+0000] {logging_mixin.py:188} INFO - Revenda NEWTEF Automação organizada com sucesso !
[2025-06-24T04:32:11.993+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50960-400/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8291c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:11.994+0000] {logging_mixin.py:188} INFO - Revenda Next Store organizada com sucesso !
[2025-06-24T04:32:13.145+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37730-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d829a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:13.146+0000] {logging_mixin.py:188} INFO - Revenda Nova Loja organizada com sucesso !
[2025-06-24T04:32:14.297+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/17210-420/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c22e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:14.297+0000] {logging_mixin.py:188} INFO - Revenda NovaPC organizada com sucesso !
[2025-06-24T04:32:15.449+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/39400-163/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b7f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:15.449+0000] {logging_mixin.py:188} INFO - Revenda Optimus - Gestão organizada com sucesso !
[2025-06-24T04:32:16.601+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/98803-412/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8344f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:16.602+0000] {logging_mixin.py:188} INFO - Revenda Otimizer Consultoria em Sistemas organizada com sucesso !
[2025-06-24T04:32:16.731+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/62500-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:16.732+0000] {logging_mixin.py:188} INFO - Revenda Otimize Soluções organizada com sucesso !
[2025-06-24T04:32:17.881+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95034-160/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:17.882+0000] {logging_mixin.py:188} INFO - Revenda P21 Software organizada com sucesso !
[2025-06-24T04:32:19.031+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50980-480/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d829190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:19.032+0000] {logging_mixin.py:188} INFO - Revenda PALM Soluções organizada com sucesso !
[2025-06-24T04:32:20.185+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/84040-010/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8628e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:20.185+0000] {logging_mixin.py:188} INFO - Revenda Parceria Informatica organizada com sucesso !
[2025-06-24T04:32:21.336+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88330-725/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:21.337+0000] {logging_mixin.py:188} INFO - Revenda PDV Automação organizada com sucesso !
[2025-06-24T04:32:22.489+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/38700-001/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:22.489+0000] {logging_mixin.py:188} INFO - Revenda PEG Informatica organizada com sucesso !
[2025-06-24T04:32:23.641+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95200-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:23.642+0000] {logging_mixin.py:188} INFO - Revenda Piramide Automação e Informatica organizada com sucesso !
[2025-06-24T04:32:23.770+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/70314-900/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2a00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:23.771+0000] {logging_mixin.py:188} INFO - Revenda Plus Solutions organizada com sucesso !
[2025-06-24T04:32:24.921+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88350-564/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:24.921+0000] {logging_mixin.py:188} INFO - Revenda Ponte organizada com sucesso !
[2025-06-24T04:32:26.072+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29700-550/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82f340>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:26.073+0000] {logging_mixin.py:188} INFO - Revenda Pratic Informática organizada com sucesso !
[2025-06-24T04:32:27.225+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/65930-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:27.226+0000] {logging_mixin.py:188} INFO - Revenda PROFISC - Consultoria  organizada com sucesso !
[2025-06-24T04:32:28.377+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws//json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:28.378+0000] {logging_mixin.py:188} INFO - Revenda Pryamos organizada com sucesso !
[2025-06-24T04:32:29.529+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46380-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:29.530+0000] {logging_mixin.py:188} INFO - Revenda Quality Automação e Recargas organizada com sucesso !
[2025-06-24T04:32:30.681+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/76963-586/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:30.682+0000] {logging_mixin.py:188} INFO - Revenda Rafah Soluções em Sistema organizada com sucesso !
[2025-06-24T04:32:30.810+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89803-460/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:30.811+0000] {logging_mixin.py:188} INFO - Revenda RC Automação organizada com sucesso !
[2025-06-24T04:32:31.961+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/05761-340/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:31.962+0000] {logging_mixin.py:188} INFO - Revenda RCM Tecnologia organizada com sucesso !
[2025-06-24T04:32:33.113+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/15910-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:33.114+0000] {logging_mixin.py:188} INFO - Revenda RedeEllo organizada com sucesso !
[2025-06-24T04:32:34.266+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/56310-130/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862d30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:34.266+0000] {logging_mixin.py:188} INFO - Revenda Rieger Consultoria e Serviços  organizada com sucesso !
[2025-06-24T04:32:35.417+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88104-435/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:35.418+0000] {logging_mixin.py:188} INFO - Revenda RKS Tecnologia organizada com sucesso !
[2025-06-24T04:32:36.569+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/76960-046/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b5b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:36.570+0000] {logging_mixin.py:188} INFO - Revenda Rondoniatec Sistemas e Soluções organizada com sucesso !
[2025-06-24T04:32:36.698+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/48602-005/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2c10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:36.698+0000] {logging_mixin.py:188} INFO - Revenda Royal Ti organizada com sucesso !
[2025-06-24T04:32:37.849+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/28895-320/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c28e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:37.850+0000] {logging_mixin.py:188} INFO - Revenda RPD Tech Soluções em T.I. organizada com sucesso !
[2025-06-24T04:32:39.002+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/87970-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d829ee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:39.003+0000] {logging_mixin.py:188} INFO - Revenda RPDV Soluções em Tecnologia organizada com sucesso !
[2025-06-24T04:32:40.153+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55825-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:40.154+0000] {logging_mixin.py:188} INFO - Revenda RS Informatica organizada com sucesso !
[2025-06-24T04:32:41.305+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/31270-350/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:41.306+0000] {logging_mixin.py:188} INFO - Revenda Rtek organizada com sucesso !
[2025-06-24T04:32:42.457+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89204-050/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:42.458+0000] {logging_mixin.py:188} INFO - Revenda SDN Sistemas de Gestão organizada com sucesso !
[2025-06-24T04:32:43.608+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/12914-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834d00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:43.609+0000] {logging_mixin.py:188} INFO - Revenda Seed Tecnologia organizada com sucesso !
[2025-06-24T04:32:43.738+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29560-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:43.739+0000] {logging_mixin.py:188} INFO - Revenda Shopseg Sistemas organizada com sucesso !
[2025-06-24T04:32:44.892+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88350-100/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83a340>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:44.893+0000] {logging_mixin.py:188} INFO - Revenda Sig Sistemas Corporativos organizada com sucesso !
[2025-06-24T04:32:46.041+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/63034-150/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:46.042+0000] {logging_mixin.py:188} INFO - Revenda Sistech Sistemas organizada com sucesso !
[2025-06-24T04:32:47.193+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88350-270/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:47.194+0000] {logging_mixin.py:188} INFO - Revenda Sistema Completo organizada com sucesso !
[2025-06-24T04:32:48.345+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/45028-190/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:48.346+0000] {logging_mixin.py:188} INFO - Revenda Sistema Uniplus - Vitória da Conquista organizada com sucesso !
[2025-06-24T04:32:49.497+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/39680-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b5b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:49.498+0000] {logging_mixin.py:188} INFO - Revenda Skill Automação Comercial organizada com sucesso !
[2025-06-24T04:32:50.649+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88130-650/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2be0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:50.650+0000] {logging_mixin.py:188} INFO - Revenda SM10 Sistemas de Gestão e Automação Comercial  (AM10) organizada com sucesso !
[2025-06-24T04:32:50.778+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/79540-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:50.778+0000] {logging_mixin.py:188} INFO - Revenda Smith Tecnologias organizada com sucesso !
[2025-06-24T04:32:51.929+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50720-090/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83abe0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:51.930+0000] {logging_mixin.py:188} INFO - Revenda SMQ Tecnologia organizada com sucesso !
[2025-06-24T04:32:53.081+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/44061-070/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:53.082+0000] {logging_mixin.py:188} INFO - Revenda Softech Tecnologia organizada com sucesso !
[2025-06-24T04:32:54.233+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/62011-205/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b7f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:54.234+0000] {logging_mixin.py:188} INFO - Revenda SoftGadol organizada com sucesso !
[2025-06-24T04:32:55.385+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/60822-305/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8340d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:55.386+0000] {logging_mixin.py:188} INFO - Revenda Softkore organizada com sucesso !
[2025-06-24T04:32:56.537+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/27920-325/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:56.538+0000] {logging_mixin.py:188} INFO - Revenda Softmaq organizada com sucesso !
[2025-06-24T04:32:57.689+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/61655-590/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8627f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:57.690+0000] {logging_mixin.py:188} INFO - Revenda Solem Tecnologia organizada com sucesso !
[2025-06-24T04:32:57.817+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95700-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83a460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:57.818+0000] {logging_mixin.py:188} INFO - Revenda Sonaglio Automação organizada com sucesso !
[2025-06-24T04:32:58.969+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50720-715/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8628e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:32:58.970+0000] {logging_mixin.py:188} INFO - Revenda Sonsun organizada com sucesso !
[2025-06-24T04:33:00.120+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50721-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:00.120+0000] {logging_mixin.py:188} INFO - Revenda Sophos Projetos organizada com sucesso !
[2025-06-24T04:33:01.274+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/99260-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83a6d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:01.274+0000] {logging_mixin.py:188} INFO - Revenda Sparta Gestão e Contabilidade - DEOCLESYSTEM organizada com sucesso !
[2025-06-24T04:33:02.425+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37470-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83a3a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:02.425+0000] {logging_mixin.py:188} INFO - Revenda Speed Automação Comercial organizada com sucesso !
[2025-06-24T04:33:03.578+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46400-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2af0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:03.578+0000] {logging_mixin.py:188} INFO - Revenda SS Informatica - Bahia organizada com sucesso !
[2025-06-24T04:33:03.708+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/65070-280/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d829fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:03.709+0000] {logging_mixin.py:188} INFO - Revenda SS Informática - Maranhão organizada com sucesso !
[2025-06-24T04:33:04.857+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59607-340/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d829970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:04.858+0000] {logging_mixin.py:188} INFO - Revenda Syscom Sistemas organizada com sucesso !
[2025-06-24T04:33:06.009+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/45075-290/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2ee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:06.009+0000] {logging_mixin.py:188} INFO - Revenda SYSFOUR - Intelligent Systems organizada com sucesso !
[2025-06-24T04:33:07.161+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89295-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b7730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:07.161+0000] {logging_mixin.py:188} INFO - Revenda System Bella Automação Comercial organizada com sucesso !
[2025-06-24T04:33:08.312+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89801-570/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8623d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:08.313+0000] {logging_mixin.py:188} INFO - Revenda TB Automação e Informática organizada com sucesso !
[2025-06-24T04:33:09.465+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59031-170/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d829880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:09.466+0000] {logging_mixin.py:188} INFO - Revenda TC Maquinas organizada com sucesso !
[2025-06-24T04:33:10.618+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/60750-030/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83a640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:10.619+0000] {logging_mixin.py:188} INFO - Revenda Technoside Informatica organizada com sucesso !
[2025-06-24T04:33:10.749+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/65800-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83a760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:10.749+0000] {logging_mixin.py:188} INFO - Revenda Tecmicro Informática organizada com sucesso !
[2025-06-24T04:33:11.895+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/79004-460/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83a4f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:11.896+0000] {logging_mixin.py:188} INFO - Revenda Tecnoinfo organizada com sucesso !
[2025-06-24T04:33:13.049+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/68525-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8623a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:13.050+0000] {logging_mixin.py:188} INFO - Revenda TECSOLUTION organizada com sucesso !
[2025-06-24T04:33:14.202+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29050-565/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8623d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:14.202+0000] {logging_mixin.py:188} INFO - Revenda Tefcom organizada com sucesso !
[2025-06-24T04:33:15.353+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/68909-845/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b7e80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:15.354+0000] {logging_mixin.py:188} INFO - Revenda TFA Tecnologia e Soluções  organizada com sucesso !
[2025-06-24T04:33:16.504+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95020-520/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:16.505+0000] {logging_mixin.py:188} INFO - Revenda TI-Brasil Sistemas organizada com sucesso !
[2025-06-24T04:33:17.655+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95084-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8341c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:17.656+0000] {logging_mixin.py:188} INFO - Revenda Trends Solutions organizada com sucesso !
[2025-06-24T04:33:17.785+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/67013-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:17.786+0000] {logging_mixin.py:188} INFO - Revenda TS TECH organizada com sucesso !
[2025-06-24T04:33:18.939+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89560-132/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2610>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:18.940+0000] {logging_mixin.py:188} INFO - Revenda Unisoft Sistemas ** Hardtech organizada com sucesso !
[2025-06-24T04:33:20.089+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88070-770/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b72b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:20.090+0000] {logging_mixin.py:188} INFO - Revenda Unitek Soluções organizada com sucesso !
[2025-06-24T04:33:21.242+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/20040-030/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862d30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:21.243+0000] {logging_mixin.py:188} INFO - Revenda Uniup Sistema - Automação e CFTV organizada com sucesso !
[2025-06-24T04:33:22.393+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89222-363/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:22.394+0000] {logging_mixin.py:188} INFO - Revenda Universal Automação Comercial  organizada com sucesso !
[2025-06-24T04:33:23.543+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78550-104/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82f1c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:23.545+0000] {logging_mixin.py:188} INFO - Revenda Universo Sistemas organizada com sucesso !
[2025-06-24T04:33:23.675+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89620-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82fa60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:23.676+0000] {logging_mixin.py:188} INFO - Revenda Valor Tecnologia organizada com sucesso !
[2025-06-24T04:33:24.827+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/98700-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d834c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:24.828+0000] {logging_mixin.py:188} INFO - Revenda VGI TECHNOLOGY organizada com sucesso !
[2025-06-24T04:33:25.977+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/87504-480/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:25.978+0000] {logging_mixin.py:188} INFO - Revenda Via Nova Soluções em Tecnologia organizada com sucesso !
[2025-06-24T04:33:27.129+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37890-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84bfd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:27.130+0000] {logging_mixin.py:188} INFO - Revenda Virtual Informatica_MG organizada com sucesso !
[2025-06-24T04:33:28.281+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89136-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:28.282+0000] {logging_mixin.py:188} INFO - Revenda Virtual Sistemas_SC organizada com sucesso !
[2025-06-24T04:33:29.433+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/26260-580/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:29.434+0000] {logging_mixin.py:188} INFO - Revenda VPN Solucoes em Informatica organizada com sucesso !
[2025-06-24T04:33:30.585+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89245-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82f4c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:30.586+0000] {logging_mixin.py:188} INFO - Revenda Vzan Automação Comercial organizada com sucesso !
[2025-06-24T04:33:30.717+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21532-460/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82e370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:30.718+0000] {logging_mixin.py:188} INFO - Revenda Walltech Informatica organizada com sucesso !
[2025-06-24T04:33:31.866+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29103-240/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:31.866+0000] {logging_mixin.py:188} INFO - Revenda W C Sistemas organizada com sucesso !
[2025-06-24T04:33:33.017+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/06280-150/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b72b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:33.017+0000] {logging_mixin.py:188} INFO - Revenda WGE informatica organizada com sucesso !
[2025-06-24T04:33:34.176+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/31080-365/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:34.177+0000] {logging_mixin.py:188} INFO - Revenda WMX Soluções em Tecnologia organizada com sucesso !
[2025-06-24T04:33:35.321+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/30710-580/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82f8e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-24T04:33:35.322+0000] {logging_mixin.py:188} INFO - Revenda X1 Automação organizada com sucesso !
[2025-06-24T04:33:35.422+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-24T04:33:35.441+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=DAG_atualizacao_cadastral_revendas, task_id=organized_response_database, execution_date=20250623T043000, start_date=20250624T043005, end_date=20250624T043335
[2025-06-24T04:33:35.541+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-24T04:33:35.576+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
