[2025-06-29T04:30:05.645+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_atualizacao_cadastral_revendas.organized_response_database scheduled__2025-06-28T04:30:00+00:00 [queued]>
[2025-06-29T04:30:05.662+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_atualizacao_cadastral_revendas.organized_response_database scheduled__2025-06-28T04:30:00+00:00 [queued]>
[2025-06-29T04:30:05.663+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-29T04:30:05.774+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): organized_response_database> on 2025-06-28 04:30:00+00:00
[2025-06-29T04:30:05.782+0000] {standard_task_runner.py:60} INFO - Started process 435551 to run task
[2025-06-29T04:30:05.788+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'DAG_atualizacao_cadastral_revendas', 'organized_response_database', 'scheduled__2025-06-28T04:30:00+00:00', '--job-id', '291', '--raw', '--subdir', 'DAGS_FOLDER/DagDatasetComercial.py', '--cfg-path', '/tmp/tmp6z_2hmyv']
[2025-06-29T04:30:05.790+0000] {standard_task_runner.py:88} INFO - Job 291: Subtask organized_response_database
[2025-06-29T04:30:05.998+0000] {task_command.py:423} INFO - Running <TaskInstance: DAG_atualizacao_cadastral_revendas.organized_response_database scheduled__2025-06-28T04:30:00+00:00 [running]> on host 99f5714845f7
[2025-06-29T04:30:06.292+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_atualizacao_cadastral_revendas' AIRFLOW_CTX_TASK_ID='organized_response_database' AIRFLOW_CTX_EXECUTION_DATE='2025-06-28T04:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-28T04:30:00+00:00'
[2025-06-29T04:30:06.470+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/75620-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8635e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:06.471+0000] {logging_mixin.py:188} INFO - Revenda A7 Soluções organizada com sucesso !
[2025-06-29T04:30:06.601+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/80540-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863e80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:06.602+0000] {logging_mixin.py:188} INFO - Revenda AB Soluções em TI organizada com sucesso !
[2025-06-29T04:30:06.732+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21070-032/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82e760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:06.733+0000] {logging_mixin.py:188} INFO - Revenda Adonai Automação Comercial organizada com sucesso !
[2025-06-29T04:30:06.862+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/39801-240/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83c040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:06.863+0000] {logging_mixin.py:188} INFO - Revenda ADV SIG organizada com sucesso !
[2025-06-29T04:30:06.994+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88400-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82eee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:06.995+0000] {logging_mixin.py:188} INFO - Revenda A e A Dist. de Informática - Softart organizada com sucesso !
[2025-06-29T04:30:07.125+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21235-604/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82e5e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:07.126+0000] {logging_mixin.py:188} INFO - Revenda Af Suporte organizada com sucesso !
[2025-06-29T04:30:08.283+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/60115-222/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:08.284+0000] {logging_mixin.py:188} INFO - Revenda Agedata Sistemas organizada com sucesso !
[2025-06-29T04:30:09.435+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78130-435/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8638e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:09.436+0000] {logging_mixin.py:188} INFO - Revenda AIO Solucoes organizada com sucesso !
[2025-06-29T04:30:09.570+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37701-706/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83c8e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:09.571+0000] {logging_mixin.py:188} INFO - Revenda AllTecInfo organizada com sucesso !
[2025-06-29T04:30:10.716+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78460-606/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c41c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:10.717+0000] {logging_mixin.py:188} INFO - Revenda Alpha Systemas e informática organizada com sucesso !
[2025-06-29T04:30:11.868+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85857-270/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:11.868+0000] {logging_mixin.py:188} INFO - Revenda Alternativa Automação Comercial organizada com sucesso !
[2025-06-29T04:30:13.021+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78575-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:13.021+0000] {logging_mixin.py:188} INFO - Revenda Amigo do Micro organizada com sucesso !
[2025-06-29T04:30:14.172+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85856-530/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83cfd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:14.173+0000] {logging_mixin.py:188} INFO - Revenda AND Consultores Associados organizada com sucesso !
[2025-06-29T04:30:15.324+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/82600-130/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83c3d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:15.325+0000] {logging_mixin.py:188} INFO - Revenda APRN Soluções organizada com sucesso !
[2025-06-29T04:30:16.480+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55540-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c48e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:16.481+0000] {logging_mixin.py:188} INFO - Revenda Ary Sistemas de Gestão e Informatica (RNS) organizada com sucesso !
[2025-06-29T04:30:16.628+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/66113-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c81c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:16.629+0000] {logging_mixin.py:188} INFO - Revenda Asteqesystem organizada com sucesso !
[2025-06-29T04:30:17.820+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/76908-430/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:17.821+0000] {logging_mixin.py:188} INFO - Revenda Atrium Sistemas organizada com sucesso !
[2025-06-29T04:30:18.972+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/27265-435/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:18.973+0000] {logging_mixin.py:188} INFO - Revenda Automac Digitron organizada com sucesso !
[2025-06-29T04:30:20.125+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29900-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:20.126+0000] {logging_mixin.py:188} INFO - Revenda Automaquinas - Automação Comercial organizada com sucesso !
[2025-06-29T04:30:21.274+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/44003-198/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:21.275+0000] {logging_mixin.py:188} INFO - Revenda Autosyste Tecnologia e Inovação organizada com sucesso !
[2025-06-29T04:30:22.427+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/25515-520/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:22.428+0000] {logging_mixin.py:188} INFO - Revenda Autotech Informática organizada com sucesso !
[2025-06-29T04:30:22.559+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/22710-112/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83c310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:22.560+0000] {logging_mixin.py:188} INFO - Revenda Bellabyte organizada com sucesso !
[2025-06-29T04:30:23.709+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/68900-075/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83ccd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:23.710+0000] {logging_mixin.py:188} INFO - Revenda Bitech organizada com sucesso !
[2025-06-29T04:30:24.860+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29645-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8639a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:24.860+0000] {logging_mixin.py:188} INFO - Revenda Boldtsoft Sistemas organizada com sucesso !
[2025-06-29T04:30:26.012+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/66623-268/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:26.012+0000] {logging_mixin.py:188} INFO - Revenda BRAZ TI organizada com sucesso !
[2025-06-29T04:30:27.163+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88352-001/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83c6a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:27.164+0000] {logging_mixin.py:188} INFO - Revenda Brusoft Informatica organizada com sucesso !
[2025-06-29T04:30:28.322+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88312-260/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4610>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:28.323+0000] {logging_mixin.py:188} INFO - Revenda Brvatech organizada com sucesso !
[2025-06-29T04:30:29.468+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/70714-020/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:29.469+0000] {logging_mixin.py:188} INFO - Revenda Canal Tecnico (Lumi) organizada com sucesso !
[2025-06-29T04:30:29.601+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/57020-260/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c91c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:29.602+0000] {logging_mixin.py:188} INFO - Revenda Casa das Impressoras organizada com sucesso !
[2025-06-29T04:30:30.749+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85852-130/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c9a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:30.750+0000] {logging_mixin.py:188} INFO - Revenda CASTERS organizada com sucesso !
[2025-06-29T04:30:31.901+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55016-080/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:31.902+0000] {logging_mixin.py:188} INFO - Revenda Centec Equipamentos organizada com sucesso !
[2025-06-29T04:30:33.052+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/57442-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b8df0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:33.053+0000] {logging_mixin.py:188} INFO - Revenda CK Tech Consultoria organizada com sucesso !
[2025-06-29T04:30:34.204+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85065-420/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863a30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:34.205+0000] {logging_mixin.py:188} INFO - Revenda Compass Tecnologia da Informação organizada com sucesso !
[2025-06-29T04:30:35.356+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/38400-694/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c9640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:35.356+0000] {logging_mixin.py:188} INFO - Revenda Compucenter Software organizada com sucesso !
[2025-06-29T04:30:35.489+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/28735-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c81c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:35.490+0000] {logging_mixin.py:188} INFO - Revenda Conexão Informática Ltda organizada com sucesso !
[2025-06-29T04:30:36.636+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/57120-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:36.637+0000] {logging_mixin.py:188} INFO - Revenda Connect System Soluções em Tecnologia organizada com sucesso !
[2025-06-29T04:30:37.788+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/69047-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c9be0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:37.789+0000] {logging_mixin.py:188} INFO - Revenda Conte Certo Serviços organizada com sucesso !
[2025-06-29T04:30:38.939+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/15085-310/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:38.940+0000] {logging_mixin.py:188} INFO - Revenda Control Biz organizada com sucesso !
[2025-06-29T04:30:40.090+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55004-270/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:40.091+0000] {logging_mixin.py:188} INFO - Revenda CTi - Centro Técnico de Informática organizada com sucesso !
[2025-06-29T04:30:41.244+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21380-008/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c47f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:41.244+0000] {logging_mixin.py:188} INFO - Revenda D&A Automação Comercial organizada com sucesso !
[2025-06-29T04:30:42.398+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89228-080/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:42.399+0000] {logging_mixin.py:188} INFO - Revenda DALTEC Automacao Comercial organizada com sucesso !
[2025-06-29T04:30:42.531+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/38740-082/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:42.531+0000] {logging_mixin.py:188} INFO - Revenda DataConta Gestão de Negócios organizada com sucesso !
[2025-06-29T04:30:43.675+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89801-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c49a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:43.676+0000] {logging_mixin.py:188} INFO - Revenda Dataproxy organizada com sucesso !
[2025-06-29T04:30:44.828+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/91220-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:44.828+0000] {logging_mixin.py:188} INFO - Revenda DCODER organizada com sucesso !
[2025-06-29T04:30:45.980+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/77405-130/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c0a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:45.981+0000] {logging_mixin.py:188} INFO - Revenda D Data Soluções organizada com sucesso !
[2025-06-29T04:30:47.140+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/53421-321/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:47.141+0000] {logging_mixin.py:188} INFO - Revenda DGTEC organizada com sucesso !
[2025-06-29T04:30:48.283+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46400-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:48.284+0000] {logging_mixin.py:188} INFO - Revenda Digito Informatica organizada com sucesso !
[2025-06-29T04:30:49.436+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85060-080/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8eb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:49.437+0000] {logging_mixin.py:188} INFO - Revenda Dikoc Soluções em Software organizada com sucesso !
[2025-06-29T04:30:49.571+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/81200-150/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:49.571+0000] {logging_mixin.py:188} INFO - Revenda DMK Sistemas e Soluções - HSI organizada com sucesso !
[2025-06-29T04:30:50.716+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78635-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c9c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:50.717+0000] {logging_mixin.py:188} INFO - Revenda DMZ Informatica organizada com sucesso !
[2025-06-29T04:30:51.866+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/13843-201/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:51.867+0000] {logging_mixin.py:188} INFO - Revenda Dolphin Consultoria organizada com sucesso !
[2025-06-29T04:30:53.020+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/28913-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:53.021+0000] {logging_mixin.py:188} INFO - Revenda DSM Consultoria em T.I. organizada com sucesso !
[2025-06-29T04:30:54.172+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/79004-440/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:54.173+0000] {logging_mixin.py:188} INFO - Revenda Duall Tech organizada com sucesso !
[2025-06-29T04:30:55.324+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/41820-020/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:55.324+0000] {logging_mixin.py:188} INFO - Revenda DWH Comercio de Alimentos organizada com sucesso !
[2025-06-29T04:30:56.476+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88702-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cca90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:56.476+0000] {logging_mixin.py:188} INFO - Revenda Edcom Automação Comercial organizada com sucesso !
[2025-06-29T04:30:56.609+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/75901-630/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c49d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:56.610+0000] {logging_mixin.py:188} INFO - Revenda Eleve Tecnologia organizada com sucesso !
[2025-06-29T04:30:57.755+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88106-500/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:57.756+0000] {logging_mixin.py:188} INFO - Revenda Emlink Solucoes Empresariais organizada com sucesso !
[2025-06-29T04:30:58.906+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/64200-250/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:30:58.907+0000] {logging_mixin.py:188} INFO - Revenda Exatop Certificação Digital e Sistemas organizada com sucesso !
[2025-06-29T04:31:00.060+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89258-730/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:00.061+0000] {logging_mixin.py:188} INFO - Revenda Exodus Informática organizada com sucesso !
[2025-06-29T04:31:01.212+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89280-328/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cca90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:01.213+0000] {logging_mixin.py:188} INFO - Revenda Extrema Software de Gestão organizada com sucesso !
[2025-06-29T04:31:02.364+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/63660-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:02.365+0000] {logging_mixin.py:188} INFO - Revenda F5 Suporte e Automacão Comercial organizada com sucesso !
[2025-06-29T04:31:02.496+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/13273-410/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:02.498+0000] {logging_mixin.py:188} INFO - Revenda Facilita Sistemas organizada com sucesso !
[2025-06-29T04:31:03.644+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95670-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:03.645+0000] {logging_mixin.py:188} INFO - Revenda Facilsys organizada com sucesso !
[2025-06-29T04:31:04.794+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58808-485/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b8fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:04.795+0000] {logging_mixin.py:188} INFO - Revenda F & F Soluções Empresariais organizada com sucesso !
[2025-06-29T04:31:05.948+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88160-064/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:05.949+0000] {logging_mixin.py:188} INFO - Revenda FKSIS - Sistemas de Gestão organizada com sucesso !
[2025-06-29T04:31:07.100+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88354-610/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4ee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:07.101+0000] {logging_mixin.py:188} INFO - Revenda FlorySoftt organizada com sucesso !
[2025-06-29T04:31:08.252+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/23860-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:08.253+0000] {logging_mixin.py:188} INFO - Revenda Fn Info House organizada com sucesso !
[2025-06-29T04:31:09.403+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/63502-769/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c80a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:09.404+0000] {logging_mixin.py:188} INFO - Revenda FS Informatica organizada com sucesso !
[2025-06-29T04:31:09.538+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/84320-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:09.539+0000] {logging_mixin.py:188} INFO - Revenda Fusion Sistemas e Informatica organizada com sucesso !
[2025-06-29T04:31:10.684+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59900-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c41c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:10.684+0000] {logging_mixin.py:188} INFO - Revenda Gilmaq Automação Comercial organizada com sucesso !
[2025-06-29T04:31:11.836+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55825-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc7f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:11.837+0000] {logging_mixin.py:188} INFO - Revenda GM Soluções em Informática organizada com sucesso !
[2025-06-29T04:31:12.987+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/01311-927/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:12.988+0000] {logging_mixin.py:188} INFO - Revenda Grupo GUUW organizada com sucesso !
[2025-06-29T04:31:14.140+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37800-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:14.140+0000] {logging_mixin.py:188} INFO - Revenda Guaxutec organizada com sucesso !
[2025-06-29T04:31:15.292+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88508-190/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863910>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:15.293+0000] {logging_mixin.py:188} INFO - Revenda HSI Automação Comercial organizada com sucesso !
[2025-06-29T04:31:16.444+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/20756-100/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:16.445+0000] {logging_mixin.py:188} INFO - Revenda HWC Soluções organizada com sucesso !
[2025-06-29T04:31:16.579+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59500-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:16.579+0000] {logging_mixin.py:188} INFO - Revenda I7 Automação Comercial organizada com sucesso !
[2025-06-29T04:31:17.724+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29280-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:17.725+0000] {logging_mixin.py:188} INFO - Revenda Ideal Soluções Empresariais organizada com sucesso !
[2025-06-29T04:31:18.875+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59570-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc2b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:18.876+0000] {logging_mixin.py:188} INFO - Revenda ID Tecnologia organizada com sucesso !
[2025-06-29T04:31:20.027+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/06454-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:20.028+0000] {logging_mixin.py:188} INFO - Revenda IFFI Soluções organizada com sucesso !
[2025-06-29T04:31:21.180+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/69980-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:21.181+0000] {logging_mixin.py:188} INFO - Revenda IG TEC organizada com sucesso !
[2025-06-29T04:31:22.332+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58900-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8c10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:22.334+0000] {logging_mixin.py:188} INFO - Revenda INFOPRINTER organizada com sucesso !
[2025-06-29T04:31:22.478+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21011-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:22.478+0000] {logging_mixin.py:188} INFO - Revenda INFORMIT organizada com sucesso !
[2025-06-29T04:31:23.675+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/69303-045/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7ccc10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:23.676+0000] {logging_mixin.py:188} INFO - Revenda Infor Serviços organizada com sucesso !
[2025-06-29T04:31:24.831+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/48601-270/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:24.832+0000] {logging_mixin.py:188} INFO - Revenda Infortec Automacao Comercial organizada com sucesso !
[2025-06-29T04:31:25.980+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46430-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:25.980+0000] {logging_mixin.py:188} INFO - Revenda Infotek organizada com sucesso !
[2025-06-29T04:31:27.131+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/26535-190/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8634f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:27.132+0000] {logging_mixin.py:188} INFO - Revenda Innovati Tecnologia (INW Store) organizada com sucesso !
[2025-06-29T04:31:28.284+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50865-090/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8a00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:28.285+0000] {logging_mixin.py:188} INFO - Revenda Inova Software organizada com sucesso !
[2025-06-29T04:31:29.435+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55130-970/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c84f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:29.435+0000] {logging_mixin.py:188} INFO - Revenda Inspire Consult & Informatica  organizada com sucesso !
[2025-06-29T04:31:29.567+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89801-106/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8636a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:29.571+0000] {logging_mixin.py:188} INFO - Revenda Inteltix Tecnologia (Center) organizada com sucesso !
[2025-06-29T04:31:30.716+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/79823-290/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c1f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:30.717+0000] {logging_mixin.py:188} INFO - Revenda J7 Automação Comercial - System HD organizada com sucesso !
[2025-06-29T04:31:31.868+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78360-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:31.868+0000] {logging_mixin.py:188} INFO - Revenda Jann Informatica organizada com sucesso !
[2025-06-29T04:31:33.020+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/76997-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7ccb20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:33.021+0000] {logging_mixin.py:188} INFO - Revenda JB Tecnologia organizada com sucesso !
[2025-06-29T04:31:34.172+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/68460-245/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c41f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:34.172+0000] {logging_mixin.py:188} INFO - Revenda J & E Soluções organizada com sucesso !
[2025-06-29T04:31:35.324+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46430-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d74f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:35.325+0000] {logging_mixin.py:188} INFO - Revenda JExpress organizada com sucesso !
[2025-06-29T04:31:36.476+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58077-062/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc9d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:36.477+0000] {logging_mixin.py:188} INFO - Revenda J F Soluções Informatica organizada com sucesso !
[2025-06-29T04:31:36.610+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/69058-580/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cca30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:36.611+0000] {logging_mixin.py:188} INFO - Revenda J F Tech Tecnologia & Sistemas organizada com sucesso !
[2025-06-29T04:31:37.755+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/31255-780/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7013da4070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:37.756+0000] {logging_mixin.py:188} INFO - Revenda JHLS Automação Comercial organizada com sucesso !
[2025-06-29T04:31:38.908+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/12914-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:38.909+0000] {logging_mixin.py:188} INFO - Revenda Jinsei Contabilidade organizada com sucesso !
[2025-06-29T04:31:40.058+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/27197-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8af0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:40.059+0000] {logging_mixin.py:188} INFO - Revenda JJ Serviços organizada com sucesso !
[2025-06-29T04:31:41.211+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/49055-620/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:41.212+0000] {logging_mixin.py:188} INFO - Revenda JM Informatica organizada com sucesso !
[2025-06-29T04:31:42.364+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89220-110/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:42.365+0000] {logging_mixin.py:188} INFO - Revenda JP Automação Comercial organizada com sucesso !
[2025-06-29T04:31:42.497+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78250-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84cd60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:42.498+0000] {logging_mixin.py:188} INFO - Revenda JSR Automação Comercial  organizada com sucesso !
[2025-06-29T04:31:43.644+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89700-166/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c89a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:43.644+0000] {logging_mixin.py:188} INFO - Revenda Kernel Sistemas organizada com sucesso !
[2025-06-29T04:31:44.794+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/14010-180/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:44.795+0000] {logging_mixin.py:188} INFO - Revenda KMCI Tecnologia em Automação organizada com sucesso !
[2025-06-29T04:31:45.951+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/25555-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:45.952+0000] {logging_mixin.py:188} INFO - Revenda Komputronic do Brasil organizada com sucesso !
[2025-06-29T04:31:47.098+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29052-170/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:47.099+0000] {logging_mixin.py:188} INFO - Revenda KSC Sistemas organizada com sucesso !
[2025-06-29T04:31:48.251+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50010-100/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:48.252+0000] {logging_mixin.py:188} INFO - Revenda L&D Comercio e Tecnologia organizada com sucesso !
[2025-06-29T04:31:49.404+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/25935-530/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:49.405+0000] {logging_mixin.py:188} INFO - Revenda LD Tech organizada com sucesso !
[2025-06-29T04:31:49.537+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29375-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c0a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:49.538+0000] {logging_mixin.py:188} INFO - Revenda LF Sistemas organizada com sucesso !
[2025-06-29T04:31:50.683+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/39400-215/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:50.684+0000] {logging_mixin.py:188} INFO - Revenda LiderTech organizada com sucesso !
[2025-06-29T04:31:51.835+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/93700-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d75b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:51.836+0000] {logging_mixin.py:188} INFO - Revenda Life Sistemas  organizada com sucesso !
[2025-06-29T04:31:52.988+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/20250-450/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83d1f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:52.989+0000] {logging_mixin.py:188} INFO - Revenda LL Tecnologia organizada com sucesso !
[2025-06-29T04:31:54.140+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/36884-004/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83da90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:54.141+0000] {logging_mixin.py:188} INFO - Revenda LMD Sistemas organizada com sucesso !
[2025-06-29T04:31:55.292+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/22730-001/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863b80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:55.292+0000] {logging_mixin.py:188} INFO - Revenda Logitec 2000 Informatica organizada com sucesso !
[2025-06-29T04:31:56.444+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37470-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8a9c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:56.445+0000] {logging_mixin.py:188} INFO - Revenda Macmos organizada com sucesso !
[2025-06-29T04:31:56.578+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59300-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:56.579+0000] {logging_mixin.py:188} INFO - Revenda Mape Informatica organizada com sucesso !
[2025-06-29T04:31:57.723+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89900-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:57.724+0000] {logging_mixin.py:188} INFO - Revenda Marcka Informática e Sistemas organizada com sucesso !
[2025-06-29T04:31:58.874+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58041-070/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83d790>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:31:58.874+0000] {logging_mixin.py:188} INFO - Revenda Matechinfo organizada com sucesso !
[2025-06-29T04:32:00.027+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88355-393/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:00.028+0000] {logging_mixin.py:188} INFO - Revenda MB Tecnologia organizada com sucesso !
[2025-06-29T04:32:01.180+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/82015-520/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:01.181+0000] {logging_mixin.py:188} INFO - Revenda MC2 Tecnologia organizada com sucesso !
[2025-06-29T04:32:02.331+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89562-180/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:02.332+0000] {logging_mixin.py:188} INFO - Revenda MCR Sistemas (RS-AMX) organizada com sucesso !
[2025-06-29T04:32:03.483+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21660-060/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b86d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:03.484+0000] {logging_mixin.py:188} INFO - Revenda MD Tech Automação organizada com sucesso !
[2025-06-29T04:32:03.617+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46430-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83d310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:03.618+0000] {logging_mixin.py:188} INFO - Revenda Megasoft Informatica organizada com sucesso !
[2025-06-29T04:32:04.763+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95270-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83deb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:04.764+0000] {logging_mixin.py:188} INFO - Revenda Mercantec Soluções organizada com sucesso !
[2025-06-29T04:32:05.921+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88310-661/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:05.922+0000] {logging_mixin.py:188} INFO - Revenda Mikrox "Somadatta" organizada com sucesso !
[2025-06-29T04:32:07.069+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/63010-127/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7a00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:07.069+0000] {logging_mixin.py:188} INFO - Revenda M. Nobre (Terabyte) organizada com sucesso !
[2025-06-29T04:32:08.220+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/32310-210/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:08.221+0000] {logging_mixin.py:188} INFO - Revenda MRsis Automação organizada com sucesso !
[2025-06-29T04:32:09.371+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37062-170/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:09.372+0000] {logging_mixin.py:188} INFO - Revenda M&R Soluções - Grupo ATL organizada com sucesso !
[2025-06-29T04:32:09.504+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/47640-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:09.505+0000] {logging_mixin.py:188} INFO - Revenda Multi Soft organizada com sucesso !
[2025-06-29T04:32:10.653+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78390-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c45b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:10.654+0000] {logging_mixin.py:188} INFO - Revenda NewCompras.com.br organizada com sucesso !
[2025-06-29T04:32:11.803+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/67030-080/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7ee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:11.804+0000] {logging_mixin.py:188} INFO - Revenda NEWTEF Automação organizada com sucesso !
[2025-06-29T04:32:12.956+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50960-400/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83d220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:12.957+0000] {logging_mixin.py:188} INFO - Revenda Next Store organizada com sucesso !
[2025-06-29T04:32:14.108+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37730-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83dac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:14.108+0000] {logging_mixin.py:188} INFO - Revenda Nova Loja organizada com sucesso !
[2025-06-29T04:32:15.260+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/17210-420/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:15.261+0000] {logging_mixin.py:188} INFO - Revenda NovaPC organizada com sucesso !
[2025-06-29T04:32:16.411+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/39400-163/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b87c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:16.412+0000] {logging_mixin.py:188} INFO - Revenda Optimus - Gestão organizada com sucesso !
[2025-06-29T04:32:16.544+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/98803-412/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:16.545+0000] {logging_mixin.py:188} INFO - Revenda Otimizer Consultoria em Sistemas organizada com sucesso !
[2025-06-29T04:32:17.692+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/62500-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d72e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:17.693+0000] {logging_mixin.py:188} INFO - Revenda Otimize Soluções organizada com sucesso !
[2025-06-29T04:32:18.844+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95034-160/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:18.845+0000] {logging_mixin.py:188} INFO - Revenda P21 Software organizada com sucesso !
[2025-06-29T04:32:19.995+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50980-480/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83d190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:19.996+0000] {logging_mixin.py:188} INFO - Revenda PALM Soluções organizada com sucesso !
[2025-06-29T04:32:21.147+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/84040-010/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:21.147+0000] {logging_mixin.py:188} INFO - Revenda Parceria Informatica organizada com sucesso !
[2025-06-29T04:32:22.300+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88330-725/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d70d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:22.301+0000] {logging_mixin.py:188} INFO - Revenda PDV Automação organizada com sucesso !
[2025-06-29T04:32:23.451+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/38700-001/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:23.452+0000] {logging_mixin.py:188} INFO - Revenda PEG Informatica organizada com sucesso !
[2025-06-29T04:32:23.584+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95200-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:23.585+0000] {logging_mixin.py:188} INFO - Revenda Piramide Automação e Informatica organizada com sucesso !
[2025-06-29T04:32:24.732+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/70314-900/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4d00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:24.733+0000] {logging_mixin.py:188} INFO - Revenda Plus Solutions organizada com sucesso !
[2025-06-29T04:32:25.883+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88350-564/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:25.884+0000] {logging_mixin.py:188} INFO - Revenda Ponte organizada com sucesso !
[2025-06-29T04:32:27.040+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29700-550/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8203a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:27.041+0000] {logging_mixin.py:188} INFO - Revenda Pratic Informática organizada com sucesso !
[2025-06-29T04:32:28.188+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/65930-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:28.189+0000] {logging_mixin.py:188} INFO - Revenda PROFISC - Consultoria  organizada com sucesso !
[2025-06-29T04:32:29.340+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws//json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:29.340+0000] {logging_mixin.py:188} INFO - Revenda Pryamos organizada com sucesso !
[2025-06-29T04:32:29.472+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46380-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:29.473+0000] {logging_mixin.py:188} INFO - Revenda Quality Automação e Recargas organizada com sucesso !
[2025-06-29T04:32:30.620+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/76963-586/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:30.621+0000] {logging_mixin.py:188} INFO - Revenda Rafah Soluções em Sistema organizada com sucesso !
[2025-06-29T04:32:31.772+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89803-460/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863d90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:31.772+0000] {logging_mixin.py:188} INFO - Revenda RC Automação organizada com sucesso !
[2025-06-29T04:32:32.924+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/05761-340/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863d00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:32.924+0000] {logging_mixin.py:188} INFO - Revenda RCM Tecnologia organizada com sucesso !
[2025-06-29T04:32:34.076+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/15910-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863e80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:34.077+0000] {logging_mixin.py:188} INFO - Revenda RedeEllo organizada com sucesso !
[2025-06-29T04:32:35.227+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/56310-130/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8636a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:35.228+0000] {logging_mixin.py:188} INFO - Revenda Rieger Consultoria e Serviços  organizada com sucesso !
[2025-06-29T04:32:36.380+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88104-435/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7df0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:36.381+0000] {logging_mixin.py:188} INFO - Revenda RKS Tecnologia organizada com sucesso !
[2025-06-29T04:32:36.513+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/76960-046/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84ce20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:36.514+0000] {logging_mixin.py:188} INFO - Revenda Rondoniatec Sistemas e Soluções organizada com sucesso !
[2025-06-29T04:32:37.660+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/48602-005/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:37.661+0000] {logging_mixin.py:188} INFO - Revenda Royal Ti organizada com sucesso !
[2025-06-29T04:32:38.813+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/28895-320/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:38.813+0000] {logging_mixin.py:188} INFO - Revenda RPD Tech Soluções em T.I. organizada com sucesso !
[2025-06-29T04:32:39.965+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/87970-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83df40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:39.966+0000] {logging_mixin.py:188} INFO - Revenda RPDV Soluções em Tecnologia organizada com sucesso !
[2025-06-29T04:32:41.116+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55825-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c49a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:41.116+0000] {logging_mixin.py:188} INFO - Revenda RS Informatica organizada com sucesso !
[2025-06-29T04:32:42.268+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/31270-350/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c1f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:42.269+0000] {logging_mixin.py:188} INFO - Revenda Rtek organizada com sucesso !
[2025-06-29T04:32:43.420+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89204-050/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:43.420+0000] {logging_mixin.py:188} INFO - Revenda SDN Sistemas de Gestão organizada com sucesso !
[2025-06-29T04:32:43.551+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/12914-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:43.552+0000] {logging_mixin.py:188} INFO - Revenda Seed Tecnologia organizada com sucesso !
[2025-06-29T04:32:44.699+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29560-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863c70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:44.700+0000] {logging_mixin.py:188} INFO - Revenda Shopseg Sistemas organizada com sucesso !
[2025-06-29T04:32:45.851+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88350-100/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8203a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:45.852+0000] {logging_mixin.py:188} INFO - Revenda Sig Sistemas Corporativos organizada com sucesso !
[2025-06-29T04:32:47.004+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/63034-150/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:47.004+0000] {logging_mixin.py:188} INFO - Revenda Sistech Sistemas organizada com sucesso !
[2025-06-29T04:32:48.163+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88350-270/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:48.164+0000] {logging_mixin.py:188} INFO - Revenda Sistema Completo organizada com sucesso !
[2025-06-29T04:32:49.308+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/45028-190/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7df0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:49.309+0000] {logging_mixin.py:188} INFO - Revenda Sistema Uniplus - Vitória da Conquista organizada com sucesso !
[2025-06-29T04:32:50.459+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/39680-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:50.460+0000] {logging_mixin.py:188} INFO - Revenda Skill Automação Comercial organizada com sucesso !
[2025-06-29T04:32:50.597+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88130-650/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:50.598+0000] {logging_mixin.py:188} INFO - Revenda SM10 Sistemas de Gestão e Automação Comercial  (AM10) organizada com sucesso !
[2025-06-29T04:32:51.740+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/79540-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4c70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:51.740+0000] {logging_mixin.py:188} INFO - Revenda Smith Tecnologias organizada com sucesso !
[2025-06-29T04:32:52.893+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50720-090/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:52.894+0000] {logging_mixin.py:188} INFO - Revenda SMQ Tecnologia organizada com sucesso !
[2025-06-29T04:32:54.044+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/44061-070/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4af0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:54.045+0000] {logging_mixin.py:188} INFO - Revenda Softech Tecnologia organizada com sucesso !
[2025-06-29T04:32:55.197+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/62011-205/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84cd30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:55.197+0000] {logging_mixin.py:188} INFO - Revenda SoftGadol organizada com sucesso !
[2025-06-29T04:32:56.348+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/60822-305/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:56.348+0000] {logging_mixin.py:188} INFO - Revenda Softkore organizada com sucesso !
[2025-06-29T04:32:56.478+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/27920-325/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8a9c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:56.479+0000] {logging_mixin.py:188} INFO - Revenda Softmaq Tecnologia organizada com sucesso !
[2025-06-29T04:32:57.628+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58500-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863c10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:57.628+0000] {logging_mixin.py:188} INFO - Revenda Softpollus organizada com sucesso !
[2025-06-29T04:32:58.779+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/61655-590/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8204c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:58.780+0000] {logging_mixin.py:188} INFO - Revenda Solem Tecnologia organizada com sucesso !
[2025-06-29T04:32:59.932+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95700-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:32:59.933+0000] {logging_mixin.py:188} INFO - Revenda Sonaglio Automação organizada com sucesso !
[2025-06-29T04:33:01.085+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50720-715/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:01.086+0000] {logging_mixin.py:188} INFO - Revenda Sonsun organizada com sucesso !
[2025-06-29T04:33:02.236+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50721-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820790>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:02.237+0000] {logging_mixin.py:188} INFO - Revenda Sophos Projetos organizada com sucesso !
[2025-06-29T04:33:03.388+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/99260-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:03.389+0000] {logging_mixin.py:188} INFO - Revenda Sparta Gestão e Contabilidade - DEOCLESYSTEM organizada com sucesso !
[2025-06-29T04:33:03.520+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37470-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4e20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:03.521+0000] {logging_mixin.py:188} INFO - Revenda Speed Automação Comercial organizada com sucesso !
[2025-06-29T04:33:04.669+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46400-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:04.669+0000] {logging_mixin.py:188} INFO - Revenda SS Informatica - Bahia organizada com sucesso !
[2025-06-29T04:33:05.820+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/65070-280/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:05.820+0000] {logging_mixin.py:188} INFO - Revenda SS Informática - Maranhão organizada com sucesso !
[2025-06-29T04:33:06.973+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59607-340/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c45b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:06.974+0000] {logging_mixin.py:188} INFO - Revenda Syscom Sistemas organizada com sucesso !
[2025-06-29T04:33:08.123+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/45075-290/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b8a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:08.124+0000] {logging_mixin.py:188} INFO - Revenda SYSFOUR - Intelligent Systems organizada com sucesso !
[2025-06-29T04:33:09.283+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89295-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:09.284+0000] {logging_mixin.py:188} INFO - Revenda System Bella Automação Comercial organizada com sucesso !
[2025-06-29T04:33:10.428+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89801-570/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c81c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:10.429+0000] {logging_mixin.py:188} INFO - Revenda TB Automação e Informática organizada com sucesso !
[2025-06-29T04:33:10.562+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59031-170/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:10.562+0000] {logging_mixin.py:188} INFO - Revenda TC Maquinas organizada com sucesso !
[2025-06-29T04:33:11.708+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/60750-030/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:11.709+0000] {logging_mixin.py:188} INFO - Revenda Technoside Informatica organizada com sucesso !
[2025-06-29T04:33:12.859+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/65800-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8209d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:12.860+0000] {logging_mixin.py:188} INFO - Revenda Tecmicro Informática organizada com sucesso !
[2025-06-29T04:33:14.011+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/79004-460/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8637f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:14.012+0000] {logging_mixin.py:188} INFO - Revenda Tecnoinfo organizada com sucesso !
[2025-06-29T04:33:15.164+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/68525-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:15.164+0000] {logging_mixin.py:188} INFO - Revenda TECSOLUTION organizada com sucesso !
[2025-06-29T04:33:16.315+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29050-565/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b87f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:16.316+0000] {logging_mixin.py:188} INFO - Revenda Tefcom organizada com sucesso !
[2025-06-29T04:33:17.470+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/68909-845/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:17.470+0000] {logging_mixin.py:188} INFO - Revenda TFA Tecnologia e Soluções  organizada com sucesso !
[2025-06-29T04:33:17.603+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95020-520/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d4220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:17.604+0000] {logging_mixin.py:188} INFO - Revenda TI-Brasil Sistemas organizada com sucesso !
[2025-06-29T04:33:18.747+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95084-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d4ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:18.748+0000] {logging_mixin.py:188} INFO - Revenda Trends Solutions organizada com sucesso !
[2025-06-29T04:33:19.900+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/67013-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:19.901+0000] {logging_mixin.py:188} INFO - Revenda TS TECH organizada com sucesso !
[2025-06-29T04:33:21.052+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89560-132/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b8dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:21.053+0000] {logging_mixin.py:188} INFO - Revenda Unisoft Sistemas ** Hardtech organizada com sucesso !
[2025-06-29T04:33:22.202+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88070-770/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8639a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:22.203+0000] {logging_mixin.py:188} INFO - Revenda Unitek Soluções organizada com sucesso !
[2025-06-29T04:33:23.355+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/20040-030/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d41c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:23.356+0000] {logging_mixin.py:188} INFO - Revenda Uniup Sistema - Automação e CFTV organizada com sucesso !
[2025-06-29T04:33:23.485+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89222-363/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:23.486+0000] {logging_mixin.py:188} INFO - Revenda Universal Automação Comercial  organizada com sucesso !
[2025-06-29T04:33:24.636+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78550-104/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:24.636+0000] {logging_mixin.py:188} INFO - Revenda Universo Sistemas organizada com sucesso !
[2025-06-29T04:33:25.788+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89620-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d4d00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:25.789+0000] {logging_mixin.py:188} INFO - Revenda Valor Tecnologia organizada com sucesso !
[2025-06-29T04:33:26.940+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/98700-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863b80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:26.941+0000] {logging_mixin.py:188} INFO - Revenda VGI TECHNOLOGY organizada com sucesso !
[2025-06-29T04:33:28.092+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/87504-480/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:28.093+0000] {logging_mixin.py:188} INFO - Revenda Via Nova Soluções em Tecnologia organizada com sucesso !
[2025-06-29T04:33:29.247+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37890-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:29.247+0000] {logging_mixin.py:188} INFO - Revenda Virtual Informatica_MG organizada com sucesso !
[2025-06-29T04:33:30.396+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89136-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c49a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:30.397+0000] {logging_mixin.py:188} INFO - Revenda Virtual Sistemas_SC organizada com sucesso !
[2025-06-29T04:33:30.530+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/26260-580/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8205b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:30.531+0000] {logging_mixin.py:188} INFO - Revenda VPN Solucoes em Informatica organizada com sucesso !
[2025-06-29T04:33:31.676+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89245-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c83d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:31.677+0000] {logging_mixin.py:188} INFO - Revenda Vzan Automação Comercial organizada com sucesso !
[2025-06-29T04:33:32.828+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21532-460/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c45e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:32.828+0000] {logging_mixin.py:188} INFO - Revenda Walltech Informatica organizada com sucesso !
[2025-06-29T04:33:33.980+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29103-240/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b87f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:33.980+0000] {logging_mixin.py:188} INFO - Revenda W C Sistemas organizada com sucesso !
[2025-06-29T04:33:35.132+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/06280-150/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:35.132+0000] {logging_mixin.py:188} INFO - Revenda WGE informatica organizada com sucesso !
[2025-06-29T04:33:36.284+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/31080-365/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:36.285+0000] {logging_mixin.py:188} INFO - Revenda WMX Soluções em Tecnologia organizada com sucesso !
[2025-06-29T04:33:37.436+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/30710-580/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-29T04:33:37.437+0000] {logging_mixin.py:188} INFO - Revenda X1 Automação organizada com sucesso !
[2025-06-29T04:33:37.550+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-29T04:33:37.567+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=DAG_atualizacao_cadastral_revendas, task_id=organized_response_database, execution_date=20250628T043000, start_date=20250629T043005, end_date=20250629T043337
[2025-06-29T04:33:37.656+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-29T04:33:37.694+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
