[2025-07-23T18:25:57.381+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_atualizacao_cadastral_revendas.insert_database scheduled__2025-07-22T04:30:00+00:00 [queued]>
[2025-07-23T18:25:57.397+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_atualizacao_cadastral_revendas.insert_database scheduled__2025-07-22T04:30:00+00:00 [queued]>
[2025-07-23T18:25:57.398+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-07-23T18:25:57.454+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): insert_database> on 2025-07-22 04:30:00+00:00
[2025-07-23T18:25:57.463+0000] {standard_task_runner.py:60} INFO - Started process 314 to run task
[2025-07-23T18:25:57.469+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'DAG_atualizacao_cadastral_revendas', 'insert_database', 'scheduled__2025-07-22T04:30:00+00:00', '--job-id', '642', '--raw', '--subdir', 'DAGS_FOLDER/DagDatasetComercial.py', '--cfg-path', '/tmp/tmpmdxfkmwq']
[2025-07-23T18:25:57.471+0000] {standard_task_runner.py:88} INFO - Job 642: Subtask insert_database
[2025-07-23T18:25:57.608+0000] {task_command.py:423} INFO - Running <TaskInstance: DAG_atualizacao_cadastral_revendas.insert_database scheduled__2025-07-22T04:30:00+00:00 [running]> on host 9ce214b77835
[2025-07-23T18:25:57.887+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_atualizacao_cadastral_revendas' AIRFLOW_CTX_TASK_ID='insert_database' AIRFLOW_CTX_EXECUTION_DATE='2025-07-22T04:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-22T04:30:00+00:00'
[2025-07-23T18:25:57.946+0000] {base.py:83} INFO - Using connection ID 'dataset_comercial_database' for task execution.
[2025-07-23T18:25:59.494+0000] {logging_mixin.py:188} INFO - Revenda A7 Soluções Atualizada com sucesso !
[2025-07-23T18:25:59.801+0000] {logging_mixin.py:188} INFO - Revenda AB Soluções em TI Atualizada com sucesso !
[2025-07-23T18:26:00.178+0000] {logging_mixin.py:188} INFO - Revenda Adonai Automação Comercial Atualizada com sucesso !
[2025-07-23T18:26:00.482+0000] {logging_mixin.py:188} INFO - Revenda ADV SIG Atualizada com sucesso !
[2025-07-23T18:26:00.801+0000] {logging_mixin.py:188} INFO - Revenda A e A Dist. de Informática - Softart Atualizada com sucesso !
[2025-07-23T18:26:01.126+0000] {logging_mixin.py:188} INFO - Revenda Af Suporte Atualizada com sucesso !
[2025-07-23T18:26:01.433+0000] {logging_mixin.py:188} INFO - Revenda Agedata Sistemas Atualizada com sucesso !
[2025-07-23T18:26:01.758+0000] {logging_mixin.py:188} INFO - Revenda AIO Solucoes Atualizada com sucesso !
[2025-07-23T18:26:02.058+0000] {logging_mixin.py:188} INFO - Revenda AllTecInfo Atualizada com sucesso !
[2025-07-23T18:26:02.357+0000] {logging_mixin.py:188} INFO - Revenda Alpha Systemas e informática Atualizada com sucesso !
[2025-07-23T18:26:02.658+0000] {logging_mixin.py:188} INFO - Revenda Alternativa Automação Comercial Atualizada com sucesso !
[2025-07-23T18:26:02.967+0000] {logging_mixin.py:188} INFO - Revenda Amigo do Micro Atualizada com sucesso !
[2025-07-23T18:26:03.273+0000] {logging_mixin.py:188} INFO - Revenda AND Consultores Associados Atualizada com sucesso !
[2025-07-23T18:26:03.559+0000] {logging_mixin.py:188} INFO - Revenda APRN Soluções Atualizada com sucesso !
[2025-07-23T18:26:03.843+0000] {logging_mixin.py:188} INFO - Revenda Ary Sistemas de Gestão e Informatica (RNS) Atualizada com sucesso !
[2025-07-23T18:26:04.132+0000] {logging_mixin.py:188} INFO - Revenda Asteqesystem Atualizada com sucesso !
[2025-07-23T18:26:04.415+0000] {logging_mixin.py:188} INFO - Revenda Atrium Sistemas Atualizada com sucesso !
[2025-07-23T18:26:04.702+0000] {logging_mixin.py:188} INFO - Revenda Automac Digitron Atualizada com sucesso !
[2025-07-23T18:26:04.990+0000] {logging_mixin.py:188} INFO - Revenda Automaquinas - Automação Comercial Atualizada com sucesso !
[2025-07-23T18:26:05.281+0000] {logging_mixin.py:188} INFO - Revenda Autosyste Tecnologia e Inovação Atualizada com sucesso !
[2025-07-23T18:26:05.577+0000] {logging_mixin.py:188} INFO - Revenda Autotech Informática Atualizada com sucesso !
[2025-07-23T18:26:05.879+0000] {logging_mixin.py:188} INFO - Revenda Bellabyte Atualizada com sucesso !
[2025-07-23T18:26:06.179+0000] {logging_mixin.py:188} INFO - Revenda Bitech Atualizada com sucesso !
[2025-07-23T18:26:06.477+0000] {logging_mixin.py:188} INFO - Revenda Boldtsoft Sistemas Atualizada com sucesso !
[2025-07-23T18:26:06.768+0000] {logging_mixin.py:188} INFO - Revenda BRAZ TI Atualizada com sucesso !
[2025-07-23T18:26:07.051+0000] {logging_mixin.py:188} INFO - Revenda Brusoft Informatica Atualizada com sucesso !
[2025-07-23T18:26:07.333+0000] {logging_mixin.py:188} INFO - Revenda Brvatech Atualizada com sucesso !
[2025-07-23T18:26:07.616+0000] {logging_mixin.py:188} INFO - Revenda Canal Tecnico (Lumi) Atualizada com sucesso !
[2025-07-23T18:26:07.655+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-07-23T18:26:07.659+0000] {process_utils.py:131} INFO - Sending 15 to group 314. PIDs of all processes in the group: [314]
[2025-07-23T18:26:07.660+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 314
[2025-07-23T18:26:07.758+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-07-23T18:26:07.759+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/DAG_atualizacao_cadastral_revendas/DatasetLoadedDataMining.py", line 68, in insert_database
    cursor.execute(query_verify, (revenda['revenda'],))
  File "/usr/local/lib/python3.8/encodings/utf_8.py", line 15, in decode
    def decode(input, errors='strict'):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/DAG_atualizacao_cadastral_revendas/DatasetLoadedDataMining.py", line 106, in insert_database
    raise RuntimeError("Erro ao inserir os dados no banco dataset") from erro
RuntimeError: Erro ao inserir os dados no banco dataset
[2025-07-23T18:26:07.792+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=DAG_atualizacao_cadastral_revendas, task_id=insert_database, execution_date=20250722T043000, start_date=20250723T182557, end_date=20250723T182607
[2025-07-23T18:26:07.862+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 642 for task insert_database (Erro ao inserir os dados no banco dataset; 314)
[2025-07-23T18:26:07.913+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=314, status='terminated', exitcode=1, started='18:25:57') (314) terminated with exit code 1
