[2025-06-28T04:30:07.989+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_atualizacao_cadastral_revendas.organized_response_database scheduled__2025-06-27T04:30:00+00:00 [queued]>
[2025-06-28T04:30:08.005+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_atualizacao_cadastral_revendas.organized_response_database scheduled__2025-06-27T04:30:00+00:00 [queued]>
[2025-06-28T04:30:08.006+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-28T04:30:08.075+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): organized_response_database> on 2025-06-27 04:30:00+00:00
[2025-06-28T04:30:08.084+0000] {standard_task_runner.py:60} INFO - Started process 384076 to run task
[2025-06-28T04:30:08.090+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'DAG_atualizacao_cadastral_revendas', 'organized_response_database', 'scheduled__2025-06-27T04:30:00+00:00', '--job-id', '277', '--raw', '--subdir', 'DAGS_FOLDER/DagDatasetComercial.py', '--cfg-path', '/tmp/tmpp0fya_rr']
[2025-06-28T04:30:08.092+0000] {standard_task_runner.py:88} INFO - Job 277: Subtask organized_response_database
[2025-06-28T04:30:08.205+0000] {task_command.py:423} INFO - Running <TaskInstance: DAG_atualizacao_cadastral_revendas.organized_response_database scheduled__2025-06-27T04:30:00+00:00 [running]> on host 99f5714845f7
[2025-06-28T04:30:08.429+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_atualizacao_cadastral_revendas' AIRFLOW_CTX_TASK_ID='organized_response_database' AIRFLOW_CTX_EXECUTION_DATE='2025-06-27T04:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-27T04:30:00+00:00'
[2025-06-28T04:30:08.600+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/75620-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8635e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:08.601+0000] {logging_mixin.py:188} INFO - Revenda A7 Soluções organizada com sucesso !
[2025-06-28T04:30:08.730+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/80540-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863e80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:08.731+0000] {logging_mixin.py:188} INFO - Revenda AB Soluções em TI organizada com sucesso !
[2025-06-28T04:30:08.862+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21070-032/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82e760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:08.863+0000] {logging_mixin.py:188} INFO - Revenda Adonai Automação Comercial organizada com sucesso !
[2025-06-28T04:30:08.995+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/39801-240/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83c040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:08.995+0000] {logging_mixin.py:188} INFO - Revenda ADV SIG organizada com sucesso !
[2025-06-28T04:30:09.124+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88400-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82eee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:09.125+0000] {logging_mixin.py:188} INFO - Revenda A e A Dist. de Informática - Softart organizada com sucesso !
[2025-06-28T04:30:09.256+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21235-604/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82e5e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:09.257+0000] {logging_mixin.py:188} INFO - Revenda Af Suporte organizada com sucesso !
[2025-06-28T04:30:10.393+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/60115-222/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:10.394+0000] {logging_mixin.py:188} INFO - Revenda Agedata Sistemas organizada com sucesso !
[2025-06-28T04:30:11.545+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78130-435/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8638e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:11.546+0000] {logging_mixin.py:188} INFO - Revenda AIO Solucoes organizada com sucesso !
[2025-06-28T04:30:11.677+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37701-706/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83c8e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:11.677+0000] {logging_mixin.py:188} INFO - Revenda AllTecInfo organizada com sucesso !
[2025-06-28T04:30:12.825+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78460-606/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c41c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:12.826+0000] {logging_mixin.py:188} INFO - Revenda Alpha Systemas e informática organizada com sucesso !
[2025-06-28T04:30:13.977+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85857-270/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:13.978+0000] {logging_mixin.py:188} INFO - Revenda Alternativa Automação Comercial organizada com sucesso !
[2025-06-28T04:30:15.129+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78575-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:15.130+0000] {logging_mixin.py:188} INFO - Revenda Amigo do Micro organizada com sucesso !
[2025-06-28T04:30:16.282+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85856-530/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83cfd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:16.283+0000] {logging_mixin.py:188} INFO - Revenda AND Consultores Associados organizada com sucesso !
[2025-06-28T04:30:17.433+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/82600-130/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83c3d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:17.434+0000] {logging_mixin.py:188} INFO - Revenda APRN Soluções organizada com sucesso !
[2025-06-28T04:30:18.587+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55540-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c48e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:18.588+0000] {logging_mixin.py:188} INFO - Revenda Ary Sistemas de Gestão e Informatica (RNS) organizada com sucesso !
[2025-06-28T04:30:18.719+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/66113-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c81c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:18.719+0000] {logging_mixin.py:188} INFO - Revenda Asteqesystem organizada com sucesso !
[2025-06-28T04:30:19.867+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/76908-430/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:19.867+0000] {logging_mixin.py:188} INFO - Revenda Atrium Sistemas organizada com sucesso !
[2025-06-28T04:30:21.017+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/27265-435/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:21.017+0000] {logging_mixin.py:188} INFO - Revenda Automac Digitron organizada com sucesso !
[2025-06-28T04:30:22.169+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29900-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:22.170+0000] {logging_mixin.py:188} INFO - Revenda Automaquinas - Automação Comercial organizada com sucesso !
[2025-06-28T04:30:23.322+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/44003-198/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:23.323+0000] {logging_mixin.py:188} INFO - Revenda Autosyste Tecnologia e Inovação organizada com sucesso !
[2025-06-28T04:30:24.472+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/25515-520/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:24.473+0000] {logging_mixin.py:188} INFO - Revenda Autotech Informática organizada com sucesso !
[2025-06-28T04:30:24.610+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/22710-112/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82e1c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:24.611+0000] {logging_mixin.py:188} INFO - Revenda Bellabyte organizada com sucesso !
[2025-06-28T04:30:25.753+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/68900-075/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82ea60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:25.754+0000] {logging_mixin.py:188} INFO - Revenda Bitech organizada com sucesso !
[2025-06-28T04:30:26.905+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29645-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8639a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:26.906+0000] {logging_mixin.py:188} INFO - Revenda Boldtsoft Sistemas organizada com sucesso !
[2025-06-28T04:30:28.057+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/66623-268/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:28.058+0000] {logging_mixin.py:188} INFO - Revenda BRAZ TI organizada com sucesso !
[2025-06-28T04:30:29.212+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88352-001/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82e8e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:29.212+0000] {logging_mixin.py:188} INFO - Revenda Brusoft Informatica organizada com sucesso !
[2025-06-28T04:30:30.362+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88312-260/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:30.363+0000] {logging_mixin.py:188} INFO - Revenda Brvatech organizada com sucesso !
[2025-06-28T04:30:31.512+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/70714-020/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c28e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:31.512+0000] {logging_mixin.py:188} INFO - Revenda Canal Tecnico (Lumi) organizada com sucesso !
[2025-06-28T04:30:31.642+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/57020-260/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c91c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:31.643+0000] {logging_mixin.py:188} INFO - Revenda Casa das Impressoras organizada com sucesso !
[2025-06-28T04:30:32.793+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85852-130/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c9a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:32.794+0000] {logging_mixin.py:188} INFO - Revenda CASTERS organizada com sucesso !
[2025-06-28T04:30:33.945+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55016-080/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c28e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:33.946+0000] {logging_mixin.py:188} INFO - Revenda Centec Equipamentos organizada com sucesso !
[2025-06-28T04:30:35.097+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/57442-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b8df0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:35.098+0000] {logging_mixin.py:188} INFO - Revenda CK Tech Consultoria organizada com sucesso !
[2025-06-28T04:30:36.249+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85065-420/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863a30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:36.250+0000] {logging_mixin.py:188} INFO - Revenda Compass Tecnologia da Informação organizada com sucesso !
[2025-06-28T04:30:37.400+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/38400-694/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c9640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:37.401+0000] {logging_mixin.py:188} INFO - Revenda Compucenter Software organizada com sucesso !
[2025-06-28T04:30:38.553+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/28735-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c41c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:38.554+0000] {logging_mixin.py:188} INFO - Revenda Conexão Informática Ltda organizada com sucesso !
[2025-06-28T04:30:38.682+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/57120-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:38.683+0000] {logging_mixin.py:188} INFO - Revenda Connect System Soluções em Tecnologia organizada com sucesso !
[2025-06-28T04:30:39.833+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/69047-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c9be0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:39.834+0000] {logging_mixin.py:188} INFO - Revenda Conte Certo Serviços organizada com sucesso !
[2025-06-28T04:30:40.985+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/15085-310/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:40.986+0000] {logging_mixin.py:188} INFO - Revenda Control Biz organizada com sucesso !
[2025-06-28T04:30:42.137+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55004-270/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:42.137+0000] {logging_mixin.py:188} INFO - Revenda CTi - Centro Técnico de Informática organizada com sucesso !
[2025-06-28T04:30:43.289+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21380-008/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c25e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:43.290+0000] {logging_mixin.py:188} INFO - Revenda D&A Automação Comercial organizada com sucesso !
[2025-06-28T04:30:44.440+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89228-080/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:44.441+0000] {logging_mixin.py:188} INFO - Revenda DALTEC Automacao Comercial organizada com sucesso !
[2025-06-28T04:30:45.593+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/38740-082/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:45.594+0000] {logging_mixin.py:188} INFO - Revenda DataConta Gestão de Negócios organizada com sucesso !
[2025-06-28T04:30:45.724+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89801-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:45.725+0000] {logging_mixin.py:188} INFO - Revenda Dataproxy organizada com sucesso !
[2025-06-28T04:30:46.872+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/91220-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:46.873+0000] {logging_mixin.py:188} INFO - Revenda DCODER organizada com sucesso !
[2025-06-28T04:30:48.025+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/77405-130/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c0a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:48.026+0000] {logging_mixin.py:188} INFO - Revenda D Data Soluções organizada com sucesso !
[2025-06-28T04:30:49.177+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/53421-321/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:49.178+0000] {logging_mixin.py:188} INFO - Revenda DGTEC organizada com sucesso !
[2025-06-28T04:30:50.329+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46400-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:50.330+0000] {logging_mixin.py:188} INFO - Revenda Digito Informatica organizada com sucesso !
[2025-06-28T04:30:51.481+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85060-080/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4eb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:51.482+0000] {logging_mixin.py:188} INFO - Revenda Dikoc Soluções em Software organizada com sucesso !
[2025-06-28T04:30:51.624+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/81200-150/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:51.624+0000] {logging_mixin.py:188} INFO - Revenda DMK Sistemas e Soluções - HSI organizada com sucesso !
[2025-06-28T04:30:52.761+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78635-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c9c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:52.762+0000] {logging_mixin.py:188} INFO - Revenda DMZ Informatica organizada com sucesso !
[2025-06-28T04:30:53.913+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/13843-201/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:53.914+0000] {logging_mixin.py:188} INFO - Revenda Dolphin Consultoria organizada com sucesso !
[2025-06-28T04:30:55.064+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/28913-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:55.065+0000] {logging_mixin.py:188} INFO - Revenda DSM Consultoria em T.I. organizada com sucesso !
[2025-06-28T04:30:56.217+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/79004-440/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2af0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:56.217+0000] {logging_mixin.py:188} INFO - Revenda Duall Tech organizada com sucesso !
[2025-06-28T04:30:57.370+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/41820-020/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2b80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:57.370+0000] {logging_mixin.py:188} INFO - Revenda DWH Comercio de Alimentos organizada com sucesso !
[2025-06-28T04:30:58.521+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88702-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cca90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:58.522+0000] {logging_mixin.py:188} INFO - Revenda Edcom Automação Comercial organizada com sucesso !
[2025-06-28T04:30:58.651+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/75901-630/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2eb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:58.652+0000] {logging_mixin.py:188} INFO - Revenda Eleve Tecnologia organizada com sucesso !
[2025-06-28T04:30:59.801+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88106-500/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:30:59.802+0000] {logging_mixin.py:188} INFO - Revenda Emlink Solucoes Empresariais organizada com sucesso !
[2025-06-28T04:31:00.952+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/64200-250/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:00.952+0000] {logging_mixin.py:188} INFO - Revenda Exatop Certificação Digital e Sistemas organizada com sucesso !
[2025-06-28T04:31:02.105+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89258-730/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:02.105+0000] {logging_mixin.py:188} INFO - Revenda Exodus Informática organizada com sucesso !
[2025-06-28T04:31:03.257+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89280-328/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cca90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:03.259+0000] {logging_mixin.py:188} INFO - Revenda Extrema Software de Gestão organizada com sucesso !
[2025-06-28T04:31:04.408+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/63660-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:04.409+0000] {logging_mixin.py:188} INFO - Revenda F5 Suporte e Automacão Comercial organizada com sucesso !
[2025-06-28T04:31:05.561+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/13273-410/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:05.562+0000] {logging_mixin.py:188} INFO - Revenda Facilita Sistemas organizada com sucesso !
[2025-06-28T04:31:05.691+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95670-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:05.692+0000] {logging_mixin.py:188} INFO - Revenda Facilsys organizada com sucesso !
[2025-06-28T04:31:06.841+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58808-485/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b8fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:06.843+0000] {logging_mixin.py:188} INFO - Revenda F & F Soluções Empresariais organizada com sucesso !
[2025-06-28T04:31:07.993+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88160-064/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:07.994+0000] {logging_mixin.py:188} INFO - Revenda FKSIS - Sistemas de Gestão organizada com sucesso !
[2025-06-28T04:31:09.147+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88354-610/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2e80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:09.148+0000] {logging_mixin.py:188} INFO - Revenda FlorySoftt organizada com sucesso !
[2025-06-28T04:31:10.298+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/23860-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:10.299+0000] {logging_mixin.py:188} INFO - Revenda Fn Info House organizada com sucesso !
[2025-06-28T04:31:11.449+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/63502-769/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c40a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:11.450+0000] {logging_mixin.py:188} INFO - Revenda FS Informatica organizada com sucesso !
[2025-06-28T04:31:12.600+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/84320-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c24f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:12.601+0000] {logging_mixin.py:188} INFO - Revenda Fusion Sistemas e Informatica organizada com sucesso !
[2025-06-28T04:31:12.728+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59900-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:12.729+0000] {logging_mixin.py:188} INFO - Revenda Gilmaq Automação Comercial organizada com sucesso !
[2025-06-28T04:31:13.881+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55825-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc7f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:13.882+0000] {logging_mixin.py:188} INFO - Revenda GM Soluções em Informática organizada com sucesso !
[2025-06-28T04:31:15.033+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/01311-927/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:15.034+0000] {logging_mixin.py:188} INFO - Revenda Grupo GUUW organizada com sucesso !
[2025-06-28T04:31:16.186+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37800-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:16.187+0000] {logging_mixin.py:188} INFO - Revenda Guaxutec organizada com sucesso !
[2025-06-28T04:31:17.337+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88508-190/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863910>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:17.338+0000] {logging_mixin.py:188} INFO - Revenda HSI Automação Comercial organizada com sucesso !
[2025-06-28T04:31:18.489+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/20756-100/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:18.490+0000] {logging_mixin.py:188} INFO - Revenda HWC Soluções organizada com sucesso !
[2025-06-28T04:31:18.618+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59500-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:18.619+0000] {logging_mixin.py:188} INFO - Revenda I7 Automação Comercial organizada com sucesso !
[2025-06-28T04:31:19.770+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29280-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:19.770+0000] {logging_mixin.py:188} INFO - Revenda Ideal Soluções Empresariais organizada com sucesso !
[2025-06-28T04:31:20.920+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59570-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc2b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:20.921+0000] {logging_mixin.py:188} INFO - Revenda ID Tecnologia organizada com sucesso !
[2025-06-28T04:31:22.073+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/06454-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c22b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:22.074+0000] {logging_mixin.py:188} INFO - Revenda IFFI Soluções organizada com sucesso !
[2025-06-28T04:31:23.225+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/69980-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2c10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:23.225+0000] {logging_mixin.py:188} INFO - Revenda IG TEC organizada com sucesso !
[2025-06-28T04:31:24.376+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58900-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4c10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:24.377+0000] {logging_mixin.py:188} INFO - Revenda INFOPRINTER organizada com sucesso !
[2025-06-28T04:31:25.528+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21011-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:25.529+0000] {logging_mixin.py:188} INFO - Revenda INFORMIT organizada com sucesso !
[2025-06-28T04:31:25.657+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/69303-045/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7ccc10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:25.657+0000] {logging_mixin.py:188} INFO - Revenda Infor Serviços organizada com sucesso !
[2025-06-28T04:31:26.809+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/48601-270/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:26.810+0000] {logging_mixin.py:188} INFO - Revenda Infortec Automacao Comercial organizada com sucesso !
[2025-06-28T04:31:27.960+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46430-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:27.961+0000] {logging_mixin.py:188} INFO - Revenda Infotek organizada com sucesso !
[2025-06-28T04:31:29.113+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/26535-190/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8634f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:29.114+0000] {logging_mixin.py:188} INFO - Revenda Innovati Tecnologia (INW Store) organizada com sucesso !
[2025-06-28T04:31:30.264+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50865-090/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4a00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:30.265+0000] {logging_mixin.py:188} INFO - Revenda Inova Software organizada com sucesso !
[2025-06-28T04:31:31.420+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55130-970/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c44f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:31.421+0000] {logging_mixin.py:188} INFO - Revenda Inspire Consult & Informatica  organizada com sucesso !
[2025-06-28T04:31:32.569+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89801-106/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8636a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:32.570+0000] {logging_mixin.py:188} INFO - Revenda Inteltix Tecnologia (Center) organizada com sucesso !
[2025-06-28T04:31:32.698+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/79823-290/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c1f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:32.699+0000] {logging_mixin.py:188} INFO - Revenda J7 Automação Comercial - System HD organizada com sucesso !
[2025-06-28T04:31:33.849+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78360-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:33.849+0000] {logging_mixin.py:188} INFO - Revenda Jann Informatica organizada com sucesso !
[2025-06-28T04:31:35.001+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/76997-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7ccb20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:35.002+0000] {logging_mixin.py:188} INFO - Revenda JB Tecnologia organizada com sucesso !
[2025-06-28T04:31:36.154+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/68460-245/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:36.155+0000] {logging_mixin.py:188} INFO - Revenda J & E Soluções organizada com sucesso !
[2025-06-28T04:31:37.305+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46430-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d74f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:37.306+0000] {logging_mixin.py:188} INFO - Revenda JExpress organizada com sucesso !
[2025-06-28T04:31:38.457+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58077-062/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc9d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:38.457+0000] {logging_mixin.py:188} INFO - Revenda J F Soluções Informatica organizada com sucesso !
[2025-06-28T04:31:39.610+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/69058-580/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cca30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:39.611+0000] {logging_mixin.py:188} INFO - Revenda J F Tech Tecnologia & Sistemas organizada com sucesso !
[2025-06-28T04:31:39.739+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/31255-780/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7013da4070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:39.739+0000] {logging_mixin.py:188} INFO - Revenda JHLS Automação Comercial organizada com sucesso !
[2025-06-28T04:31:40.889+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/12914-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:40.890+0000] {logging_mixin.py:188} INFO - Revenda Jinsei Contabilidade organizada com sucesso !
[2025-06-28T04:31:42.042+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/27197-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4af0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:42.043+0000] {logging_mixin.py:188} INFO - Revenda JJ Serviços organizada com sucesso !
[2025-06-28T04:31:43.194+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/49055-620/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:43.195+0000] {logging_mixin.py:188} INFO - Revenda JM Informatica organizada com sucesso !
[2025-06-28T04:31:44.345+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89220-110/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:44.346+0000] {logging_mixin.py:188} INFO - Revenda JP Automação Comercial organizada com sucesso !
[2025-06-28T04:31:45.498+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78250-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84cd60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:45.499+0000] {logging_mixin.py:188} INFO - Revenda JSR Automação Comercial  organizada com sucesso !
[2025-06-28T04:31:45.627+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89700-166/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c49a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:45.628+0000] {logging_mixin.py:188} INFO - Revenda Kernel Sistemas organizada com sucesso !
[2025-06-28T04:31:46.776+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/14010-180/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:46.777+0000] {logging_mixin.py:188} INFO - Revenda KMCI Tecnologia em Automação organizada com sucesso !
[2025-06-28T04:31:47.929+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/25555-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c28e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:47.932+0000] {logging_mixin.py:188} INFO - Revenda Komputronic do Brasil organizada com sucesso !
[2025-06-28T04:31:49.081+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29052-170/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:49.082+0000] {logging_mixin.py:188} INFO - Revenda KSC Sistemas organizada com sucesso !
[2025-06-28T04:31:50.233+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50010-100/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:50.234+0000] {logging_mixin.py:188} INFO - Revenda L&D Comercio e Tecnologia organizada com sucesso !
[2025-06-28T04:31:51.385+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/25935-530/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c28e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:51.385+0000] {logging_mixin.py:188} INFO - Revenda LD Tech organizada com sucesso !
[2025-06-28T04:31:52.538+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29375-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c0a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:52.538+0000] {logging_mixin.py:188} INFO - Revenda LF Sistemas organizada com sucesso !
[2025-06-28T04:31:52.668+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/39400-215/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:52.669+0000] {logging_mixin.py:188} INFO - Revenda LiderTech organizada com sucesso !
[2025-06-28T04:31:53.816+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/93700-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d75b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:53.817+0000] {logging_mixin.py:188} INFO - Revenda Life Sistemas  organizada com sucesso !
[2025-06-28T04:31:54.969+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/20250-450/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:54.970+0000] {logging_mixin.py:188} INFO - Revenda LL Tecnologia organizada com sucesso !
[2025-06-28T04:31:56.121+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/36884-004/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:56.122+0000] {logging_mixin.py:188} INFO - Revenda LMD Sistemas organizada com sucesso !
[2025-06-28T04:31:57.273+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/22730-001/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863b80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:57.274+0000] {logging_mixin.py:188} INFO - Revenda Logitec 2000 Informatica organizada com sucesso !
[2025-06-28T04:31:58.425+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37470-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8a9c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:58.426+0000] {logging_mixin.py:188} INFO - Revenda Macmos organizada com sucesso !
[2025-06-28T04:31:59.577+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59300-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c21f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:59.578+0000] {logging_mixin.py:188} INFO - Revenda Mape Informatica organizada com sucesso !
[2025-06-28T04:31:59.705+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89900-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2c10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:31:59.706+0000] {logging_mixin.py:188} INFO - Revenda Marcka Informática e Sistemas organizada com sucesso !
[2025-06-28T04:32:00.858+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58041-070/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4be0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:00.859+0000] {logging_mixin.py:188} INFO - Revenda Matechinfo organizada com sucesso !
[2025-06-28T04:32:02.009+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88355-393/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:02.010+0000] {logging_mixin.py:188} INFO - Revenda MB Tecnologia organizada com sucesso !
[2025-06-28T04:32:03.162+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/82015-520/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:03.163+0000] {logging_mixin.py:188} INFO - Revenda MC2 Tecnologia organizada com sucesso !
[2025-06-28T04:32:04.313+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89562-180/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:04.314+0000] {logging_mixin.py:188} INFO - Revenda MCR Sistemas (RS-AMX) organizada com sucesso !
[2025-06-28T04:32:05.465+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21660-060/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b86d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:05.466+0000] {logging_mixin.py:188} INFO - Revenda MD Tech Automação organizada com sucesso !
[2025-06-28T04:32:06.617+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46430-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:06.618+0000] {logging_mixin.py:188} INFO - Revenda Megasoft Informatica organizada com sucesso !
[2025-06-28T04:32:06.745+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95270-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c44f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:06.746+0000] {logging_mixin.py:188} INFO - Revenda Mercantec Soluções organizada com sucesso !
[2025-06-28T04:32:07.898+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88310-661/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:07.898+0000] {logging_mixin.py:188} INFO - Revenda Mikrox "Somadatta" organizada com sucesso !
[2025-06-28T04:32:09.049+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/63010-127/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7a00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:09.050+0000] {logging_mixin.py:188} INFO - Revenda M. Nobre (Terabyte) organizada com sucesso !
[2025-06-28T04:32:10.201+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/32310-210/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:10.202+0000] {logging_mixin.py:188} INFO - Revenda MRsis Automação organizada com sucesso !
[2025-06-28T04:32:11.353+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37062-170/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:11.353+0000] {logging_mixin.py:188} INFO - Revenda M&R Soluções - Grupo ATL organizada com sucesso !
[2025-06-28T04:32:12.506+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/47640-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:12.507+0000] {logging_mixin.py:188} INFO - Revenda Multi Soft organizada com sucesso !
[2025-06-28T04:32:12.637+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78390-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:12.638+0000] {logging_mixin.py:188} INFO - Revenda NewCompras.com.br organizada com sucesso !
[2025-06-28T04:32:13.785+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/67030-080/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7ee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:13.786+0000] {logging_mixin.py:188} INFO - Revenda NEWTEF Automação organizada com sucesso !
[2025-06-28T04:32:14.937+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50960-400/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:14.938+0000] {logging_mixin.py:188} INFO - Revenda Next Store organizada com sucesso !
[2025-06-28T04:32:16.089+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37730-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:16.090+0000] {logging_mixin.py:188} INFO - Revenda Nova Loja organizada com sucesso !
[2025-06-28T04:32:17.241+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/17210-420/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:17.242+0000] {logging_mixin.py:188} INFO - Revenda NovaPC organizada com sucesso !
[2025-06-28T04:32:18.393+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/39400-163/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b87c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:18.394+0000] {logging_mixin.py:188} INFO - Revenda Optimus - Gestão organizada com sucesso !
[2025-06-28T04:32:19.545+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/98803-412/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:19.546+0000] {logging_mixin.py:188} INFO - Revenda Otimizer Consultoria em Sistemas organizada com sucesso !
[2025-06-28T04:32:19.674+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/62500-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d72e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:19.675+0000] {logging_mixin.py:188} INFO - Revenda Otimize Soluções organizada com sucesso !
[2025-06-28T04:32:20.826+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95034-160/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:20.827+0000] {logging_mixin.py:188} INFO - Revenda P21 Software organizada com sucesso !
[2025-06-28T04:32:21.977+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50980-480/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:21.978+0000] {logging_mixin.py:188} INFO - Revenda PALM Soluções organizada com sucesso !
[2025-06-28T04:32:23.128+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/84040-010/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:23.129+0000] {logging_mixin.py:188} INFO - Revenda Parceria Informatica organizada com sucesso !
[2025-06-28T04:32:24.281+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88330-725/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d70d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:24.282+0000] {logging_mixin.py:188} INFO - Revenda PDV Automação organizada com sucesso !
[2025-06-28T04:32:25.433+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/38700-001/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:25.433+0000] {logging_mixin.py:188} INFO - Revenda PEG Informatica organizada com sucesso !
[2025-06-28T04:32:26.585+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95200-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:26.585+0000] {logging_mixin.py:188} INFO - Revenda Piramide Automação e Informatica organizada com sucesso !
[2025-06-28T04:32:26.727+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/70314-900/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2a30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:26.727+0000] {logging_mixin.py:188} INFO - Revenda Plus Solutions organizada com sucesso !
[2025-06-28T04:32:27.863+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88350-564/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:27.864+0000] {logging_mixin.py:188} INFO - Revenda Ponte organizada com sucesso !
[2025-06-28T04:32:29.017+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29700-550/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c43a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:29.017+0000] {logging_mixin.py:188} INFO - Revenda Pratic Informática organizada com sucesso !
[2025-06-28T04:32:30.169+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/65930-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2d30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:30.170+0000] {logging_mixin.py:188} INFO - Revenda PROFISC - Consultoria  organizada com sucesso !
[2025-06-28T04:32:31.321+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws//json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:31.322+0000] {logging_mixin.py:188} INFO - Revenda Pryamos organizada com sucesso !
[2025-06-28T04:32:32.473+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46380-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:32.474+0000] {logging_mixin.py:188} INFO - Revenda Quality Automação e Recargas organizada com sucesso !
[2025-06-28T04:32:32.601+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/76963-586/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:32.602+0000] {logging_mixin.py:188} INFO - Revenda Rafah Soluções em Sistema organizada com sucesso !
[2025-06-28T04:32:33.754+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89803-460/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863d90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:33.755+0000] {logging_mixin.py:188} INFO - Revenda RC Automação organizada com sucesso !
[2025-06-28T04:32:34.905+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/05761-340/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863d00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:34.906+0000] {logging_mixin.py:188} INFO - Revenda RCM Tecnologia organizada com sucesso !
[2025-06-28T04:32:36.057+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/15910-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863e80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:36.058+0000] {logging_mixin.py:188} INFO - Revenda RedeEllo organizada com sucesso !
[2025-06-28T04:32:37.209+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/56310-130/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8636a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:37.210+0000] {logging_mixin.py:188} INFO - Revenda Rieger Consultoria e Serviços  organizada com sucesso !
[2025-06-28T04:32:38.361+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88104-435/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7df0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:38.361+0000] {logging_mixin.py:188} INFO - Revenda RKS Tecnologia organizada com sucesso !
[2025-06-28T04:32:39.513+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/76960-046/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84ce20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:39.514+0000] {logging_mixin.py:188} INFO - Revenda Rondoniatec Sistemas e Soluções organizada com sucesso !
[2025-06-28T04:32:39.643+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/48602-005/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:39.644+0000] {logging_mixin.py:188} INFO - Revenda Royal Ti organizada com sucesso !
[2025-06-28T04:32:40.794+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/28895-320/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2d90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:40.795+0000] {logging_mixin.py:188} INFO - Revenda RPD Tech Soluções em T.I. organizada com sucesso !
[2025-06-28T04:32:41.946+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/87970-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:41.946+0000] {logging_mixin.py:188} INFO - Revenda RPDV Soluções em Tecnologia organizada com sucesso !
[2025-06-28T04:32:43.098+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55825-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:43.099+0000] {logging_mixin.py:188} INFO - Revenda RS Informatica organizada com sucesso !
[2025-06-28T04:32:44.249+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/31270-350/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c1f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:44.250+0000] {logging_mixin.py:188} INFO - Revenda Rtek organizada com sucesso !
[2025-06-28T04:32:45.402+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89204-050/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:45.403+0000] {logging_mixin.py:188} INFO - Revenda SDN Sistemas de Gestão organizada com sucesso !
[2025-06-28T04:32:46.553+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/12914-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:46.554+0000] {logging_mixin.py:188} INFO - Revenda Seed Tecnologia organizada com sucesso !
[2025-06-28T04:32:46.682+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29560-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863c70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:46.683+0000] {logging_mixin.py:188} INFO - Revenda Shopseg Sistemas organizada com sucesso !
[2025-06-28T04:32:47.833+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88350-100/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7dc3a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:47.834+0000] {logging_mixin.py:188} INFO - Revenda Sig Sistemas Corporativos organizada com sucesso !
[2025-06-28T04:32:48.985+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/63034-150/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:48.985+0000] {logging_mixin.py:188} INFO - Revenda Sistech Sistemas organizada com sucesso !
[2025-06-28T04:32:50.136+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88350-270/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:50.137+0000] {logging_mixin.py:188} INFO - Revenda Sistema Completo organizada com sucesso !
[2025-06-28T04:32:51.289+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/45028-190/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7df0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:51.290+0000] {logging_mixin.py:188} INFO - Revenda Sistema Uniplus - Vitória da Conquista organizada com sucesso !
[2025-06-28T04:32:52.442+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/39680-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:52.442+0000] {logging_mixin.py:188} INFO - Revenda Skill Automação Comercial organizada com sucesso !
[2025-06-28T04:32:53.594+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88130-650/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:53.595+0000] {logging_mixin.py:188} INFO - Revenda SM10 Sistemas de Gestão e Automação Comercial  (AM10) organizada com sucesso !
[2025-06-28T04:32:53.731+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/79540-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:53.732+0000] {logging_mixin.py:188} INFO - Revenda Smith Tecnologias organizada com sucesso !
[2025-06-28T04:32:54.875+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50720-090/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7dcc40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:54.875+0000] {logging_mixin.py:188} INFO - Revenda SMQ Tecnologia organizada com sucesso !
[2025-06-28T04:32:56.025+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/44061-070/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:56.026+0000] {logging_mixin.py:188} INFO - Revenda Softech Tecnologia organizada com sucesso !
[2025-06-28T04:32:57.175+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/62011-205/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84cd30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:57.176+0000] {logging_mixin.py:188} INFO - Revenda SoftGadol organizada com sucesso !
[2025-06-28T04:32:58.330+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/60822-305/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:58.331+0000] {logging_mixin.py:188} INFO - Revenda Softkore organizada com sucesso !
[2025-06-28T04:32:59.481+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/27920-325/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8a9c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:59.482+0000] {logging_mixin.py:188} INFO - Revenda Softmaq Tecnologia organizada com sucesso !
[2025-06-28T04:32:59.610+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58500-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863c10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:32:59.611+0000] {logging_mixin.py:188} INFO - Revenda Softpollus organizada com sucesso !
[2025-06-28T04:33:00.761+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/61655-590/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7dc4c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:00.762+0000] {logging_mixin.py:188} INFO - Revenda Solem Tecnologia organizada com sucesso !
[2025-06-28T04:33:01.913+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95700-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:01.914+0000] {logging_mixin.py:188} INFO - Revenda Sonaglio Automação organizada com sucesso !
[2025-06-28T04:33:03.065+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50720-715/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:03.065+0000] {logging_mixin.py:188} INFO - Revenda Sonsun organizada com sucesso !
[2025-06-28T04:33:04.216+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50721-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7dc790>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:04.216+0000] {logging_mixin.py:188} INFO - Revenda Sophos Projetos organizada com sucesso !
[2025-06-28T04:33:05.370+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/99260-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7dc310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:05.371+0000] {logging_mixin.py:188} INFO - Revenda Sparta Gestão e Contabilidade - DEOCLESYSTEM organizada com sucesso !
[2025-06-28T04:33:06.522+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37470-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:06.522+0000] {logging_mixin.py:188} INFO - Revenda Speed Automação Comercial organizada com sucesso !
[2025-06-28T04:33:06.653+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46400-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:06.654+0000] {logging_mixin.py:188} INFO - Revenda SS Informatica - Bahia organizada com sucesso !
[2025-06-28T04:33:07.801+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/65070-280/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:07.802+0000] {logging_mixin.py:188} INFO - Revenda SS Informática - Maranhão organizada com sucesso !
[2025-06-28T04:33:08.953+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59607-340/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:08.954+0000] {logging_mixin.py:188} INFO - Revenda Syscom Sistemas organizada com sucesso !
[2025-06-28T04:33:10.103+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/45075-290/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b8a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:10.104+0000] {logging_mixin.py:188} INFO - Revenda SYSFOUR - Intelligent Systems organizada com sucesso !
[2025-06-28T04:33:11.257+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89295-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:11.257+0000] {logging_mixin.py:188} INFO - Revenda System Bella Automação Comercial organizada com sucesso !
[2025-06-28T04:33:12.409+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89801-570/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c81c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:12.409+0000] {logging_mixin.py:188} INFO - Revenda TB Automação e Informática organizada com sucesso !
[2025-06-28T04:33:13.561+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59031-170/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d4220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:13.561+0000] {logging_mixin.py:188} INFO - Revenda TC Maquinas organizada com sucesso !
[2025-06-28T04:33:13.689+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/60750-030/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d4ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:13.690+0000] {logging_mixin.py:188} INFO - Revenda Technoside Informatica organizada com sucesso !
[2025-06-28T04:33:14.841+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/65800-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d49d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:14.842+0000] {logging_mixin.py:188} INFO - Revenda Tecmicro Informática organizada com sucesso !
[2025-06-28T04:33:15.993+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/79004-460/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8637f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:15.994+0000] {logging_mixin.py:188} INFO - Revenda Tecnoinfo organizada com sucesso !
[2025-06-28T04:33:17.146+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/68525-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:17.147+0000] {logging_mixin.py:188} INFO - Revenda TECSOLUTION organizada com sucesso !
[2025-06-28T04:33:18.297+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29050-565/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b87f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:18.297+0000] {logging_mixin.py:188} INFO - Revenda Tefcom organizada com sucesso !
[2025-06-28T04:33:19.449+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/68909-845/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2d30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:19.449+0000] {logging_mixin.py:188} INFO - Revenda TFA Tecnologia e Soluções  organizada com sucesso !
[2025-06-28T04:33:20.601+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95020-520/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7dc220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:20.602+0000] {logging_mixin.py:188} INFO - Revenda TI-Brasil Sistemas organizada com sucesso !
[2025-06-28T04:33:20.734+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95084-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7dcac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:20.735+0000] {logging_mixin.py:188} INFO - Revenda Trends Solutions organizada com sucesso !
[2025-06-28T04:33:21.881+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/67013-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:21.882+0000] {logging_mixin.py:188} INFO - Revenda TS TECH organizada com sucesso !
[2025-06-28T04:33:23.034+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89560-132/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b8dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:23.037+0000] {logging_mixin.py:188} INFO - Revenda Unisoft Sistemas ** Hardtech organizada com sucesso !
[2025-06-28T04:33:24.185+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88070-770/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8639a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:24.186+0000] {logging_mixin.py:188} INFO - Revenda Unitek Soluções organizada com sucesso !
[2025-06-28T04:33:25.337+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/20040-030/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7dc1c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:25.337+0000] {logging_mixin.py:188} INFO - Revenda Uniup Sistema - Automação e CFTV organizada com sucesso !
[2025-06-28T04:33:26.490+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89222-363/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:26.491+0000] {logging_mixin.py:188} INFO - Revenda Universal Automação Comercial  organizada com sucesso !
[2025-06-28T04:33:26.622+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78550-104/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:26.622+0000] {logging_mixin.py:188} INFO - Revenda Universo Sistemas organizada com sucesso !
[2025-06-28T04:33:27.769+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89620-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7dcd00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:27.770+0000] {logging_mixin.py:188} INFO - Revenda Valor Tecnologia organizada com sucesso !
[2025-06-28T04:33:28.921+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/98700-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863b80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:28.921+0000] {logging_mixin.py:188} INFO - Revenda VGI TECHNOLOGY organizada com sucesso !
[2025-06-28T04:33:30.074+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/87504-480/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:30.074+0000] {logging_mixin.py:188} INFO - Revenda Via Nova Soluções em Tecnologia organizada com sucesso !
[2025-06-28T04:33:31.225+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37890-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:31.226+0000] {logging_mixin.py:188} INFO - Revenda Virtual Informatica_MG organizada com sucesso !
[2025-06-28T04:33:32.377+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89136-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:32.378+0000] {logging_mixin.py:188} INFO - Revenda Virtual Sistemas_SC organizada com sucesso !
[2025-06-28T04:33:33.529+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/26260-580/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c85b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:33.530+0000] {logging_mixin.py:188} INFO - Revenda VPN Solucoes em Informatica organizada com sucesso !
[2025-06-28T04:33:33.660+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89245-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d43d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:33.661+0000] {logging_mixin.py:188} INFO - Revenda Vzan Automação Comercial organizada com sucesso !
[2025-06-28T04:33:34.808+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21532-460/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c23d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:34.809+0000] {logging_mixin.py:188} INFO - Revenda Walltech Informatica organizada com sucesso !
[2025-06-28T04:33:35.962+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29103-240/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b87f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:35.963+0000] {logging_mixin.py:188} INFO - Revenda W C Sistemas organizada com sucesso !
[2025-06-28T04:33:37.114+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/06280-150/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:37.114+0000] {logging_mixin.py:188} INFO - Revenda WGE informatica organizada com sucesso !
[2025-06-28T04:33:38.263+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/31080-365/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:38.264+0000] {logging_mixin.py:188} INFO - Revenda WMX Soluções em Tecnologia organizada com sucesso !
[2025-06-28T04:33:39.417+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/30710-580/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-28T04:33:39.418+0000] {logging_mixin.py:188} INFO - Revenda X1 Automação organizada com sucesso !
[2025-06-28T04:33:39.529+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-28T04:33:39.550+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=DAG_atualizacao_cadastral_revendas, task_id=organized_response_database, execution_date=20250627T043000, start_date=20250628T043007, end_date=20250628T043339
[2025-06-28T04:33:39.626+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-28T04:33:39.663+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
