[2025-07-25T01:35:06.078+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_atualizacao_financeiro_intelidata.executar_query_gnio scheduled__2025-07-24T01:30:00+00:00 [queued]>
[2025-07-25T01:35:06.094+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_atualizacao_financeiro_intelidata.executar_query_gnio scheduled__2025-07-24T01:30:00+00:00 [queued]>
[2025-07-25T01:35:06.094+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-07-25T01:35:06.163+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): executar_query_gnio> on 2025-07-24 01:30:00+00:00
[2025-07-25T01:35:06.181+0000] {standard_task_runner.py:60} INFO - Started process 66967 to run task
[2025-07-25T01:35:06.189+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'DAG_atualizacao_financeiro_intelidata', 'executar_query_gnio', 'scheduled__2025-07-24T01:30:00+00:00', '--job-id', '660', '--raw', '--subdir', 'DAGS_FOLDER/Dagfinanceirointelidata.py', '--cfg-path', '/tmp/tmpfnvbex48']
[2025-07-25T01:35:06.194+0000] {standard_task_runner.py:88} INFO - Job 660: Subtask executar_query_gnio
[2025-07-25T01:35:06.564+0000] {task_command.py:423} INFO - Running <TaskInstance: DAG_atualizacao_financeiro_intelidata.executar_query_gnio scheduled__2025-07-24T01:30:00+00:00 [running]> on host 9ce214b77835
[2025-07-25T01:35:06.774+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Pedro' AIRFLOW_CTX_DAG_ID='DAG_atualizacao_financeiro_intelidata' AIRFLOW_CTX_TASK_ID='executar_query_gnio' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T01:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-24T01:30:00+00:00'
[2025-07-25T01:35:06.797+0000] {base.py:83} INFO - Using connection ID 'gnio' for task execution.
[2025-07-25T01:35:07.733+0000] {warnings.py:109} WARNING - /opt/***/dags/DAG_financeiro_intelidata/AtualizacaoFinanceiro.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection_gnio)

[2025-07-25T01:35:08.038+0000] {logging_mixin.py:188} INFO - ðŸš« Erro na query GNIO: Query retornou DataFrame vazio!
[2025-07-25T01:35:08.040+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/DAG_financeiro_intelidata/AtualizacaoFinanceiro.py", line 41, in executar_query_gnio
    raise ValueError("Query retornou DataFrame vazio!")
ValueError: Query retornou DataFrame vazio!
[2025-07-25T01:35:08.055+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=DAG_atualizacao_financeiro_intelidata, task_id=executar_query_gnio, execution_date=20250724T013000, start_date=20250725T013506, end_date=20250725T013508
[2025-07-25T01:35:08.105+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 660 for task executar_query_gnio (Query retornou DataFrame vazio!; 66967)
[2025-07-25T01:35:08.131+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-25T01:35:08.443+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
