[2025-06-30T04:30:04.964+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_atualizacao_cadastral_revendas.organized_response_database scheduled__2025-06-29T04:30:00+00:00 [queued]>
[2025-06-30T04:30:04.980+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_atualizacao_cadastral_revendas.organized_response_database scheduled__2025-06-29T04:30:00+00:00 [queued]>
[2025-06-30T04:30:04.980+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-30T04:30:05.019+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): organized_response_database> on 2025-06-29 04:30:00+00:00
[2025-06-30T04:30:05.027+0000] {standard_task_runner.py:60} INFO - Started process 487027 to run task
[2025-06-30T04:30:05.035+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'DAG_atualizacao_cadastral_revendas', 'organized_response_database', 'scheduled__2025-06-29T04:30:00+00:00', '--job-id', '305', '--raw', '--subdir', 'DAGS_FOLDER/DagDatasetComercial.py', '--cfg-path', '/tmp/tmpa00win58']
[2025-06-30T04:30:05.037+0000] {standard_task_runner.py:88} INFO - Job 305: Subtask organized_response_database
[2025-06-30T04:30:05.159+0000] {task_command.py:423} INFO - Running <TaskInstance: DAG_atualizacao_cadastral_revendas.organized_response_database scheduled__2025-06-29T04:30:00+00:00 [running]> on host 99f5714845f7
[2025-06-30T04:30:05.381+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_atualizacao_cadastral_revendas' AIRFLOW_CTX_TASK_ID='organized_response_database' AIRFLOW_CTX_EXECUTION_DATE='2025-06-29T04:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-29T04:30:00+00:00'
[2025-06-30T04:30:05.549+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/75620-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8635e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:05.549+0000] {logging_mixin.py:188} INFO - Revenda A7 Soluções organizada com sucesso !
[2025-06-30T04:30:05.677+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/80540-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863e80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:05.678+0000] {logging_mixin.py:188} INFO - Revenda AB Soluções em TI organizada com sucesso !
[2025-06-30T04:30:05.809+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21070-032/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82e760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:05.810+0000] {logging_mixin.py:188} INFO - Revenda Adonai Automação Comercial organizada com sucesso !
[2025-06-30T04:30:05.938+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/39801-240/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83c040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:05.939+0000] {logging_mixin.py:188} INFO - Revenda ADV SIG organizada com sucesso !
[2025-06-30T04:30:06.070+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88400-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82eee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:06.071+0000] {logging_mixin.py:188} INFO - Revenda A e A Dist. de Informática - Softart organizada com sucesso !
[2025-06-30T04:30:06.199+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21235-604/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82e5e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:06.200+0000] {logging_mixin.py:188} INFO - Revenda Af Suporte organizada com sucesso !
[2025-06-30T04:30:07.387+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/60115-222/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:07.388+0000] {logging_mixin.py:188} INFO - Revenda Agedata Sistemas organizada com sucesso !
[2025-06-30T04:30:08.537+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78130-435/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8638e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:08.538+0000] {logging_mixin.py:188} INFO - Revenda AIO Solucoes organizada com sucesso !
[2025-06-30T04:30:08.667+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37701-706/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83c8e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:08.668+0000] {logging_mixin.py:188} INFO - Revenda AllTecInfo organizada com sucesso !
[2025-06-30T04:30:09.817+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78460-606/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c41c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:09.817+0000] {logging_mixin.py:188} INFO - Revenda Alpha Systemas e informática organizada com sucesso !
[2025-06-30T04:30:10.969+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85857-270/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:10.969+0000] {logging_mixin.py:188} INFO - Revenda Alternativa Automação Comercial organizada com sucesso !
[2025-06-30T04:30:12.121+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78575-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:12.122+0000] {logging_mixin.py:188} INFO - Revenda Amigo do Micro organizada com sucesso !
[2025-06-30T04:30:13.273+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85856-530/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83cfd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:13.273+0000] {logging_mixin.py:188} INFO - Revenda AND Consultores Associados organizada com sucesso !
[2025-06-30T04:30:14.426+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/82600-130/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83c3d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:14.427+0000] {logging_mixin.py:188} INFO - Revenda APRN Soluções organizada com sucesso !
[2025-06-30T04:30:14.558+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55540-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c48e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:14.559+0000] {logging_mixin.py:188} INFO - Revenda Ary Sistemas de Gestão e Informatica (RNS) organizada com sucesso !
[2025-06-30T04:30:15.705+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/66113-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c81c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:15.706+0000] {logging_mixin.py:188} INFO - Revenda Asteqesystem organizada com sucesso !
[2025-06-30T04:30:16.857+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/76908-430/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:16.858+0000] {logging_mixin.py:188} INFO - Revenda Atrium Sistemas organizada com sucesso !
[2025-06-30T04:30:18.009+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/27265-435/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:18.010+0000] {logging_mixin.py:188} INFO - Revenda Automac Digitron organizada com sucesso !
[2025-06-30T04:30:19.161+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29900-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:19.161+0000] {logging_mixin.py:188} INFO - Revenda Automaquinas - Automação Comercial organizada com sucesso !
[2025-06-30T04:30:20.313+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/44003-198/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:20.314+0000] {logging_mixin.py:188} INFO - Revenda Autosyste Tecnologia e Inovação organizada com sucesso !
[2025-06-30T04:30:21.465+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/25515-520/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:21.466+0000] {logging_mixin.py:188} INFO - Revenda Autotech Informática organizada com sucesso !
[2025-06-30T04:30:21.597+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/22710-112/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83c310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:21.599+0000] {logging_mixin.py:188} INFO - Revenda Bellabyte organizada com sucesso !
[2025-06-30T04:30:22.745+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/68900-075/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83ccd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:22.746+0000] {logging_mixin.py:188} INFO - Revenda Bitech organizada com sucesso !
[2025-06-30T04:30:23.898+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29645-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8639a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:23.898+0000] {logging_mixin.py:188} INFO - Revenda Boldtsoft Sistemas organizada com sucesso !
[2025-06-30T04:30:25.048+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/66623-268/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:25.049+0000] {logging_mixin.py:188} INFO - Revenda BRAZ TI organizada com sucesso !
[2025-06-30T04:30:26.201+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88352-001/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83c6a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:26.202+0000] {logging_mixin.py:188} INFO - Revenda Brusoft Informatica organizada com sucesso !
[2025-06-30T04:30:27.353+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88312-260/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4610>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:27.354+0000] {logging_mixin.py:188} INFO - Revenda Brvatech organizada com sucesso !
[2025-06-30T04:30:28.505+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/70714-020/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:28.506+0000] {logging_mixin.py:188} INFO - Revenda Canal Tecnico (Lumi) organizada com sucesso !
[2025-06-30T04:30:28.636+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/57020-260/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c91c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:28.637+0000] {logging_mixin.py:188} INFO - Revenda Casa das Impressoras organizada com sucesso !
[2025-06-30T04:30:29.786+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85852-130/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c9a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:29.787+0000] {logging_mixin.py:188} INFO - Revenda CASTERS organizada com sucesso !
[2025-06-30T04:30:30.938+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55016-080/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:30.939+0000] {logging_mixin.py:188} INFO - Revenda Centec Equipamentos organizada com sucesso !
[2025-06-30T04:30:32.089+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/57442-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b8df0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:32.090+0000] {logging_mixin.py:188} INFO - Revenda CK Tech Consultoria organizada com sucesso !
[2025-06-30T04:30:33.240+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85065-420/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863a30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:33.241+0000] {logging_mixin.py:188} INFO - Revenda Compass Tecnologia da Informação organizada com sucesso !
[2025-06-30T04:30:34.393+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/38400-694/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c9640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:34.394+0000] {logging_mixin.py:188} INFO - Revenda Compucenter Software organizada com sucesso !
[2025-06-30T04:30:35.545+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/28735-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c81c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:35.546+0000] {logging_mixin.py:188} INFO - Revenda Conexão Informática Ltda organizada com sucesso !
[2025-06-30T04:30:35.677+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/57120-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:35.678+0000] {logging_mixin.py:188} INFO - Revenda Connect System Soluções em Tecnologia organizada com sucesso !
[2025-06-30T04:30:36.825+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/69047-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c9be0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:36.826+0000] {logging_mixin.py:188} INFO - Revenda Conte Certo Serviços organizada com sucesso !
[2025-06-30T04:30:37.977+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/15085-310/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:37.977+0000] {logging_mixin.py:188} INFO - Revenda Control Biz organizada com sucesso !
[2025-06-30T04:30:39.129+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55004-270/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:39.130+0000] {logging_mixin.py:188} INFO - Revenda CTi - Centro Técnico de Informática organizada com sucesso !
[2025-06-30T04:30:40.282+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21380-008/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c47f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:40.283+0000] {logging_mixin.py:188} INFO - Revenda D&A Automação Comercial organizada com sucesso !
[2025-06-30T04:30:41.434+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89228-080/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:41.434+0000] {logging_mixin.py:188} INFO - Revenda DALTEC Automacao Comercial organizada com sucesso !
[2025-06-30T04:30:41.563+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/38740-082/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:41.564+0000] {logging_mixin.py:188} INFO - Revenda DataConta Gestão de Negócios organizada com sucesso !
[2025-06-30T04:30:42.714+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89801-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c49a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:42.714+0000] {logging_mixin.py:188} INFO - Revenda Dataproxy organizada com sucesso !
[2025-06-30T04:30:43.864+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/91220-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:43.865+0000] {logging_mixin.py:188} INFO - Revenda DCODER organizada com sucesso !
[2025-06-30T04:30:45.017+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/77405-130/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c0a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:45.018+0000] {logging_mixin.py:188} INFO - Revenda D Data Soluções organizada com sucesso !
[2025-06-30T04:30:46.170+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/53421-321/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:46.171+0000] {logging_mixin.py:188} INFO - Revenda DGTEC organizada com sucesso !
[2025-06-30T04:30:47.321+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46400-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:47.322+0000] {logging_mixin.py:188} INFO - Revenda Digito Informatica organizada com sucesso !
[2025-06-30T04:30:48.473+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85060-080/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8eb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:48.474+0000] {logging_mixin.py:188} INFO - Revenda Dikoc Soluções em Software organizada com sucesso !
[2025-06-30T04:30:48.602+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/81200-150/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:48.603+0000] {logging_mixin.py:188} INFO - Revenda DMK Sistemas e Soluções - HSI organizada com sucesso !
[2025-06-30T04:30:49.754+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78635-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c9c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:49.755+0000] {logging_mixin.py:188} INFO - Revenda DMZ Informatica organizada com sucesso !
[2025-06-30T04:30:50.906+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/13843-201/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:50.906+0000] {logging_mixin.py:188} INFO - Revenda Dolphin Consultoria organizada com sucesso !
[2025-06-30T04:30:52.057+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/28913-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:52.058+0000] {logging_mixin.py:188} INFO - Revenda DSM Consultoria em T.I. organizada com sucesso !
[2025-06-30T04:30:53.209+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/79004-440/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:53.210+0000] {logging_mixin.py:188} INFO - Revenda Duall Tech organizada com sucesso !
[2025-06-30T04:30:54.361+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/41820-020/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:54.362+0000] {logging_mixin.py:188} INFO - Revenda DWH Comercio de Alimentos organizada com sucesso !
[2025-06-30T04:30:55.513+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88702-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cca90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:55.514+0000] {logging_mixin.py:188} INFO - Revenda Edcom Automação Comercial organizada com sucesso !
[2025-06-30T04:30:55.646+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/75901-630/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c49d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:55.647+0000] {logging_mixin.py:188} INFO - Revenda Eleve Tecnologia organizada com sucesso !
[2025-06-30T04:30:56.793+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88106-500/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:56.794+0000] {logging_mixin.py:188} INFO - Revenda Emlink Solucoes Empresariais organizada com sucesso !
[2025-06-30T04:30:57.945+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/64200-250/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:57.945+0000] {logging_mixin.py:188} INFO - Revenda Exatop Certificação Digital e Sistemas organizada com sucesso !
[2025-06-30T04:30:59.097+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89258-730/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:30:59.098+0000] {logging_mixin.py:188} INFO - Revenda Exodus Informática organizada com sucesso !
[2025-06-30T04:31:00.248+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89280-328/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cca90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:00.249+0000] {logging_mixin.py:188} INFO - Revenda Extrema Software de Gestão organizada com sucesso !
[2025-06-30T04:31:01.401+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/63660-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:01.402+0000] {logging_mixin.py:188} INFO - Revenda F5 Suporte e Automacão Comercial organizada com sucesso !
[2025-06-30T04:31:02.553+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/13273-410/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:02.555+0000] {logging_mixin.py:188} INFO - Revenda Facilita Sistemas organizada com sucesso !
[2025-06-30T04:31:02.686+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95670-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:02.687+0000] {logging_mixin.py:188} INFO - Revenda Facilsys organizada com sucesso !
[2025-06-30T04:31:03.834+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58808-485/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b8fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:03.835+0000] {logging_mixin.py:188} INFO - Revenda F & F Soluções Empresariais organizada com sucesso !
[2025-06-30T04:31:04.985+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88160-064/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:04.986+0000] {logging_mixin.py:188} INFO - Revenda FKSIS - Sistemas de Gestão organizada com sucesso !
[2025-06-30T04:31:06.137+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88354-610/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4ee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:06.138+0000] {logging_mixin.py:188} INFO - Revenda FlorySoftt organizada com sucesso !
[2025-06-30T04:31:07.289+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/23860-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:07.290+0000] {logging_mixin.py:188} INFO - Revenda Fn Info House organizada com sucesso !
[2025-06-30T04:31:08.441+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/63502-769/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c80a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:08.442+0000] {logging_mixin.py:188} INFO - Revenda FS Informatica organizada com sucesso !
[2025-06-30T04:31:08.571+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/84320-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:08.572+0000] {logging_mixin.py:188} INFO - Revenda Fusion Sistemas e Informatica organizada com sucesso !
[2025-06-30T04:31:09.721+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59900-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c41c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:09.721+0000] {logging_mixin.py:188} INFO - Revenda Gilmaq Automação Comercial organizada com sucesso !
[2025-06-30T04:31:10.873+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55825-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc7f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:10.874+0000] {logging_mixin.py:188} INFO - Revenda GM Soluções em Informática organizada com sucesso !
[2025-06-30T04:31:12.025+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/01311-927/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:12.025+0000] {logging_mixin.py:188} INFO - Revenda Grupo GUUW organizada com sucesso !
[2025-06-30T04:31:13.178+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37800-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:13.179+0000] {logging_mixin.py:188} INFO - Revenda Guaxutec organizada com sucesso !
[2025-06-30T04:31:14.329+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88508-190/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863910>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:14.330+0000] {logging_mixin.py:188} INFO - Revenda HSI Automação Comercial organizada com sucesso !
[2025-06-30T04:31:15.481+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/20756-100/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:15.481+0000] {logging_mixin.py:188} INFO - Revenda HWC Soluções organizada com sucesso !
[2025-06-30T04:31:15.610+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59500-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:15.611+0000] {logging_mixin.py:188} INFO - Revenda I7 Automação Comercial organizada com sucesso !
[2025-06-30T04:31:16.761+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29280-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:16.762+0000] {logging_mixin.py:188} INFO - Revenda Ideal Soluções Empresariais organizada com sucesso !
[2025-06-30T04:31:17.913+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59570-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc2b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:17.913+0000] {logging_mixin.py:188} INFO - Revenda ID Tecnologia organizada com sucesso !
[2025-06-30T04:31:19.066+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/06454-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:19.067+0000] {logging_mixin.py:188} INFO - Revenda IFFI Soluções organizada com sucesso !
[2025-06-30T04:31:20.217+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/69980-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:20.218+0000] {logging_mixin.py:188} INFO - Revenda IG TEC organizada com sucesso !
[2025-06-30T04:31:21.369+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58900-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8c10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:21.371+0000] {logging_mixin.py:188} INFO - Revenda INFOPRINTER organizada com sucesso !
[2025-06-30T04:31:22.521+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21011-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:22.522+0000] {logging_mixin.py:188} INFO - Revenda INFORMIT organizada com sucesso !
[2025-06-30T04:31:22.650+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/69303-045/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7ccc10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:22.651+0000] {logging_mixin.py:188} INFO - Revenda Infor Serviços organizada com sucesso !
[2025-06-30T04:31:23.804+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/48601-270/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:23.806+0000] {logging_mixin.py:188} INFO - Revenda Infortec Automacao Comercial organizada com sucesso !
[2025-06-30T04:31:24.954+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46430-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:24.955+0000] {logging_mixin.py:188} INFO - Revenda Infotek organizada com sucesso !
[2025-06-30T04:31:26.104+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/26535-190/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8634f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:26.105+0000] {logging_mixin.py:188} INFO - Revenda Innovati Tecnologia (INW Store) organizada com sucesso !
[2025-06-30T04:31:27.255+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50865-090/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8a00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:27.256+0000] {logging_mixin.py:188} INFO - Revenda Inova Software organizada com sucesso !
[2025-06-30T04:31:28.407+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55130-970/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c84f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:28.408+0000] {logging_mixin.py:188} INFO - Revenda Inspire Consult & Informatica  organizada com sucesso !
[2025-06-30T04:31:29.561+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89801-106/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8636a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:29.562+0000] {logging_mixin.py:188} INFO - Revenda Inteltix Tecnologia (Center) organizada com sucesso !
[2025-06-30T04:31:29.690+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/79823-290/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c1f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:29.691+0000] {logging_mixin.py:188} INFO - Revenda J7 Automação Comercial - System HD organizada com sucesso !
[2025-06-30T04:31:30.841+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78360-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:30.842+0000] {logging_mixin.py:188} INFO - Revenda Jann Informatica organizada com sucesso !
[2025-06-30T04:31:31.993+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/76997-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7ccb20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:31.994+0000] {logging_mixin.py:188} INFO - Revenda JB Tecnologia organizada com sucesso !
[2025-06-30T04:31:33.145+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/68460-245/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c41f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:33.146+0000] {logging_mixin.py:188} INFO - Revenda J & E Soluções organizada com sucesso !
[2025-06-30T04:31:34.298+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46430-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d84f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:34.299+0000] {logging_mixin.py:188} INFO - Revenda JExpress organizada com sucesso !
[2025-06-30T04:31:35.448+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58077-062/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cc9d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:35.449+0000] {logging_mixin.py:188} INFO - Revenda J F Soluções Informatica organizada com sucesso !
[2025-06-30T04:31:35.579+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/69058-580/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cca30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:35.580+0000] {logging_mixin.py:188} INFO - Revenda J F Tech Tecnologia & Sistemas organizada com sucesso !
[2025-06-30T04:31:36.729+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/31255-780/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7013da4070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:36.730+0000] {logging_mixin.py:188} INFO - Revenda JHLS Automação Comercial organizada com sucesso !
[2025-06-30T04:31:37.883+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/12914-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:37.884+0000] {logging_mixin.py:188} INFO - Revenda Jinsei Contabilidade organizada com sucesso !
[2025-06-30T04:31:39.032+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/27197-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8af0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:39.032+0000] {logging_mixin.py:188} INFO - Revenda JJ Serviços organizada com sucesso !
[2025-06-30T04:31:40.186+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/49055-620/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d8070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:40.187+0000] {logging_mixin.py:188} INFO - Revenda JM Informatica organizada com sucesso !
[2025-06-30T04:31:41.337+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89220-110/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:41.337+0000] {logging_mixin.py:188} INFO - Revenda JP Automação Comercial organizada com sucesso !
[2025-06-30T04:31:42.490+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78250-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84cd60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:42.491+0000] {logging_mixin.py:188} INFO - Revenda JSR Automação Comercial  organizada com sucesso !
[2025-06-30T04:31:42.620+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89700-166/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c89a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:42.620+0000] {logging_mixin.py:188} INFO - Revenda Kernel Sistemas organizada com sucesso !
[2025-06-30T04:31:43.769+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/14010-180/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:43.770+0000] {logging_mixin.py:188} INFO - Revenda KMCI Tecnologia em Automação organizada com sucesso !
[2025-06-30T04:31:44.921+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/25555-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:44.922+0000] {logging_mixin.py:188} INFO - Revenda Komputronic do Brasil organizada com sucesso !
[2025-06-30T04:31:46.074+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29052-170/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:46.075+0000] {logging_mixin.py:188} INFO - Revenda KSC Sistemas organizada com sucesso !
[2025-06-30T04:31:47.225+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50010-100/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:47.226+0000] {logging_mixin.py:188} INFO - Revenda L&D Comercio e Tecnologia organizada com sucesso !
[2025-06-30T04:31:48.376+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/25935-530/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:48.377+0000] {logging_mixin.py:188} INFO - Revenda LD Tech organizada com sucesso !
[2025-06-30T04:31:49.528+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29375-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c0a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:49.529+0000] {logging_mixin.py:188} INFO - Revenda LF Sistemas organizada com sucesso !
[2025-06-30T04:31:49.658+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/39400-215/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:49.658+0000] {logging_mixin.py:188} INFO - Revenda LiderTech organizada com sucesso !
[2025-06-30T04:31:50.809+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/93700-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d85b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:50.810+0000] {logging_mixin.py:188} INFO - Revenda Life Sistemas  organizada com sucesso !
[2025-06-30T04:31:51.959+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/20250-450/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83d1f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:51.959+0000] {logging_mixin.py:188} INFO - Revenda LL Tecnologia organizada com sucesso !
[2025-06-30T04:31:53.113+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/36884-004/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83da90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:53.113+0000] {logging_mixin.py:188} INFO - Revenda LMD Sistemas organizada com sucesso !
[2025-06-30T04:31:54.265+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/22730-001/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863b80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:54.266+0000] {logging_mixin.py:188} INFO - Revenda Logitec 2000 Informatica organizada com sucesso !
[2025-06-30T04:31:55.417+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37470-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8a9c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:55.418+0000] {logging_mixin.py:188} INFO - Revenda Macmos organizada com sucesso !
[2025-06-30T04:31:55.548+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59300-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:55.549+0000] {logging_mixin.py:188} INFO - Revenda Mape Informatica organizada com sucesso !
[2025-06-30T04:31:56.697+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89900-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:56.697+0000] {logging_mixin.py:188} INFO - Revenda Marcka Informática e Sistemas organizada com sucesso !
[2025-06-30T04:31:57.851+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58041-070/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83d790>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:57.852+0000] {logging_mixin.py:188} INFO - Revenda Matechinfo organizada com sucesso !
[2025-06-30T04:31:59.001+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88355-393/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d8f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:31:59.002+0000] {logging_mixin.py:188} INFO - Revenda MB Tecnologia organizada com sucesso !
[2025-06-30T04:32:00.154+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/82015-520/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d8400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:00.154+0000] {logging_mixin.py:188} INFO - Revenda MC2 Tecnologia organizada com sucesso !
[2025-06-30T04:32:01.306+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89562-180/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:01.306+0000] {logging_mixin.py:188} INFO - Revenda MCR Sistemas (RS-AMX) organizada com sucesso !
[2025-06-30T04:32:02.458+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21660-060/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b86d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:02.458+0000] {logging_mixin.py:188} INFO - Revenda MD Tech Automação organizada com sucesso !
[2025-06-30T04:32:02.591+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46430-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83d310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:02.592+0000] {logging_mixin.py:188} INFO - Revenda Megasoft Informatica organizada com sucesso !
[2025-06-30T04:32:03.737+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95270-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83deb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:03.738+0000] {logging_mixin.py:188} INFO - Revenda Mercantec Soluções organizada com sucesso !
[2025-06-30T04:32:04.889+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88310-661/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:04.890+0000] {logging_mixin.py:188} INFO - Revenda Mikrox "Somadatta" organizada com sucesso !
[2025-06-30T04:32:06.041+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/63010-127/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d8a00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:06.042+0000] {logging_mixin.py:188} INFO - Revenda M. Nobre (Terabyte) organizada com sucesso !
[2025-06-30T04:32:07.193+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/32310-210/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:07.194+0000] {logging_mixin.py:188} INFO - Revenda MRsis Automação organizada com sucesso !
[2025-06-30T04:32:08.346+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37062-170/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:08.347+0000] {logging_mixin.py:188} INFO - Revenda M&R Soluções - Grupo ATL organizada com sucesso !
[2025-06-30T04:32:09.497+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/47640-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:09.498+0000] {logging_mixin.py:188} INFO - Revenda Multi Soft organizada com sucesso !
[2025-06-30T04:32:09.627+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78390-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c45b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:09.628+0000] {logging_mixin.py:188} INFO - Revenda NewCompras.com.br organizada com sucesso !
[2025-06-30T04:32:10.777+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/67030-080/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d8ee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:10.778+0000] {logging_mixin.py:188} INFO - Revenda NEWTEF Automação organizada com sucesso !
[2025-06-30T04:32:11.929+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50960-400/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83d220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:11.930+0000] {logging_mixin.py:188} INFO - Revenda Next Store organizada com sucesso !
[2025-06-30T04:32:13.081+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37730-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83dac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:13.082+0000] {logging_mixin.py:188} INFO - Revenda Nova Loja organizada com sucesso !
[2025-06-30T04:32:14.233+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/17210-420/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:14.234+0000] {logging_mixin.py:188} INFO - Revenda NovaPC organizada com sucesso !
[2025-06-30T04:32:15.385+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/39400-163/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b87c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:15.385+0000] {logging_mixin.py:188} INFO - Revenda Optimus - Gestão organizada com sucesso !
[2025-06-30T04:32:16.538+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/98803-412/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d8820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:16.539+0000] {logging_mixin.py:188} INFO - Revenda Otimizer Consultoria em Sistemas organizada com sucesso !
[2025-06-30T04:32:16.667+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/62500-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d82e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:16.668+0000] {logging_mixin.py:188} INFO - Revenda Otimize Soluções organizada com sucesso !
[2025-06-30T04:32:17.816+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95034-160/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:17.816+0000] {logging_mixin.py:188} INFO - Revenda P21 Software organizada com sucesso !
[2025-06-30T04:32:18.967+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50980-480/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83d190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:18.968+0000] {logging_mixin.py:188} INFO - Revenda PALM Soluções organizada com sucesso !
[2025-06-30T04:32:20.121+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/84040-010/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:20.122+0000] {logging_mixin.py:188} INFO - Revenda Parceria Informatica organizada com sucesso !
[2025-06-30T04:32:21.273+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88330-725/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d80d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:21.274+0000] {logging_mixin.py:188} INFO - Revenda PDV Automação organizada com sucesso !
[2025-06-30T04:32:22.425+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/38700-001/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d8a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:22.426+0000] {logging_mixin.py:188} INFO - Revenda PEG Informatica organizada com sucesso !
[2025-06-30T04:32:22.556+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95200-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:22.557+0000] {logging_mixin.py:188} INFO - Revenda Piramide Automação e Informatica organizada com sucesso !
[2025-06-30T04:32:23.705+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/70314-900/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4d00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:23.706+0000] {logging_mixin.py:188} INFO - Revenda Plus Solutions organizada com sucesso !
[2025-06-30T04:32:24.857+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88350-564/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:24.858+0000] {logging_mixin.py:188} INFO - Revenda Ponte organizada com sucesso !
[2025-06-30T04:32:26.009+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29700-550/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8203a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:26.010+0000] {logging_mixin.py:188} INFO - Revenda Pratic Informática organizada com sucesso !
[2025-06-30T04:32:27.161+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/65930-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:27.162+0000] {logging_mixin.py:188} INFO - Revenda PROFISC - Consultoria  organizada com sucesso !
[2025-06-30T04:32:28.314+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws//json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:28.315+0000] {logging_mixin.py:188} INFO - Revenda Pryamos organizada com sucesso !
[2025-06-30T04:32:29.465+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46380-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d8160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:29.466+0000] {logging_mixin.py:188} INFO - Revenda Quality Automação e Recargas organizada com sucesso !
[2025-06-30T04:32:29.594+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/76963-586/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d8f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:29.595+0000] {logging_mixin.py:188} INFO - Revenda Rafah Soluções em Sistema organizada com sucesso !
[2025-06-30T04:32:30.745+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89803-460/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863d90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:30.746+0000] {logging_mixin.py:188} INFO - Revenda RC Automação organizada com sucesso !
[2025-06-30T04:32:31.897+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/05761-340/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863d00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:31.899+0000] {logging_mixin.py:188} INFO - Revenda RCM Tecnologia organizada com sucesso !
[2025-06-30T04:32:33.050+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/15910-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863e80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:33.051+0000] {logging_mixin.py:188} INFO - Revenda RedeEllo organizada com sucesso !
[2025-06-30T04:32:34.201+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/56310-130/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8636a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:34.202+0000] {logging_mixin.py:188} INFO - Revenda Rieger Consultoria e Serviços  organizada com sucesso !
[2025-06-30T04:32:35.353+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88104-435/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d8df0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:35.354+0000] {logging_mixin.py:188} INFO - Revenda RKS Tecnologia organizada com sucesso !
[2025-06-30T04:32:36.505+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/76960-046/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84ce20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:36.506+0000] {logging_mixin.py:188} INFO - Revenda Rondoniatec Sistemas e Soluções organizada com sucesso !
[2025-06-30T04:32:36.635+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/48602-005/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:36.636+0000] {logging_mixin.py:188} INFO - Revenda Royal Ti organizada com sucesso !
[2025-06-30T04:32:37.786+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/28895-320/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:37.786+0000] {logging_mixin.py:188} INFO - Revenda RPD Tech Soluções em T.I. organizada com sucesso !
[2025-06-30T04:32:38.937+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/87970-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83df40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:38.938+0000] {logging_mixin.py:188} INFO - Revenda RPDV Soluções em Tecnologia organizada com sucesso !
[2025-06-30T04:32:40.090+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55825-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c49a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:40.091+0000] {logging_mixin.py:188} INFO - Revenda RS Informatica organizada com sucesso !
[2025-06-30T04:32:41.240+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/31270-350/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c1f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:41.240+0000] {logging_mixin.py:188} INFO - Revenda Rtek organizada com sucesso !
[2025-06-30T04:32:42.393+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89204-050/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d8ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:42.393+0000] {logging_mixin.py:188} INFO - Revenda SDN Sistemas de Gestão organizada com sucesso !
[2025-06-30T04:32:43.544+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/12914-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d8e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:43.545+0000] {logging_mixin.py:188} INFO - Revenda Seed Tecnologia organizada com sucesso !
[2025-06-30T04:32:43.676+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29560-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863c70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:43.676+0000] {logging_mixin.py:188} INFO - Revenda Shopseg Sistemas organizada com sucesso !
[2025-06-30T04:32:44.825+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88350-100/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8203a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:44.825+0000] {logging_mixin.py:188} INFO - Revenda Sig Sistemas Corporativos organizada com sucesso !
[2025-06-30T04:32:45.977+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/63034-150/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:45.978+0000] {logging_mixin.py:188} INFO - Revenda Sistech Sistemas organizada com sucesso !
[2025-06-30T04:32:47.129+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88350-270/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:47.130+0000] {logging_mixin.py:188} INFO - Revenda Sistema Completo organizada com sucesso !
[2025-06-30T04:32:48.281+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/45028-190/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d8df0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:48.282+0000] {logging_mixin.py:188} INFO - Revenda Sistema Uniplus - Vitória da Conquista organizada com sucesso !
[2025-06-30T04:32:49.432+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/39680-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:49.433+0000] {logging_mixin.py:188} INFO - Revenda Skill Automação Comercial organizada com sucesso !
[2025-06-30T04:32:49.562+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88130-650/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:49.563+0000] {logging_mixin.py:188} INFO - Revenda SM10 Sistemas de Gestão e Automação Comercial  (AM10) organizada com sucesso !
[2025-06-30T04:32:50.713+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/79540-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4c70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:50.714+0000] {logging_mixin.py:188} INFO - Revenda Smith Tecnologias organizada com sucesso !
[2025-06-30T04:32:51.867+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50720-090/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:51.868+0000] {logging_mixin.py:188} INFO - Revenda SMQ Tecnologia organizada com sucesso !
[2025-06-30T04:32:53.017+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/44061-070/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4af0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:53.018+0000] {logging_mixin.py:188} INFO - Revenda Softech Tecnologia organizada com sucesso !
[2025-06-30T04:32:54.169+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/62011-205/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84cd30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:54.170+0000] {logging_mixin.py:188} INFO - Revenda SoftGadol organizada com sucesso !
[2025-06-30T04:32:55.321+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/60822-305/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d8ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:55.322+0000] {logging_mixin.py:188} INFO - Revenda Softkore organizada com sucesso !
[2025-06-30T04:32:56.474+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/27920-325/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8a9c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:56.475+0000] {logging_mixin.py:188} INFO - Revenda Softmaq Tecnologia organizada com sucesso !
[2025-06-30T04:32:56.606+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58500-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863c10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:56.606+0000] {logging_mixin.py:188} INFO - Revenda Softpollus organizada com sucesso !
[2025-06-30T04:32:57.752+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/61655-590/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8204c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:57.753+0000] {logging_mixin.py:188} INFO - Revenda Solem Tecnologia organizada com sucesso !
[2025-06-30T04:32:58.905+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95700-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:32:58.905+0000] {logging_mixin.py:188} INFO - Revenda Sonaglio Automação organizada com sucesso !
[2025-06-30T04:33:00.058+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50720-715/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:00.059+0000] {logging_mixin.py:188} INFO - Revenda Sonsun organizada com sucesso !
[2025-06-30T04:33:01.212+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50721-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820790>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:01.213+0000] {logging_mixin.py:188} INFO - Revenda Sophos Projetos organizada com sucesso !
[2025-06-30T04:33:02.361+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/99260-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:02.362+0000] {logging_mixin.py:188} INFO - Revenda Sparta Gestão e Contabilidade - DEOCLESYSTEM organizada com sucesso !
[2025-06-30T04:33:03.514+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37470-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4e20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:03.515+0000] {logging_mixin.py:188} INFO - Revenda Speed Automação Comercial organizada com sucesso !
[2025-06-30T04:33:03.645+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46400-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:03.646+0000] {logging_mixin.py:188} INFO - Revenda SS Informatica - Bahia organizada com sucesso !
[2025-06-30T04:33:04.793+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/65070-280/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:04.794+0000] {logging_mixin.py:188} INFO - Revenda SS Informática - Maranhão organizada com sucesso !
[2025-06-30T04:33:05.945+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59607-340/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c45b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:05.946+0000] {logging_mixin.py:188} INFO - Revenda Syscom Sistemas organizada com sucesso !
[2025-06-30T04:33:07.098+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/45075-290/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b8a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:07.099+0000] {logging_mixin.py:188} INFO - Revenda SYSFOUR - Intelligent Systems organizada com sucesso !
[2025-06-30T04:33:08.249+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89295-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:08.250+0000] {logging_mixin.py:188} INFO - Revenda System Bella Automação Comercial organizada com sucesso !
[2025-06-30T04:33:09.401+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89801-570/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c81c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:09.402+0000] {logging_mixin.py:188} INFO - Revenda TB Automação e Informática organizada com sucesso !
[2025-06-30T04:33:10.554+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59031-170/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:10.555+0000] {logging_mixin.py:188} INFO - Revenda TC Maquinas organizada com sucesso !
[2025-06-30T04:33:10.686+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/60750-030/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:10.687+0000] {logging_mixin.py:188} INFO - Revenda Technoside Informatica organizada com sucesso !
[2025-06-30T04:33:11.836+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/65800-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8209d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:11.837+0000] {logging_mixin.py:188} INFO - Revenda Tecmicro Informática organizada com sucesso !
[2025-06-30T04:33:12.986+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/79004-460/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8637f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:12.986+0000] {logging_mixin.py:188} INFO - Revenda Tecnoinfo organizada com sucesso !
[2025-06-30T04:33:14.138+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/68525-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:14.139+0000] {logging_mixin.py:188} INFO - Revenda TECSOLUTION organizada com sucesso !
[2025-06-30T04:33:15.289+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29050-565/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b87f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:15.290+0000] {logging_mixin.py:188} INFO - Revenda Tefcom organizada com sucesso !
[2025-06-30T04:33:16.442+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/68909-845/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:16.442+0000] {logging_mixin.py:188} INFO - Revenda TFA Tecnologia e Soluções  organizada com sucesso !
[2025-06-30T04:33:16.572+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95020-520/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d4220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:16.572+0000] {logging_mixin.py:188} INFO - Revenda TI-Brasil Sistemas organizada com sucesso !
[2025-06-30T04:33:17.722+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95084-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d4ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:17.723+0000] {logging_mixin.py:188} INFO - Revenda Trends Solutions organizada com sucesso !
[2025-06-30T04:33:18.874+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/67013-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:18.875+0000] {logging_mixin.py:188} INFO - Revenda TS TECH organizada com sucesso !
[2025-06-30T04:33:20.025+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89560-132/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b8dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:20.026+0000] {logging_mixin.py:188} INFO - Revenda Unisoft Sistemas ** Hardtech organizada com sucesso !
[2025-06-30T04:33:21.176+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88070-770/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8639a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:21.177+0000] {logging_mixin.py:188} INFO - Revenda Unitek Soluções organizada com sucesso !
[2025-06-30T04:33:22.329+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/20040-030/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d41c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:22.330+0000] {logging_mixin.py:188} INFO - Revenda Uniup Sistema - Automação e CFTV organizada com sucesso !
[2025-06-30T04:33:23.481+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89222-363/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:23.482+0000] {logging_mixin.py:188} INFO - Revenda Universal Automação Comercial  organizada com sucesso !
[2025-06-30T04:33:23.613+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78550-104/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:23.613+0000] {logging_mixin.py:188} INFO - Revenda Universo Sistemas organizada com sucesso !
[2025-06-30T04:33:24.761+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89620-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d4d00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:24.762+0000] {logging_mixin.py:188} INFO - Revenda Valor Tecnologia organizada com sucesso !
[2025-06-30T04:33:25.913+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/98700-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863b80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:25.914+0000] {logging_mixin.py:188} INFO - Revenda VGI TECHNOLOGY organizada com sucesso !
[2025-06-30T04:33:27.065+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/87504-480/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84c640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:27.066+0000] {logging_mixin.py:188} INFO - Revenda Via Nova Soluções em Tecnologia organizada com sucesso !
[2025-06-30T04:33:28.217+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37890-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:28.218+0000] {logging_mixin.py:188} INFO - Revenda Virtual Informatica_MG organizada com sucesso !
[2025-06-30T04:33:29.370+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89136-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c49a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:29.370+0000] {logging_mixin.py:188} INFO - Revenda Virtual Sistemas_SC organizada com sucesso !
[2025-06-30T04:33:30.521+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/26260-580/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8205b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:30.522+0000] {logging_mixin.py:188} INFO - Revenda VPN Solucoes em Informatica organizada com sucesso !
[2025-06-30T04:33:30.657+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89245-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c83d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:30.658+0000] {logging_mixin.py:188} INFO - Revenda Vzan Automação Comercial organizada com sucesso !
[2025-06-30T04:33:31.802+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21532-460/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c45e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:31.802+0000] {logging_mixin.py:188} INFO - Revenda Walltech Informatica organizada com sucesso !
[2025-06-30T04:33:32.953+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29103-240/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b87f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:32.954+0000] {logging_mixin.py:188} INFO - Revenda W C Sistemas organizada com sucesso !
[2025-06-30T04:33:34.105+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/06280-150/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d863b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:34.105+0000] {logging_mixin.py:188} INFO - Revenda WGE informatica organizada com sucesso !
[2025-06-30T04:33:35.257+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/31080-365/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:35.257+0000] {logging_mixin.py:188} INFO - Revenda WMX Soluções em Tecnologia organizada com sucesso !
[2025-06-30T04:33:36.409+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/30710-580/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d820ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-30T04:33:36.410+0000] {logging_mixin.py:188} INFO - Revenda X1 Automação organizada com sucesso !
[2025-06-30T04:33:36.544+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-30T04:33:36.564+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=DAG_atualizacao_cadastral_revendas, task_id=organized_response_database, execution_date=20250629T043000, start_date=20250630T043004, end_date=20250630T043336
[2025-06-30T04:33:36.664+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-30T04:33:36.701+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
