[2025-06-25T04:30:06.629+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_atualizacao_cadastral_revendas.organized_response_database scheduled__2025-06-24T04:30:00+00:00 [queued]>
[2025-06-25T04:30:06.645+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_atualizacao_cadastral_revendas.organized_response_database scheduled__2025-06-24T04:30:00+00:00 [queued]>
[2025-06-25T04:30:06.645+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-25T04:30:06.763+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): organized_response_database> on 2025-06-24 04:30:00+00:00
[2025-06-25T04:30:06.771+0000] {standard_task_runner.py:60} INFO - Started process 229676 to run task
[2025-06-25T04:30:06.777+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'DAG_atualizacao_cadastral_revendas', 'organized_response_database', 'scheduled__2025-06-24T04:30:00+00:00', '--job-id', '230', '--raw', '--subdir', 'DAGS_FOLDER/DagDatasetComercial.py', '--cfg-path', '/tmp/tmp61i5qlil']
[2025-06-25T04:30:06.779+0000] {standard_task_runner.py:88} INFO - Job 230: Subtask organized_response_database
[2025-06-25T04:30:06.895+0000] {task_command.py:423} INFO - Running <TaskInstance: DAG_atualizacao_cadastral_revendas.organized_response_database scheduled__2025-06-24T04:30:00+00:00 [running]> on host 99f5714845f7
[2025-06-25T04:30:07.142+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_atualizacao_cadastral_revendas' AIRFLOW_CTX_TASK_ID='organized_response_database' AIRFLOW_CTX_EXECUTION_DATE='2025-06-24T04:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-24T04:30:00+00:00'
[2025-06-25T04:30:07.514+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/75620-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8625b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:07.574+0000] {logging_mixin.py:188} INFO - Revenda A7 Soluções organizada com sucesso !
[2025-06-25T04:30:07.702+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/80540-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:07.703+0000] {logging_mixin.py:188} INFO - Revenda AB Soluções em TI organizada com sucesso !
[2025-06-25T04:30:07.833+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21070-032/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82d730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:07.834+0000] {logging_mixin.py:188} INFO - Revenda Adonai Automação Comercial organizada com sucesso !
[2025-06-25T04:30:07.963+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/39801-240/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82dfd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:07.963+0000] {logging_mixin.py:188} INFO - Revenda ADV SIG organizada com sucesso !
[2025-06-25T04:30:08.117+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88400-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82ddf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:08.118+0000] {logging_mixin.py:188} INFO - Revenda A e A Dist. de Informática - Softart organizada com sucesso !
[2025-06-25T04:30:08.247+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21235-604/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d82d610>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:08.248+0000] {logging_mixin.py:188} INFO - Revenda Af Suporte organizada com sucesso !
[2025-06-25T04:30:09.433+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/60115-222/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:09.434+0000] {logging_mixin.py:188} INFO - Revenda Agedata Sistemas organizada com sucesso !
[2025-06-25T04:30:09.563+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78130-435/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:09.564+0000] {logging_mixin.py:188} INFO - Revenda AIO Solucoes organizada com sucesso !
[2025-06-25T04:30:10.841+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37701-706/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83b8b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:10.842+0000] {logging_mixin.py:188} INFO - Revenda AllTecInfo organizada com sucesso !
[2025-06-25T04:30:11.994+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78460-606/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:11.995+0000] {logging_mixin.py:188} INFO - Revenda Alpha Systemas e informática organizada com sucesso !
[2025-06-25T04:30:13.146+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85857-270/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8624c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:13.147+0000] {logging_mixin.py:188} INFO - Revenda Alternativa Automação Comercial organizada com sucesso !
[2025-06-25T04:30:14.296+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78575-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862df0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:14.297+0000] {logging_mixin.py:188} INFO - Revenda Amigo do Micro organizada com sucesso !
[2025-06-25T04:30:15.449+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85856-530/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83bee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:15.449+0000] {logging_mixin.py:188} INFO - Revenda AND Consultores Associados organizada com sucesso !
[2025-06-25T04:30:15.578+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/82600-130/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83b370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:15.579+0000] {logging_mixin.py:188} INFO - Revenda APRN Soluções organizada com sucesso !
[2025-06-25T04:30:16.729+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55540-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c28b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:16.730+0000] {logging_mixin.py:188} INFO - Revenda Ary Sistemas de Gestão e Informatica (RNS) organizada com sucesso !
[2025-06-25T04:30:17.882+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/66113-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c6190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:17.882+0000] {logging_mixin.py:188} INFO - Revenda Asteqesystem organizada com sucesso !
[2025-06-25T04:30:19.034+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/76908-430/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c6a30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:19.035+0000] {logging_mixin.py:188} INFO - Revenda Atrium Sistemas organizada com sucesso !
[2025-06-25T04:30:20.185+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/27265-435/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:20.186+0000] {logging_mixin.py:188} INFO - Revenda Automac Digitron organizada com sucesso !
[2025-06-25T04:30:21.337+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29900-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c24f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:21.337+0000] {logging_mixin.py:188} INFO - Revenda Automaquinas - Automação Comercial organizada com sucesso !
[2025-06-25T04:30:22.490+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/44003-198/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:22.491+0000] {logging_mixin.py:188} INFO - Revenda Autosyste Tecnologia e Inovação organizada com sucesso !
[2025-06-25T04:30:22.622+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/25515-520/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c6610>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:22.623+0000] {logging_mixin.py:188} INFO - Revenda Autotech Informática organizada com sucesso !
[2025-06-25T04:30:23.770+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/22710-112/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83b190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:23.771+0000] {logging_mixin.py:188} INFO - Revenda Bellabyte organizada com sucesso !
[2025-06-25T04:30:24.921+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/68900-075/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83ba30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:24.922+0000] {logging_mixin.py:188} INFO - Revenda Bitech organizada com sucesso !
[2025-06-25T04:30:26.073+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29645-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8629d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:26.073+0000] {logging_mixin.py:188} INFO - Revenda Boldtsoft Sistemas organizada com sucesso !
[2025-06-25T04:30:27.226+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/66623-268/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84bd30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:27.227+0000] {logging_mixin.py:188} INFO - Revenda BRAZ TI organizada com sucesso !
[2025-06-25T04:30:28.377+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88352-001/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83b910>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:28.378+0000] {logging_mixin.py:188} INFO - Revenda Brusoft Informatica organizada com sucesso !
[2025-06-25T04:30:28.507+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88312-260/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83bfd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:28.508+0000] {logging_mixin.py:188} INFO - Revenda Brvatech organizada com sucesso !
[2025-06-25T04:30:29.657+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/70714-020/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c88b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:29.658+0000] {logging_mixin.py:188} INFO - Revenda Canal Tecnico (Lumi) organizada com sucesso !
[2025-06-25T04:30:30.809+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/57020-260/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:30.810+0000] {logging_mixin.py:188} INFO - Revenda Casa das Impressoras organizada com sucesso !
[2025-06-25T04:30:31.963+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85852-130/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:31.963+0000] {logging_mixin.py:188} INFO - Revenda CASTERS organizada com sucesso !
[2025-06-25T04:30:33.121+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55016-080/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c88e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:33.122+0000] {logging_mixin.py:188} INFO - Revenda Centec Equipamentos organizada com sucesso !
[2025-06-25T04:30:34.270+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/57442-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b7dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:34.270+0000] {logging_mixin.py:188} INFO - Revenda CK Tech Consultoria organizada com sucesso !
[2025-06-25T04:30:35.417+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85065-420/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862d90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:35.418+0000] {logging_mixin.py:188} INFO - Revenda Compass Tecnologia da Informação organizada com sucesso !
[2025-06-25T04:30:35.546+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/38400-694/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c29d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:35.546+0000] {logging_mixin.py:188} INFO - Revenda Compucenter Software organizada com sucesso !
[2025-06-25T04:30:36.698+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/28735-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:36.699+0000] {logging_mixin.py:188} INFO - Revenda Conexão Informática Ltda organizada com sucesso !
[2025-06-25T04:30:37.850+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/57120-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4a30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:37.851+0000] {logging_mixin.py:188} INFO - Revenda Connect System Soluções em Tecnologia organizada com sucesso !
[2025-06-25T04:30:39.002+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/69047-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:39.002+0000] {logging_mixin.py:188} INFO - Revenda Conte Certo Serviços organizada com sucesso !
[2025-06-25T04:30:40.154+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/15085-310/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862910>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:40.155+0000] {logging_mixin.py:188} INFO - Revenda Control Biz organizada com sucesso !
[2025-06-25T04:30:41.306+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55004-270/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:41.307+0000] {logging_mixin.py:188} INFO - Revenda CTi - Centro Técnico de Informática organizada com sucesso !
[2025-06-25T04:30:42.457+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21380-008/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:42.457+0000] {logging_mixin.py:188} INFO - Revenda D&A Automação Comercial organizada com sucesso !
[2025-06-25T04:30:42.586+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89228-080/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8e20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:42.587+0000] {logging_mixin.py:188} INFO - Revenda DALTEC Automacao Comercial organizada com sucesso !
[2025-06-25T04:30:43.736+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/38740-082/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:43.737+0000] {logging_mixin.py:188} INFO - Revenda DataConta Gestão de Negócios organizada com sucesso !
[2025-06-25T04:30:44.890+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89801-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:44.891+0000] {logging_mixin.py:188} INFO - Revenda Dataproxy organizada com sucesso !
[2025-06-25T04:30:46.040+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/91220-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:46.041+0000] {logging_mixin.py:188} INFO - Revenda DCODER organizada com sucesso !
[2025-06-25T04:30:47.195+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/77405-130/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:47.196+0000] {logging_mixin.py:188} INFO - Revenda D Data Soluções organizada com sucesso !
[2025-06-25T04:30:48.344+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/53421-321/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:48.345+0000] {logging_mixin.py:188} INFO - Revenda DGTEC organizada com sucesso !
[2025-06-25T04:30:49.498+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46400-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:49.498+0000] {logging_mixin.py:188} INFO - Revenda Digito Informatica organizada com sucesso !
[2025-06-25T04:30:49.630+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/85060-080/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4e80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:49.631+0000] {logging_mixin.py:188} INFO - Revenda Dikoc Soluções em Software organizada com sucesso !
[2025-06-25T04:30:50.777+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/81200-150/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cb340>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:50.778+0000] {logging_mixin.py:188} INFO - Revenda DMK Sistemas e Soluções - HSI organizada com sucesso !
[2025-06-25T04:30:51.929+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78635-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c2a30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:51.930+0000] {logging_mixin.py:188} INFO - Revenda DMZ Informatica organizada com sucesso !
[2025-06-25T04:30:53.080+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/13843-201/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:53.081+0000] {logging_mixin.py:188} INFO - Revenda Dolphin Consultoria organizada com sucesso !
[2025-06-25T04:30:54.233+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/28913-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84bd00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:54.233+0000] {logging_mixin.py:188} INFO - Revenda DSM Consultoria em T.I. organizada com sucesso !
[2025-06-25T04:30:55.385+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/79004-440/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8bb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:55.386+0000] {logging_mixin.py:188} INFO - Revenda Duall Tech organizada com sucesso !
[2025-06-25T04:30:55.515+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/41820-020/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:55.516+0000] {logging_mixin.py:188} INFO - Revenda DWH Comercio de Alimentos organizada com sucesso !
[2025-06-25T04:30:56.665+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88702-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cba60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:56.666+0000] {logging_mixin.py:188} INFO - Revenda Edcom Automação Comercial organizada com sucesso !
[2025-06-25T04:30:57.816+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/75901-630/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:57.817+0000] {logging_mixin.py:188} INFO - Revenda Eleve Tecnologia organizada com sucesso !
[2025-06-25T04:30:58.969+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88106-500/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c83d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:30:58.969+0000] {logging_mixin.py:188} INFO - Revenda Emlink Solucoes Empresariais organizada com sucesso !
[2025-06-25T04:31:00.121+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/64200-250/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b0d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:00.122+0000] {logging_mixin.py:188} INFO - Revenda Exatop Certificação Digital e Sistemas organizada com sucesso !
[2025-06-25T04:31:01.281+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89258-730/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862e20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:01.282+0000] {logging_mixin.py:188} INFO - Revenda Exodus Informática organizada com sucesso !
[2025-06-25T04:31:02.425+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89280-328/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cba90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:02.425+0000] {logging_mixin.py:188} INFO - Revenda Extrema Software de Gestão organizada com sucesso !
[2025-06-25T04:31:02.559+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/63660-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cb550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:02.559+0000] {logging_mixin.py:188} INFO - Revenda F5 Suporte e Automacão Comercial organizada com sucesso !
[2025-06-25T04:31:03.705+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/13273-410/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4340>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:03.707+0000] {logging_mixin.py:188} INFO - Revenda Facilita Sistemas organizada com sucesso !
[2025-06-25T04:31:04.857+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95670-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862e20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:04.858+0000] {logging_mixin.py:188} INFO - Revenda Facilsys organizada com sucesso !
[2025-06-25T04:31:06.009+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58808-485/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b7d90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:06.010+0000] {logging_mixin.py:188} INFO - Revenda F & F Soluções Empresariais organizada com sucesso !
[2025-06-25T04:31:07.161+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88160-064/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cb370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:07.162+0000] {logging_mixin.py:188} INFO - Revenda FKSIS - Sistemas de Gestão organizada com sucesso !
[2025-06-25T04:31:08.313+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88354-610/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cbf40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:08.314+0000] {logging_mixin.py:188} INFO - Revenda FlorySoftt organizada com sucesso !
[2025-06-25T04:31:09.465+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/23860-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:09.466+0000] {logging_mixin.py:188} INFO - Revenda Fn Info House organizada com sucesso !
[2025-06-25T04:31:09.597+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/63502-769/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:09.598+0000] {logging_mixin.py:188} INFO - Revenda FS Informatica organizada com sucesso !
[2025-06-25T04:31:10.746+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/84320-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8af0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:10.747+0000] {logging_mixin.py:188} INFO - Revenda Fusion Sistemas e Informatica organizada com sucesso !
[2025-06-25T04:31:11.898+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59900-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c80a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:11.899+0000] {logging_mixin.py:188} INFO - Revenda Gilmaq Automação Comercial organizada com sucesso !
[2025-06-25T04:31:13.049+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55825-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cb9a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:13.050+0000] {logging_mixin.py:188} INFO - Revenda GM Soluções em Informática organizada com sucesso !
[2025-06-25T04:31:14.201+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/01311-927/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cb4c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:14.202+0000] {logging_mixin.py:188} INFO - Revenda Grupo GUUW organizada com sucesso !
[2025-06-25T04:31:15.353+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37800-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862af0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:15.353+0000] {logging_mixin.py:188} INFO - Revenda Guaxutec organizada com sucesso !
[2025-06-25T04:31:16.505+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88508-190/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:16.506+0000] {logging_mixin.py:188} INFO - Revenda HSI Automação Comercial organizada com sucesso !
[2025-06-25T04:31:16.635+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/20756-100/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862e20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:16.636+0000] {logging_mixin.py:188} INFO - Revenda HWC Soluções organizada com sucesso !
[2025-06-25T04:31:17.785+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59500-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862af0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:17.786+0000] {logging_mixin.py:188} INFO - Revenda I7 Automação Comercial organizada com sucesso !
[2025-06-25T04:31:18.937+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29280-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cb610>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:18.937+0000] {logging_mixin.py:188} INFO - Revenda Ideal Soluções Empresariais organizada com sucesso !
[2025-06-25T04:31:20.091+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59570-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cb670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:20.091+0000] {logging_mixin.py:188} INFO - Revenda ID Tecnologia organizada com sucesso !
[2025-06-25T04:31:21.241+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/06454-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8d00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:21.242+0000] {logging_mixin.py:188} INFO - Revenda IFFI Soluções organizada com sucesso !
[2025-06-25T04:31:22.394+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/69980-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:22.395+0000] {logging_mixin.py:188} INFO - Revenda IG TEC organizada com sucesso !
[2025-06-25T04:31:22.526+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58900-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4be0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:22.527+0000] {logging_mixin.py:188} INFO - Revenda INFOPRINTER organizada com sucesso !
[2025-06-25T04:31:23.673+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21011-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:23.674+0000] {logging_mixin.py:188} INFO - Revenda INFORMIT organizada com sucesso !
[2025-06-25T04:31:24.826+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/69303-045/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cbb50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:24.827+0000] {logging_mixin.py:188} INFO - Revenda Infor Serviços organizada com sucesso !
[2025-06-25T04:31:25.977+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/48601-270/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cb850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:25.978+0000] {logging_mixin.py:188} INFO - Revenda Infortec Automacao Comercial organizada com sucesso !
[2025-06-25T04:31:27.130+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46430-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862eb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:27.131+0000] {logging_mixin.py:188} INFO - Revenda Infotek organizada com sucesso !
[2025-06-25T04:31:28.282+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/26535-190/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:28.283+0000] {logging_mixin.py:188} INFO - Revenda Innovati Tecnologia (INW Store) organizada com sucesso !
[2025-06-25T04:31:29.432+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50865-090/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c49d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:29.433+0000] {logging_mixin.py:188} INFO - Revenda Inova Software organizada com sucesso !
[2025-06-25T04:31:29.565+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55130-970/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:29.565+0000] {logging_mixin.py:188} INFO - Revenda Inspire Consult & Informatica  organizada com sucesso !
[2025-06-25T04:31:30.712+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89801-106/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:30.712+0000] {logging_mixin.py:188} INFO - Revenda Inteltix Tecnologia (Center) organizada com sucesso !
[2025-06-25T04:31:31.864+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/79823-290/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84bd00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:31.865+0000] {logging_mixin.py:188} INFO - Revenda J7 Automação Comercial - System HD organizada com sucesso !
[2025-06-25T04:31:33.017+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78360-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cb4c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:33.018+0000] {logging_mixin.py:188} INFO - Revenda Jann Informatica organizada com sucesso !
[2025-06-25T04:31:34.169+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/76997-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cbf70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:34.170+0000] {logging_mixin.py:188} INFO - Revenda JB Tecnologia organizada com sucesso !
[2025-06-25T04:31:35.321+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/68460-245/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:35.321+0000] {logging_mixin.py:188} INFO - Revenda J & E Soluções organizada com sucesso !
[2025-06-25T04:31:36.472+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46430-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d74c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:36.473+0000] {logging_mixin.py:188} INFO - Revenda JExpress organizada com sucesso !
[2025-06-25T04:31:36.604+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58077-062/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cba90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:36.604+0000] {logging_mixin.py:188} INFO - Revenda J F Soluções Informatica organizada com sucesso !
[2025-06-25T04:31:37.754+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/69058-580/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7cbaf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:37.755+0000] {logging_mixin.py:188} INFO - Revenda J F Tech Tecnologia & Sistemas organizada com sucesso !
[2025-06-25T04:31:38.906+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/31255-780/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:38.907+0000] {logging_mixin.py:188} INFO - Revenda JHLS Automação Comercial organizada com sucesso !
[2025-06-25T04:31:40.057+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/12914-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:40.058+0000] {logging_mixin.py:188} INFO - Revenda Jinsei Contabilidade organizada com sucesso !
[2025-06-25T04:31:41.210+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/27197-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:41.211+0000] {logging_mixin.py:188} INFO - Revenda JJ Serviços organizada com sucesso !
[2025-06-25T04:31:42.360+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/49055-620/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:42.361+0000] {logging_mixin.py:188} INFO - Revenda JM Informatica organizada com sucesso !
[2025-06-25T04:31:43.514+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89220-110/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8625b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:43.515+0000] {logging_mixin.py:188} INFO - Revenda JP Automação Comercial organizada com sucesso !
[2025-06-25T04:31:43.644+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78250-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b1f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:43.645+0000] {logging_mixin.py:188} INFO - Revenda JSR Automação Comercial  organizada com sucesso !
[2025-06-25T04:31:44.793+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89700-166/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:44.793+0000] {logging_mixin.py:188} INFO - Revenda Kernel Sistemas organizada com sucesso !
[2025-06-25T04:31:45.945+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/14010-180/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:45.946+0000] {logging_mixin.py:188} INFO - Revenda KMCI Tecnologia em Automação organizada com sucesso !
[2025-06-25T04:31:47.098+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/25555-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:47.098+0000] {logging_mixin.py:188} INFO - Revenda Komputronic do Brasil organizada com sucesso !
[2025-06-25T04:31:48.249+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29052-170/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:48.250+0000] {logging_mixin.py:188} INFO - Revenda KSC Sistemas organizada com sucesso !
[2025-06-25T04:31:49.401+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50010-100/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c88b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:49.402+0000] {logging_mixin.py:188} INFO - Revenda L&D Comercio e Tecnologia organizada com sucesso !
[2025-06-25T04:31:49.533+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/25935-530/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:49.534+0000] {logging_mixin.py:188} INFO - Revenda LD Tech organizada com sucesso !
[2025-06-25T04:31:50.681+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29375-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:50.682+0000] {logging_mixin.py:188} INFO - Revenda LF Sistemas organizada com sucesso !
[2025-06-25T04:31:51.833+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/39400-215/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:51.833+0000] {logging_mixin.py:188} INFO - Revenda LiderTech organizada com sucesso !
[2025-06-25T04:31:52.985+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/93700-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:52.986+0000] {logging_mixin.py:188} INFO - Revenda Life Sistemas  organizada com sucesso !
[2025-06-25T04:31:54.138+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/20250-450/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c42e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:54.138+0000] {logging_mixin.py:188} INFO - Revenda LL Tecnologia organizada com sucesso !
[2025-06-25T04:31:55.289+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/36884-004/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4a90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:55.290+0000] {logging_mixin.py:188} INFO - Revenda LMD Sistemas organizada com sucesso !
[2025-06-25T04:31:56.441+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/22730-001/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8629d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:56.442+0000] {logging_mixin.py:188} INFO - Revenda Logitec 2000 Informatica organizada com sucesso !
[2025-06-25T04:31:56.571+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37470-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862e80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:56.572+0000] {logging_mixin.py:188} INFO - Revenda Macmos organizada com sucesso !
[2025-06-25T04:31:57.721+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59300-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:57.722+0000] {logging_mixin.py:188} INFO - Revenda Mape Informatica organizada com sucesso !
[2025-06-25T04:31:58.873+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89900-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c81c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:31:58.874+0000] {logging_mixin.py:188} INFO - Revenda Marcka Informática e Sistemas organizada com sucesso !
[2025-06-25T04:32:00.024+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/58041-070/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4d30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:00.024+0000] {logging_mixin.py:188} INFO - Revenda Matechinfo organizada com sucesso !
[2025-06-25T04:32:01.177+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88355-393/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:01.178+0000] {logging_mixin.py:188} INFO - Revenda MB Tecnologia organizada com sucesso !
[2025-06-25T04:32:02.329+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/82015-520/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:02.329+0000] {logging_mixin.py:188} INFO - Revenda MC2 Tecnologia organizada com sucesso !
[2025-06-25T04:32:03.481+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89562-180/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:03.482+0000] {logging_mixin.py:188} INFO - Revenda MCR Sistemas (RS-AMX) organizada com sucesso !
[2025-06-25T04:32:03.612+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21660-060/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b76a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:03.612+0000] {logging_mixin.py:188} INFO - Revenda MD Tech Automação organizada com sucesso !
[2025-06-25T04:32:04.762+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46430-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:04.762+0000] {logging_mixin.py:188} INFO - Revenda Megasoft Informatica organizada com sucesso !
[2025-06-25T04:32:05.915+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95270-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4d90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:05.918+0000] {logging_mixin.py:188} INFO - Revenda Mercantec Soluções organizada com sucesso !
[2025-06-25T04:32:07.065+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88310-661/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862a90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:07.066+0000] {logging_mixin.py:188} INFO - Revenda Mikrox "Somadatta" organizada com sucesso !
[2025-06-25T04:32:08.218+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/63010-127/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:08.219+0000] {logging_mixin.py:188} INFO - Revenda M. Nobre (Terabyte) organizada com sucesso !
[2025-06-25T04:32:09.369+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/32310-210/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862c70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:09.369+0000] {logging_mixin.py:188} INFO - Revenda MRsis Automação organizada com sucesso !
[2025-06-25T04:32:09.498+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37062-170/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84bd00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:09.499+0000] {logging_mixin.py:188} INFO - Revenda M&R Soluções - Grupo ATL organizada com sucesso !
[2025-06-25T04:32:10.650+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/47640-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:10.650+0000] {logging_mixin.py:188} INFO - Revenda Multi Soft organizada com sucesso !
[2025-06-25T04:32:11.801+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78390-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c81c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:11.802+0000] {logging_mixin.py:188} INFO - Revenda NewCompras.com.br organizada com sucesso !
[2025-06-25T04:32:12.953+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/67030-080/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:12.954+0000] {logging_mixin.py:188} INFO - Revenda NEWTEF Automação organizada com sucesso !
[2025-06-25T04:32:14.106+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50960-400/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83c1f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:14.106+0000] {logging_mixin.py:188} INFO - Revenda Next Store organizada com sucesso !
[2025-06-25T04:32:15.259+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37730-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83ca90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:15.260+0000] {logging_mixin.py:188} INFO - Revenda Nova Loja organizada com sucesso !
[2025-06-25T04:32:16.409+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/17210-420/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8a90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:16.410+0000] {logging_mixin.py:188} INFO - Revenda NovaPC organizada com sucesso !
[2025-06-25T04:32:16.539+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/39400-163/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b7790>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:16.539+0000] {logging_mixin.py:188} INFO - Revenda Optimus - Gestão organizada com sucesso !
[2025-06-25T04:32:17.690+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/98803-412/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:17.690+0000] {logging_mixin.py:188} INFO - Revenda Otimizer Consultoria em Sistemas organizada com sucesso !
[2025-06-25T04:32:18.840+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/62500-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:18.841+0000] {logging_mixin.py:188} INFO - Revenda Otimize Soluções organizada com sucesso !
[2025-06-25T04:32:19.994+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95034-160/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:19.994+0000] {logging_mixin.py:188} INFO - Revenda P21 Software organizada com sucesso !
[2025-06-25T04:32:21.147+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50980-480/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83c130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:21.148+0000] {logging_mixin.py:188} INFO - Revenda PALM Soluções organizada com sucesso !
[2025-06-25T04:32:22.297+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/84040-010/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:22.298+0000] {logging_mixin.py:188} INFO - Revenda Parceria Informatica organizada com sucesso !
[2025-06-25T04:32:23.449+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88330-725/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d72b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:23.450+0000] {logging_mixin.py:188} INFO - Revenda PDV Automação organizada com sucesso !
[2025-06-25T04:32:23.581+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/38700-001/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7e80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:23.581+0000] {logging_mixin.py:188} INFO - Revenda PEG Informatica organizada com sucesso !
[2025-06-25T04:32:24.729+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95200-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b610>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:24.730+0000] {logging_mixin.py:188} INFO - Revenda Piramide Automação e Informatica organizada com sucesso !
[2025-06-25T04:32:25.881+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/70314-900/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c80d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:25.882+0000] {logging_mixin.py:188} INFO - Revenda Plus Solutions organizada com sucesso !
[2025-06-25T04:32:27.033+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88350-564/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:27.034+0000] {logging_mixin.py:188} INFO - Revenda Ponte organizada com sucesso !
[2025-06-25T04:32:28.185+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29700-550/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c4370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:28.185+0000] {logging_mixin.py:188} INFO - Revenda Pratic Informática organizada com sucesso !
[2025-06-25T04:32:29.335+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/65930-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8a00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:29.336+0000] {logging_mixin.py:188} INFO - Revenda PROFISC - Consultoria  organizada com sucesso !
[2025-06-25T04:32:30.489+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws//json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b1f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:30.490+0000] {logging_mixin.py:188} INFO - Revenda Pryamos organizada com sucesso !
[2025-06-25T04:32:30.620+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46380-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:30.621+0000] {logging_mixin.py:188} INFO - Revenda Quality Automação e Recargas organizada com sucesso !
[2025-06-25T04:32:31.771+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/76963-586/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:31.772+0000] {logging_mixin.py:188} INFO - Revenda Rafah Soluções em Sistema organizada com sucesso !
[2025-06-25T04:32:32.920+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89803-460/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:32.921+0000] {logging_mixin.py:188} INFO - Revenda RC Automação organizada com sucesso !
[2025-06-25T04:32:34.073+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/05761-340/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:34.073+0000] {logging_mixin.py:188} INFO - Revenda RCM Tecnologia organizada com sucesso !
[2025-06-25T04:32:35.225+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/15910-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8624f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:35.226+0000] {logging_mixin.py:188} INFO - Revenda RedeEllo organizada com sucesso !
[2025-06-25T04:32:36.378+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/56310-130/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:36.379+0000] {logging_mixin.py:188} INFO - Revenda Rieger Consultoria e Serviços  organizada com sucesso !
[2025-06-25T04:32:36.506+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88104-435/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7c70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:36.507+0000] {logging_mixin.py:188} INFO - Revenda RKS Tecnologia organizada com sucesso !
[2025-06-25T04:32:37.657+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/76960-046/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84bdf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:37.658+0000] {logging_mixin.py:188} INFO - Revenda Rondoniatec Sistemas e Soluções organizada com sucesso !
[2025-06-25T04:32:38.812+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/48602-005/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:38.813+0000] {logging_mixin.py:188} INFO - Revenda Royal Ti organizada com sucesso !
[2025-06-25T04:32:39.960+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/28895-320/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c85b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:39.961+0000] {logging_mixin.py:188} INFO - Revenda RPD Tech Soluções em T.I. organizada com sucesso !
[2025-06-25T04:32:41.113+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/87970-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83c250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:41.114+0000] {logging_mixin.py:188} INFO - Revenda RPDV Soluções em Tecnologia organizada com sucesso !
[2025-06-25T04:32:42.267+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/55825-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c85e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:42.268+0000] {logging_mixin.py:188} INFO - Revenda RS Informatica organizada com sucesso !
[2025-06-25T04:32:43.418+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/31270-350/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84bd00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:43.419+0000] {logging_mixin.py:188} INFO - Revenda Rtek organizada com sucesso !
[2025-06-25T04:32:43.550+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89204-050/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7e20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:43.550+0000] {logging_mixin.py:188} INFO - Revenda SDN Sistemas de Gestão organizada com sucesso !
[2025-06-25T04:32:44.697+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/12914-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8a7be0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:44.698+0000] {logging_mixin.py:188} INFO - Revenda Seed Tecnologia organizada com sucesso !
[2025-06-25T04:32:45.849+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29560-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862910>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:45.850+0000] {logging_mixin.py:188} INFO - Revenda Shopseg Sistemas organizada com sucesso !
[2025-06-25T04:32:47.001+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88350-100/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d9370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:47.002+0000] {logging_mixin.py:188} INFO - Revenda Sig Sistemas Corporativos organizada com sucesso !
[2025-06-25T04:32:48.152+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/63034-150/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862eb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:48.153+0000] {logging_mixin.py:188} INFO - Revenda Sistech Sistemas organizada com sucesso !
[2025-06-25T04:32:49.316+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88350-270/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8628b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:49.321+0000] {logging_mixin.py:188} INFO - Revenda Sistema Completo organizada com sucesso !
[2025-06-25T04:32:50.456+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/45028-190/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d74f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:50.457+0000] {logging_mixin.py:188} INFO - Revenda Sistema Uniplus - Vitória da Conquista organizada com sucesso !
[2025-06-25T04:32:50.585+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/39680-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b0d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:50.586+0000] {logging_mixin.py:188} INFO - Revenda Skill Automação Comercial organizada com sucesso !
[2025-06-25T04:32:51.738+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88130-650/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:51.739+0000] {logging_mixin.py:188} INFO - Revenda SM10 Sistemas de Gestão e Automação Comercial  (AM10) organizada com sucesso !
[2025-06-25T04:32:52.890+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/79540-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:52.891+0000] {logging_mixin.py:188} INFO - Revenda Smith Tecnologias organizada com sucesso !
[2025-06-25T04:32:54.042+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50720-090/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d9c10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:54.043+0000] {logging_mixin.py:188} INFO - Revenda SMQ Tecnologia organizada com sucesso !
[2025-06-25T04:32:55.193+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/44061-070/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c84f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:55.194+0000] {logging_mixin.py:188} INFO - Revenda Softech Tecnologia organizada com sucesso !
[2025-06-25T04:32:56.346+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/62011-205/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:56.346+0000] {logging_mixin.py:188} INFO - Revenda SoftGadol organizada com sucesso !
[2025-06-25T04:32:57.497+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/60822-305/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:57.498+0000] {logging_mixin.py:188} INFO - Revenda Softkore organizada com sucesso !
[2025-06-25T04:32:57.627+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/27920-325/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:57.628+0000] {logging_mixin.py:188} INFO - Revenda Softmaq organizada com sucesso !
[2025-06-25T04:32:58.778+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/61655-590/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862c10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:58.779+0000] {logging_mixin.py:188} INFO - Revenda Solem Tecnologia organizada com sucesso !
[2025-06-25T04:32:59.929+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95700-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d9490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:32:59.930+0000] {logging_mixin.py:188} INFO - Revenda Sonaglio Automação organizada com sucesso !
[2025-06-25T04:33:01.080+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50720-715/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862d30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:01.081+0000] {logging_mixin.py:188} INFO - Revenda Sonsun organizada com sucesso !
[2025-06-25T04:33:02.233+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/50721-040/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7013da4070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:02.234+0000] {logging_mixin.py:188} INFO - Revenda Sophos Projetos organizada com sucesso !
[2025-06-25T04:33:03.385+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/99260-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d9d30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:03.386+0000] {logging_mixin.py:188} INFO - Revenda Sparta Gestão e Contabilidade - DEOCLESYSTEM organizada com sucesso !
[2025-06-25T04:33:03.517+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37470-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d9310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:03.518+0000] {logging_mixin.py:188} INFO - Revenda Speed Automação Comercial organizada com sucesso !
[2025-06-25T04:33:04.663+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/46400-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8340>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:04.664+0000] {logging_mixin.py:188} INFO - Revenda SS Informatica - Bahia organizada com sucesso !
[2025-06-25T04:33:05.817+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/65070-280/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83cbb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:05.818+0000] {logging_mixin.py:188} INFO - Revenda SS Informática - Maranhão organizada com sucesso !
[2025-06-25T04:33:06.968+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59607-340/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83c9a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:06.969+0000] {logging_mixin.py:188} INFO - Revenda Syscom Sistemas organizada com sucesso !
[2025-06-25T04:33:08.122+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/45075-290/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:08.123+0000] {logging_mixin.py:188} INFO - Revenda SYSFOUR - Intelligent Systems organizada com sucesso !
[2025-06-25T04:33:09.274+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89295-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b7d90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:09.274+0000] {logging_mixin.py:188} INFO - Revenda System Bella Automação Comercial organizada com sucesso !
[2025-06-25T04:33:10.425+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89801-570/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:10.426+0000] {logging_mixin.py:188} INFO - Revenda TB Automação e Informática organizada com sucesso !
[2025-06-25T04:33:10.555+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/59031-170/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d83c970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:10.555+0000] {logging_mixin.py:188} INFO - Revenda TC Maquinas organizada com sucesso !
[2025-06-25T04:33:11.706+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/60750-030/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d9160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:11.706+0000] {logging_mixin.py:188} INFO - Revenda Technoside Informatica organizada com sucesso !
[2025-06-25T04:33:14.905+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/65800-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d95e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:14.905+0000] {logging_mixin.py:188} INFO - Revenda Tecmicro Informática organizada com sucesso !
[2025-06-25T04:33:15.036+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/79004-460/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d96a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:15.036+0000] {logging_mixin.py:188} INFO - Revenda Tecnoinfo organizada com sucesso !
[2025-06-25T04:33:16.186+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/68525-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:16.186+0000] {logging_mixin.py:188} INFO - Revenda TECSOLUTION organizada com sucesso !
[2025-06-25T04:33:17.337+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29050-565/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:17.338+0000] {logging_mixin.py:188} INFO - Revenda Tefcom organizada com sucesso !
[2025-06-25T04:33:18.489+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/68909-845/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b7790>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:18.490+0000] {logging_mixin.py:188} INFO - Revenda TFA Tecnologia e Soluções  organizada com sucesso !
[2025-06-25T04:33:18.621+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95020-520/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:18.621+0000] {logging_mixin.py:188} INFO - Revenda TI-Brasil Sistemas organizada com sucesso !
[2025-06-25T04:33:19.769+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/95084-200/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d61f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:19.770+0000] {logging_mixin.py:188} INFO - Revenda Trends Solutions organizada com sucesso !
[2025-06-25T04:33:20.922+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/67013-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d6a90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:20.923+0000] {logging_mixin.py:188} INFO - Revenda TS TECH organizada com sucesso !
[2025-06-25T04:33:22.074+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89560-132/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c87f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:22.074+0000] {logging_mixin.py:188} INFO - Revenda Unisoft Sistemas ** Hardtech organizada com sucesso !
[2025-06-25T04:33:23.225+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/88070-770/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b7dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:23.225+0000] {logging_mixin.py:188} INFO - Revenda Unitek Soluções organizada com sucesso !
[2025-06-25T04:33:24.377+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/20040-030/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862a90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:24.378+0000] {logging_mixin.py:188} INFO - Revenda Uniup Sistema - Automação e CFTV organizada com sucesso !
[2025-06-25T04:33:24.509+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89222-363/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d6670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:24.510+0000] {logging_mixin.py:188} INFO - Revenda Universal Automação Comercial  organizada com sucesso !
[2025-06-25T04:33:25.656+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/78550-104/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d71f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:25.657+0000] {logging_mixin.py:188} INFO - Revenda Universo Sistemas organizada com sucesso !
[2025-06-25T04:33:26.809+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89620-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7a90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:26.810+0000] {logging_mixin.py:188} INFO - Revenda Valor Tecnologia organizada com sucesso !
[2025-06-25T04:33:27.962+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/98700-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d6ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:27.963+0000] {logging_mixin.py:188} INFO - Revenda VGI TECHNOLOGY organizada com sucesso !
[2025-06-25T04:33:29.114+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/87504-480/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:29.114+0000] {logging_mixin.py:188} INFO - Revenda Via Nova Soluções em Tecnologia organizada com sucesso !
[2025-06-25T04:33:30.266+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/37890-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d84b760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:30.266+0000] {logging_mixin.py:188} INFO - Revenda Virtual Informatica_MG organizada com sucesso !
[2025-06-25T04:33:31.416+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89136-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c85b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:31.416+0000] {logging_mixin.py:188} INFO - Revenda Virtual Sistemas_SC organizada com sucesso !
[2025-06-25T04:33:31.546+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/26260-580/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:31.547+0000] {logging_mixin.py:188} INFO - Revenda VPN Solucoes em Informatica organizada com sucesso !
[2025-06-25T04:33:32.697+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/89245-000/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:32.698+0000] {logging_mixin.py:188} INFO - Revenda Vzan Automação Comercial organizada com sucesso !
[2025-06-25T04:33:33.851+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/21532-460/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8353a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:33.852+0000] {logging_mixin.py:188} INFO - Revenda Walltech Informatica organizada com sucesso !
[2025-06-25T04:33:35.002+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/29103-240/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7c8550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:35.003+0000] {logging_mixin.py:188} INFO - Revenda W C Sistemas organizada com sucesso !
[2025-06-25T04:33:36.152+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/06280-150/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d8b77c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:36.152+0000] {logging_mixin.py:188} INFO - Revenda WGE informatica organizada com sucesso !
[2025-06-25T04:33:37.305+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/31080-365/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d862730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:37.306+0000] {logging_mixin.py:188} INFO - Revenda WMX Soluções em Tecnologia organizada com sucesso !
[2025-06-25T04:33:38.457+0000] {logging_mixin.py:188} INFO - Erro no get_geolocalization: HTTPSConnectionPool(host='viacep.com.br', port=443): Max retries exceeded with url: /ws/30710-580/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f700d7d7af0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-06-25T04:33:38.458+0000] {logging_mixin.py:188} INFO - Revenda X1 Automação organizada com sucesso !
[2025-06-25T04:33:38.534+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-25T04:33:38.558+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=DAG_atualizacao_cadastral_revendas, task_id=organized_response_database, execution_date=20250624T043000, start_date=20250625T043006, end_date=20250625T043338
[2025-06-25T04:33:38.637+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-25T04:33:38.673+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
